<a href="https://colab.research.google.com/github/wajd-mq/wajd-mq/blob/main/DL1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("henilj7/iphone-purchase-records")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'iphone-purchase-records' dataset.
Path to dataset files: /kaggle/input/iphone-purchase-records

In [ ]:
import kagglehub
import pandas as pd
import os

# Download dataset
path = kagglehub.dataset_download("henilj7/iphone-purchase-records")

print(path)

# عرض الملفات الموجودة
print(os.listdir(path))

Using Colab cache for faster access to the 'iphone-purchase-records' dataset.
/kaggle/input/iphone-purchase-records
['iphone_purchase_records.csv']

In [ ]:
df = pd.read_csv(os.path.join(path, "iphone_purchase_records.csv"))

df.head()

   Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64
 2   Salary           400 non-null    int64
 3   Purchase Iphone  400 non-null    int64
dtypes: int64(3), object(1)
memory usage: 12.6+ KB

In [ ]:

df.describe()

              Age         Salary  Purchase Iphone
count  400.000000     400.000000       400.000000
mean    37.655000   69742.500000         0.357500
std     10.482877   34096.960282         0.479864
min     18.000000   15000.000000         0.000000
25%     29.750000   43000.000000         0.000000
50%     37.000000   70000.000000         0.000000
75%     46.000000   88000.000000         1.000000
max     60.000000  150000.000000         1.000000

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Gender"] = le.fit_transform(df["Gender"])

In [ ]:
X = df[["Gender","Age","Salary"]]

y = df["Purchase Iphone"]

In [ ]:
for col in df.columns:
    print(col)

Gender
Age
Salary
Purchase Iphone

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()

# Input Layer (3 Features)
model.add(Dense(
    8,
    activation='relu',
    input_shape=(3,)
))

# Hidden Layer
model.add(Dense(
    4,
    activation='relu'
))

# Output Layer
model.add(Dense(
    1,
    activation='sigmoid'
))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 8)              │            32 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 73 (292.00 B)

 Trainable params: 73 (292.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.4023 - loss: 0.7128 - val_accuracy: 0.4688 - val_loss: 0.7458
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5508 - loss: 0.6860 - val_accuracy: 0.5469 - val_loss: 0.7195
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5859 - loss: 0.6664 - val_accuracy: 0.5625 - val_loss: 0.6988
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5977 - loss: 0.6497 - val_accuracy: 0.6094 - val_loss: 0.6794
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6445 - loss: 0.6339 - val_accuracy: 0.7031 - val_loss: 0.6617
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7109 - loss: 0.6195 - val_accuracy: 0.7969 - val_loss: 0.6459
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7422 - loss: 0.6059 - val_accuracy: 0.7969 - val_loss: 0.6328
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7891 - loss: 0.5935 - val_accuracy: 0.7969 - val_loss: 0.6212
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8242 - loss: 0.5819 - val_accuracy: 0.8125 - val_loss: 0.6101
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.5697 - val_accuracy: 0.8438 - val_loss: 0.5992
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.5576 - val_accuracy: 0.8750 - val_loss: 0.5889
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.5453 - val_accuracy: 0.8750 - val_loss: 0.5774
Epoch 13/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8555 - loss: 0.5333 - val_accuracy: 0.8750 - val_loss: 0.5650
Epoch 14/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8633 - loss: 0.5200 - val_accuracy: 0.8906 - val_loss: 0.5526
Epoch 15/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.5077 - val_accuracy: 0.8906 - val_loss: 0.5397
Epoch 16/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.4945 - val_accuracy: 0.8906 - val_loss: 0.5263
Epoch 17/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8750 - loss: 0.4817 - val_accuracy: 0.8906 - val_loss: 0.5123
Epoch 18/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.4681 - val_accuracy: 0.8750 - val_loss: 0.4991
Epoch 19/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.4550 - val_accuracy: 0.8750 - val_loss: 0.4859
Epoch 20/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.4415 - val_accuracy: 0.8750 - val_loss: 0.4720
Epoch 21/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.4286 - val_accuracy: 0.8750 - val_loss: 0.4575
Epoch 22/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.4160 - val_accuracy: 0.8750 - val_loss: 0.4448
Epoch 23/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.4037 - val_accuracy: 0.8750 - val_loss: 0.4335
Epoch 24/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3923 - val_accuracy: 0.8750 - val_loss: 0.4207
Epoch 25/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3811 - val_accuracy: 0.8750 - val_loss: 0.4095
Epoch 26/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3706 - val_accuracy: 0.8750 - val_loss: 0.3995
Epoch 27/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3614 - val_accuracy: 0.8750 - val_loss: 0.3901
Epoch 28/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3522 - val_accuracy: 0.8906 - val_loss: 0.3817
Epoch 29/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3443 - val_accuracy: 0.8906 - val_loss: 0.3723
Epoch 30/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3363 - val_accuracy: 0.8906 - val_loss: 0.3643
Epoch 31/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3291 - val_accuracy: 0.8906 - val_loss: 0.3583
Epoch 32/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3230 - val_accuracy: 0.8906 - val_loss: 0.3518
Epoch 33/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3165 - val_accuracy: 0.8906 - val_loss: 0.3459
Epoch 34/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8984 - loss: 0.3110 - val_accuracy: 0.8906 - val_loss: 0.3412
Epoch 35/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.3055 - val_accuracy: 0.8906 - val_loss: 0.3369
Epoch 36/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.3008 - val_accuracy: 0.8906 - val_loss: 0.3323
Epoch 37/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2962 - val_accuracy: 0.8906 - val_loss: 0.3276
Epoch 38/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2920 - val_accuracy: 0.8906 - val_loss: 0.3249
Epoch 39/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2880 - val_accuracy: 0.8906 - val_loss: 0.3213
Epoch 40/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2848 - val_accuracy: 0.8906 - val_loss: 0.3183
Epoch 41/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2819 - val_accuracy: 0.8906 - val_loss: 0.3146
Epoch 42/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9062 - loss: 0.2790 - val_accuracy: 0.8906 - val_loss: 0.3135
Epoch 43/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9062 - loss: 0.2760 - val_accuracy: 0.8906 - val_loss: 0.3116
Epoch 44/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2738 - val_accuracy: 0.8906 - val_loss: 0.3083
Epoch 45/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2717 - val_accuracy: 0.8906 - val_loss: 0.3065
Epoch 46/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2699 - val_accuracy: 0.8906 - val_loss: 0.3046
Epoch 47/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2678 - val_accuracy: 0.8906 - val_loss: 0.3057
Epoch 48/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2657 - val_accuracy: 0.8906 - val_loss: 0.3041
Epoch 49/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2641 - val_accuracy: 0.8906 - val_loss: 0.3021
Epoch 50/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2623 - val_accuracy: 0.8906 - val_loss: 0.3008
Epoch 51/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2611 - val_accuracy: 0.8906 - val_loss: 0.3006
Epoch 52/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9102 - loss: 0.2596 - val_accuracy: 0.8906 - val_loss: 0.3007
Epoch 53/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2581 - val_accuracy: 0.8906 - val_loss: 0.2993
Epoch 54/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2574 - val_accuracy: 0.8906 - val_loss: 0.2989
Epoch 55/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2559 - val_accuracy: 0.8906 - val_loss: 0.2971
Epoch 56/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2547 - val_accuracy: 0.8906 - val_loss: 0.2965
Epoch 57/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2540 - val_accuracy: 0.8906 - val_loss: 0.2957
Epoch 58/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2529 - val_accuracy: 0.8906 - val_loss: 0.2957
Epoch 59/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2515 - val_accuracy: 0.8906 - val_loss: 0.2954
Epoch 60/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9141 - loss: 0.2508 - val_accuracy: 0.8906 - val_loss: 0.2952
Epoch 61/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2501 - val_accuracy: 0.8906 - val_loss: 0.2954
Epoch 62/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2493 - val_accuracy: 0.8906 - val_loss: 0.2937
Epoch 63/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2486 - val_accuracy: 0.8906 - val_loss: 0.2928
Epoch 64/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2484 - val_accuracy: 0.8906 - val_loss: 0.2947
Epoch 65/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2474 - val_accuracy: 0.8906 - val_loss: 0.2931
Epoch 66/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2472 - val_accuracy: 0.8906 - val_loss: 0.2944
Epoch 67/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2465 - val_accuracy: 0.8906 - val_loss: 0.2955
Epoch 68/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2456 - val_accuracy: 0.8906 - val_loss: 0.2920
Epoch 69/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9141 - loss: 0.2453 - val_accuracy: 0.8906 - val_loss: 0.2930
Epoch 70/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2445 - val_accuracy: 0.8906 - val_loss: 0.2910
Epoch 71/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2440 - val_accuracy: 0.8906 - val_loss: 0.2911
Epoch 72/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9141 - loss: 0.2444 - val_accuracy: 0.8906 - val_loss: 0.2937
Epoch 73/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9141 - loss: 0.2433 - val_accuracy: 0.8906 - val_loss: 0.2925
Epoch 74/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9141 - loss: 0.2430 - val_accuracy: 0.8906 - val_loss: 0.2920
Epoch 75/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9141 - loss: 0.2423 - val_accuracy: 0.8906 - val_loss: 0.2920
Epoch 76/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9141 - loss: 0.2430 - val_accuracy: 0.8906 - val_loss: 0.2897
Epoch 77/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9141 - loss: 0.2415 - val_accuracy: 0.8906 - val_loss: 0.2911
Epoch 78/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9141 - loss: 0.2414 - val_accuracy: 0.8906 - val_loss: 0.2924
Epoch 79/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9141 - loss: 0.2408 - val_accuracy: 0.8906 - val_loss: 0.2930
Epoch 80/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9141 - loss: 0.2410 - val_accuracy: 0.8906 - val_loss: 0.2937
Epoch 81/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9141 - loss: 0.2405 - val_accuracy: 0.8906 - val_loss: 0.2933
Epoch 82/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9141 - loss: 0.2406 - val_accuracy: 0.8906 - val_loss: 0.2936
Epoch 83/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9141 - loss: 0.2404 - val_accuracy: 0.8906 - val_loss: 0.2904
Epoch 84/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9141 - loss: 0.2398 - val_accuracy: 0.8906 - val_loss: 0.2903
Epoch 85/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2392 - val_accuracy: 0.8906 - val_loss: 0.2912
Epoch 86/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2393 - val_accuracy: 0.8906 - val_loss: 0.2924
Epoch 87/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2391 - val_accuracy: 0.8906 - val_loss: 0.2911
Epoch 88/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2389 - val_accuracy: 0.8906 - val_loss: 0.2921
Epoch 89/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2385 - val_accuracy: 0.8906 - val_loss: 0.2915
Epoch 90/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2382 - val_accuracy: 0.8906 - val_loss: 0.2918
Epoch 91/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2385 - val_accuracy: 0.9062 - val_loss: 0.2932
Epoch 92/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2378 - val_accuracy: 0.8906 - val_loss: 0.2923
Epoch 93/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9141 - loss: 0.2379 - val_accuracy: 0.8906 - val_loss: 0.2907
Epoch 94/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2377 - val_accuracy: 0.8906 - val_loss: 0.2909
Epoch 95/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2375 - val_accuracy: 0.9062 - val_loss: 0.2921
Epoch 96/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2375 - val_accuracy: 0.8906 - val_loss: 0.2900
Epoch 97/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2370 - val_accuracy: 0.8906 - val_loss: 0.2910
Epoch 98/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2371 - val_accuracy: 0.8906 - val_loss: 0.2893
Epoch 99/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2368 - val_accuracy: 0.8906 - val_loss: 0.2911
Epoch 100/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2369 - val_accuracy: 0.9062 - val_loss: 0.2913

In [ ]:
loss, accuracy = model.evaluate(
    X_test,
    y_test
)

print("Accuracy:", accuracy)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9250 - loss: 0.1885
Accuracy: 0.925000011920929

In [ ]:
predictions = model.predict(X_test)

predictions = (predictions > 0.5).astype(int)

print(predictions[:10])

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[[1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]]

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

# Hidden Layer 1 (4 Neurons)
model.add(Dense(
    units=4,
    activation='relu',
    input_shape=(3,)
))

# Hidden Layer 2 (2 Neurons)
model.add(Dense(
    units=2,
    activation='relu'
))

# Output Layer (1 Neuron)
model.add(Dense(
    units=1,
    activation='sigmoid'
))

In [ ]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.6289 - loss: 0.6904 - val_accuracy: 0.6875 - val_loss: 0.6856
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6289 - loss: 0.6863 - val_accuracy: 0.6875 - val_loss: 0.6806
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.6817 - val_accuracy: 0.6875 - val_loss: 0.6752
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6289 - loss: 0.6768 - val_accuracy: 0.6875 - val_loss: 0.6686
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.6715 - val_accuracy: 0.6875 - val_loss: 0.6607
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.6648 - val_accuracy: 0.6875 - val_loss: 0.6520
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.6575 - val_accuracy: 0.6875 - val_loss: 0.6426
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.6489 - val_accuracy: 0.6875 - val_loss: 0.6318
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.6390 - val_accuracy: 0.6875 - val_loss: 0.6206
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.6291 - val_accuracy: 0.6875 - val_loss: 0.6094
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.6190 - val_accuracy: 0.6875 - val_loss: 0.5984
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.6097 - val_accuracy: 0.6875 - val_loss: 0.5864
Epoch 13/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6289 - loss: 0.5999 - val_accuracy: 0.6875 - val_loss: 0.5748
Epoch 14/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.5900 - val_accuracy: 0.6875 - val_loss: 0.5635
Epoch 15/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.5804 - val_accuracy: 0.6875 - val_loss: 0.5526
Epoch 16/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.5714 - val_accuracy: 0.6875 - val_loss: 0.5405
Epoch 17/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.5618 - val_accuracy: 0.6875 - val_loss: 0.5296
Epoch 18/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.5530 - val_accuracy: 0.6875 - val_loss: 0.5187
Epoch 19/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.5444 - val_accuracy: 0.6875 - val_loss: 0.5084
Epoch 20/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.5359 - val_accuracy: 0.6875 - val_loss: 0.4980
Epoch 21/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.5280 - val_accuracy: 0.6875 - val_loss: 0.4882
Epoch 22/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6289 - loss: 0.5201 - val_accuracy: 0.6875 - val_loss: 0.4794
Epoch 23/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6289 - loss: 0.5128 - val_accuracy: 0.6875 - val_loss: 0.4709
Epoch 24/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.5058 - val_accuracy: 0.6875 - val_loss: 0.4625
Epoch 25/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.4987 - val_accuracy: 0.6875 - val_loss: 0.4555
Epoch 26/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.4925 - val_accuracy: 0.6875 - val_loss: 0.4486
Epoch 27/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.4866 - val_accuracy: 0.6875 - val_loss: 0.4421
Epoch 28/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.4806 - val_accuracy: 0.6875 - val_loss: 0.4364
Epoch 29/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.4751 - val_accuracy: 0.6875 - val_loss: 0.4303
Epoch 30/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6289 - loss: 0.4697 - val_accuracy: 0.6875 - val_loss: 0.4252
Epoch 31/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6289 - loss: 0.4646 - val_accuracy: 0.6875 - val_loss: 0.4201
Epoch 32/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6641 - loss: 0.4596 - val_accuracy: 0.8125 - val_loss: 0.4153
Epoch 33/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7812 - loss: 0.4551 - val_accuracy: 0.8125 - val_loss: 0.4103
Epoch 34/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7812 - loss: 0.4507 - val_accuracy: 0.8125 - val_loss: 0.4061
Epoch 35/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7812 - loss: 0.4461 - val_accuracy: 0.8281 - val_loss: 0.4014
Epoch 36/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7773 - loss: 0.4416 - val_accuracy: 0.8281 - val_loss: 0.3966
Epoch 37/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7930 - loss: 0.4373 - val_accuracy: 0.8281 - val_loss: 0.3933
Epoch 38/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7930 - loss: 0.4327 - val_accuracy: 0.8281 - val_loss: 0.3893
Epoch 39/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7930 - loss: 0.4285 - val_accuracy: 0.8281 - val_loss: 0.3841
Epoch 40/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7891 - loss: 0.4239 - val_accuracy: 0.8281 - val_loss: 0.3806
Epoch 41/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8008 - loss: 0.4199 - val_accuracy: 0.8438 - val_loss: 0.3766
Epoch 42/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8164 - loss: 0.4157 - val_accuracy: 0.8438 - val_loss: 0.3731
Epoch 43/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8242 - loss: 0.4119 - val_accuracy: 0.8438 - val_loss: 0.3691
Epoch 44/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.4079 - val_accuracy: 0.8750 - val_loss: 0.3661
Epoch 45/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8438 - loss: 0.4038 - val_accuracy: 0.8750 - val_loss: 0.3630
Epoch 46/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8438 - loss: 0.3998 - val_accuracy: 0.8750 - val_loss: 0.3595
Epoch 47/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8438 - loss: 0.3966 - val_accuracy: 0.8750 - val_loss: 0.3565
Epoch 48/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8438 - loss: 0.3927 - val_accuracy: 0.8750 - val_loss: 0.3527
Epoch 49/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8438 - loss: 0.3896 - val_accuracy: 0.8906 - val_loss: 0.3498
Epoch 50/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8516 - loss: 0.3862 - val_accuracy: 0.8906 - val_loss: 0.3471
Epoch 51/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8555 - loss: 0.3833 - val_accuracy: 0.8906 - val_loss: 0.3454
Epoch 52/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8633 - loss: 0.3803 - val_accuracy: 0.8906 - val_loss: 0.3427
Epoch 53/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8633 - loss: 0.3775 - val_accuracy: 0.8906 - val_loss: 0.3391
Epoch 54/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8633 - loss: 0.3745 - val_accuracy: 0.8906 - val_loss: 0.3376
Epoch 55/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8633 - loss: 0.3717 - val_accuracy: 0.8906 - val_loss: 0.3351
Epoch 56/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8672 - loss: 0.3691 - val_accuracy: 0.8906 - val_loss: 0.3336
Epoch 57/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8672 - loss: 0.3662 - val_accuracy: 0.8906 - val_loss: 0.3313
Epoch 58/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8672 - loss: 0.3638 - val_accuracy: 0.8906 - val_loss: 0.3293
Epoch 59/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8711 - loss: 0.3612 - val_accuracy: 0.8906 - val_loss: 0.3277
Epoch 60/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8750 - loss: 0.3591 - val_accuracy: 0.8906 - val_loss: 0.3256
Epoch 61/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8750 - loss: 0.3563 - val_accuracy: 0.8906 - val_loss: 0.3239
Epoch 62/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8789 - loss: 0.3540 - val_accuracy: 0.8906 - val_loss: 0.3222
Epoch 63/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8750 - loss: 0.3515 - val_accuracy: 0.8906 - val_loss: 0.3210
Epoch 64/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.3492 - val_accuracy: 0.8906 - val_loss: 0.3197
Epoch 65/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.3469 - val_accuracy: 0.8906 - val_loss: 0.3182
Epoch 66/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.3446 - val_accuracy: 0.8906 - val_loss: 0.3165
Epoch 67/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.3422 - val_accuracy: 0.8906 - val_loss: 0.3154
Epoch 68/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.3402 - val_accuracy: 0.8750 - val_loss: 0.3139
Epoch 69/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.3379 - val_accuracy: 0.8750 - val_loss: 0.3122
Epoch 70/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.3358 - val_accuracy: 0.8750 - val_loss: 0.3107
Epoch 71/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.3337 - val_accuracy: 0.8750 - val_loss: 0.3099
Epoch 72/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.3318 - val_accuracy: 0.8750 - val_loss: 0.3084
Epoch 73/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.3300 - val_accuracy: 0.8750 - val_loss: 0.3065
Epoch 74/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.3277 - val_accuracy: 0.8750 - val_loss: 0.3052
Epoch 75/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.3260 - val_accuracy: 0.8750 - val_loss: 0.3040
Epoch 76/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8867 - loss: 0.3240 - val_accuracy: 0.8750 - val_loss: 0.3026
Epoch 77/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.3223 - val_accuracy: 0.8750 - val_loss: 0.3016
Epoch 78/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.3207 - val_accuracy: 0.8750 - val_loss: 0.3000
Epoch 79/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.3190 - val_accuracy: 0.8750 - val_loss: 0.2996
Epoch 80/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8867 - loss: 0.3172 - val_accuracy: 0.8750 - val_loss: 0.2978
Epoch 81/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8906 - loss: 0.3153 - val_accuracy: 0.8750 - val_loss: 0.2969
Epoch 82/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.3138 - val_accuracy: 0.8750 - val_loss: 0.2959
Epoch 83/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.3122 - val_accuracy: 0.8750 - val_loss: 0.2944
Epoch 84/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3108 - val_accuracy: 0.8750 - val_loss: 0.2942
Epoch 85/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3092 - val_accuracy: 0.8750 - val_loss: 0.2928
Epoch 86/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3074 - val_accuracy: 0.8750 - val_loss: 0.2920
Epoch 87/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3060 - val_accuracy: 0.8750 - val_loss: 0.2906
Epoch 88/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8984 - loss: 0.3044 - val_accuracy: 0.8750 - val_loss: 0.2896
Epoch 89/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8945 - loss: 0.3031 - val_accuracy: 0.8906 - val_loss: 0.2888
Epoch 90/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3017 - val_accuracy: 0.9062 - val_loss: 0.2884
Epoch 91/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3002 - val_accuracy: 0.9062 - val_loss: 0.2875
Epoch 92/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2988 - val_accuracy: 0.9062 - val_loss: 0.2865
Epoch 93/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2976 - val_accuracy: 0.9062 - val_loss: 0.2857
Epoch 94/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2962 - val_accuracy: 0.9062 - val_loss: 0.2854
Epoch 95/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2949 - val_accuracy: 0.9062 - val_loss: 0.2844
Epoch 96/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2935 - val_accuracy: 0.9062 - val_loss: 0.2837
Epoch 97/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9023 - loss: 0.2923 - val_accuracy: 0.9062 - val_loss: 0.2830
Epoch 98/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2910 - val_accuracy: 0.9062 - val_loss: 0.2825
Epoch 99/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2901 - val_accuracy: 0.9062 - val_loss: 0.2817
Epoch 100/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2887 - val_accuracy: 0.9062 - val_loss: 0.2808

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Accuracy:", accuracy)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9125 - loss: 0.2637
Accuracy: 0.9125000238418579

In [ ]:
# Import libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam


# Build Neural Network
model = Sequential()

# Hidden Layer 1 (256 neurons)
model.add(Dense(
    32,
    activation='relu',
    input_shape=(3,)
))

# Hidden Layer 2 (64 neurons)
model.add(Dense(
    16,
    activation='relu'
))

# Output Layer (1 neuron)
model.add(Dense(
    1,
    activation='sigmoid'
))


# Model Summary
model.summary()


# Compile model
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


# Train model
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)


# Evaluate model
loss, accuracy = model.evaluate(
    X_test,
    y_test
)

print("Test Accuracy:", accuracy)
print("Test Loss:", loss)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 32)             │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 673 (2.63 KB)

 Trainable params: 673 (2.63 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.6289 - loss: 0.6044 - val_accuracy: 0.6875 - val_loss: 0.5417
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6367 - loss: 0.5511 - val_accuracy: 0.7188 - val_loss: 0.4979
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7031 - loss: 0.5081 - val_accuracy: 0.7969 - val_loss: 0.4604
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7969 - loss: 0.4686 - val_accuracy: 0.8281 - val_loss: 0.4260
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8203 - loss: 0.4316 - val_accuracy: 0.9062 - val_loss: 0.3942
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3961 - val_accuracy: 0.9062 - val_loss: 0.3665
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.3667 - val_accuracy: 0.8906 - val_loss: 0.3444
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.3426 - val_accuracy: 0.8906 - val_loss: 0.3262
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.3237 - val_accuracy: 0.8750 - val_loss: 0.3135
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8828 - loss: 0.3089 - val_accuracy: 0.8750 - val_loss: 0.3023
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.2969 - val_accuracy: 0.8750 - val_loss: 0.2947
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.2875 - val_accuracy: 0.8750 - val_loss: 0.2873
Epoch 13/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2795 - val_accuracy: 0.8906 - val_loss: 0.2822
Epoch 14/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2723 - val_accuracy: 0.8906 - val_loss: 0.2775
Epoch 15/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2668 - val_accuracy: 0.8906 - val_loss: 0.2760
Epoch 16/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2618 - val_accuracy: 0.8906 - val_loss: 0.2740
Epoch 17/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2579 - val_accuracy: 0.8906 - val_loss: 0.2734
Epoch 18/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2542 - val_accuracy: 0.8906 - val_loss: 0.2708
Epoch 19/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9102 - loss: 0.2496 - val_accuracy: 0.8906 - val_loss: 0.2727
Epoch 20/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2468 - val_accuracy: 0.9062 - val_loss: 0.2719
Epoch 21/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2441 - val_accuracy: 0.9062 - val_loss: 0.2729
Epoch 22/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2422 - val_accuracy: 0.9062 - val_loss: 0.2725
Epoch 23/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9062 - loss: 0.2428 - val_accuracy: 0.9062 - val_loss: 0.2695
Epoch 24/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2387 - val_accuracy: 0.9062 - val_loss: 0.2742
Epoch 25/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2357 - val_accuracy: 0.9062 - val_loss: 0.2734
Epoch 26/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2339 - val_accuracy: 0.9062 - val_loss: 0.2760
Epoch 27/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9102 - loss: 0.2325 - val_accuracy: 0.9062 - val_loss: 0.2772
Epoch 28/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2299 - val_accuracy: 0.9062 - val_loss: 0.2772
Epoch 29/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2279 - val_accuracy: 0.9062 - val_loss: 0.2753
Epoch 30/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2278 - val_accuracy: 0.9062 - val_loss: 0.2776
Epoch 31/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9219 - loss: 0.2254 - val_accuracy: 0.9062 - val_loss: 0.2753
Epoch 32/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9180 - loss: 0.2241 - val_accuracy: 0.9062 - val_loss: 0.2768
Epoch 33/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9219 - loss: 0.2221 - val_accuracy: 0.9062 - val_loss: 0.2778
Epoch 34/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9219 - loss: 0.2210 - val_accuracy: 0.9062 - val_loss: 0.2754
Epoch 35/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9219 - loss: 0.2199 - val_accuracy: 0.9062 - val_loss: 0.2773
Epoch 36/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9219 - loss: 0.2202 - val_accuracy: 0.9062 - val_loss: 0.2753
Epoch 37/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9258 - loss: 0.2178 - val_accuracy: 0.9062 - val_loss: 0.2801
Epoch 38/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9258 - loss: 0.2167 - val_accuracy: 0.9062 - val_loss: 0.2778
Epoch 39/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9219 - loss: 0.2162 - val_accuracy: 0.9062 - val_loss: 0.2761
Epoch 40/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9258 - loss: 0.2143 - val_accuracy: 0.9062 - val_loss: 0.2790
Epoch 41/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9258 - loss: 0.2136 - val_accuracy: 0.9062 - val_loss: 0.2789
Epoch 42/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2133 - val_accuracy: 0.9062 - val_loss: 0.2780
Epoch 43/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2128 - val_accuracy: 0.9062 - val_loss: 0.2818
Epoch 44/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2132 - val_accuracy: 0.9062 - val_loss: 0.2816
Epoch 45/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2106 - val_accuracy: 0.9062 - val_loss: 0.2813
Epoch 46/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2104 - val_accuracy: 0.9062 - val_loss: 0.2811
Epoch 47/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2103 - val_accuracy: 0.9062 - val_loss: 0.2821
Epoch 48/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9258 - loss: 0.2094 - val_accuracy: 0.9062 - val_loss: 0.2801
Epoch 49/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2092 - val_accuracy: 0.9062 - val_loss: 0.2813
Epoch 50/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2082 - val_accuracy: 0.9062 - val_loss: 0.2798
Epoch 51/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2079 - val_accuracy: 0.9062 - val_loss: 0.2831
Epoch 52/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2071 - val_accuracy: 0.9062 - val_loss: 0.2832
Epoch 53/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.2064 - val_accuracy: 0.9062 - val_loss: 0.2814
Epoch 54/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2057 - val_accuracy: 0.9062 - val_loss: 0.2828
Epoch 55/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2053 - val_accuracy: 0.9062 - val_loss: 0.2836
Epoch 56/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2050 - val_accuracy: 0.9062 - val_loss: 0.2834
Epoch 57/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9258 - loss: 0.2043 - val_accuracy: 0.9062 - val_loss: 0.2830
Epoch 58/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2038 - val_accuracy: 0.9062 - val_loss: 0.2831
Epoch 59/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2044 - val_accuracy: 0.9062 - val_loss: 0.2828
Epoch 60/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.2036 - val_accuracy: 0.9062 - val_loss: 0.2848
Epoch 61/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.2028 - val_accuracy: 0.9062 - val_loss: 0.2852
Epoch 62/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.2016 - val_accuracy: 0.9062 - val_loss: 0.2847
Epoch 63/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2010 - val_accuracy: 0.9062 - val_loss: 0.2843
Epoch 64/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2016 - val_accuracy: 0.9062 - val_loss: 0.2854
Epoch 65/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.2000 - val_accuracy: 0.9062 - val_loss: 0.2852
Epoch 66/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.2001 - val_accuracy: 0.9062 - val_loss: 0.2860
Epoch 67/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.2005 - val_accuracy: 0.9062 - val_loss: 0.2855
Epoch 68/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1989 - val_accuracy: 0.9062 - val_loss: 0.2870
Epoch 69/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1987 - val_accuracy: 0.9062 - val_loss: 0.2905
Epoch 70/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1981 - val_accuracy: 0.9062 - val_loss: 0.2850
Epoch 71/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.1973 - val_accuracy: 0.9062 - val_loss: 0.2865
Epoch 72/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1970 - val_accuracy: 0.9062 - val_loss: 0.2883
Epoch 73/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.1968 - val_accuracy: 0.9062 - val_loss: 0.2897
Epoch 74/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9258 - loss: 0.1966 - val_accuracy: 0.9062 - val_loss: 0.2889
Epoch 75/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1949 - val_accuracy: 0.9062 - val_loss: 0.2879
Epoch 76/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.1954 - val_accuracy: 0.9062 - val_loss: 0.2901
Epoch 77/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.1943 - val_accuracy: 0.9062 - val_loss: 0.2907
Epoch 78/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.1941 - val_accuracy: 0.9062 - val_loss: 0.2870
Epoch 79/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9336 - loss: 0.1953 - val_accuracy: 0.9062 - val_loss: 0.2872
Epoch 80/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9336 - loss: 0.1930 - val_accuracy: 0.9062 - val_loss: 0.2909
Epoch 81/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1931 - val_accuracy: 0.9062 - val_loss: 0.2876
Epoch 82/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.1927 - val_accuracy: 0.9062 - val_loss: 0.2896
Epoch 83/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9297 - loss: 0.1925 - val_accuracy: 0.9062 - val_loss: 0.2893
Epoch 84/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1919 - val_accuracy: 0.9062 - val_loss: 0.2890
Epoch 85/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.1913 - val_accuracy: 0.9062 - val_loss: 0.2921
Epoch 86/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.1906 - val_accuracy: 0.9062 - val_loss: 0.2905
Epoch 87/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1908 - val_accuracy: 0.9062 - val_loss: 0.2889
Epoch 88/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1922 - val_accuracy: 0.9062 - val_loss: 0.2867
Epoch 89/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1892 - val_accuracy: 0.9062 - val_loss: 0.2915
Epoch 90/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.1912 - val_accuracy: 0.9062 - val_loss: 0.2955
Epoch 91/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.1887 - val_accuracy: 0.9062 - val_loss: 0.2905
Epoch 92/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9297 - loss: 0.1885 - val_accuracy: 0.9062 - val_loss: 0.2892
Epoch 93/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1883 - val_accuracy: 0.9062 - val_loss: 0.2906
Epoch 94/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1877 - val_accuracy: 0.9062 - val_loss: 0.2911
Epoch 95/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1872 - val_accuracy: 0.9062 - val_loss: 0.2915
Epoch 96/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1874 - val_accuracy: 0.9062 - val_loss: 0.2938
Epoch 97/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9258 - loss: 0.1884 - val_accuracy: 0.9062 - val_loss: 0.2962
Epoch 98/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1861 - val_accuracy: 0.9062 - val_loss: 0.2922
Epoch 99/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1860 - val_accuracy: 0.9062 - val_loss: 0.2920
Epoch 100/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9375 - loss: 0.1859 - val_accuracy: 0.9062 - val_loss: 0.2911
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9250 - loss: 0.2206
Test Accuracy: 0.925000011920929
Test Loss: 0.22064951062202454

In [ ]:
# Import Libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping


# Build Neural Network
model = Sequential()


# Hidden Layer 1 (32 neurons)
model.add(Dense(
    32,
    activation='relu',
    input_shape=(3,)
))


# Hidden Layer 2 (16 neurons)
model.add(Dense(
    16,
    activation='relu'
))


# Output Layer (1 neuron)
model.add(Dense(
    1,
    activation='sigmoid'
))


# Display Model Structure
model.summary()


# Compile Model
model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


# Early Stopping
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=30,
    restore_best_weights=True
)


# Train Model
history = model.fit(
    X_train,
    y_train,
    epochs=300,
    batch_size=16,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)


# Evaluate Model
loss, accuracy = model.evaluate(
    X_test,
    y_test
)


print("Test Accuracy:", accuracy)
print("Test Loss:", loss)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 32)             │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 673 (2.63 KB)

 Trainable params: 673 (2.63 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.3711 - loss: 0.7020 - val_accuracy: 0.3125 - val_loss: 0.7205
Epoch 2/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3711 - loss: 0.6668 - val_accuracy: 0.3281 - val_loss: 0.6899
Epoch 3/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5039 - loss: 0.6388 - val_accuracy: 0.5938 - val_loss: 0.6666
Epoch 4/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6914 - loss: 0.6160 - val_accuracy: 0.7656 - val_loss: 0.6466
Epoch 5/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7773 - loss: 0.5958 - val_accuracy: 0.8281 - val_loss: 0.6281
Epoch 6/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8359 - loss: 0.5771 - val_accuracy: 0.8594 - val_loss: 0.6117
Epoch 7/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.5591 - val_accuracy: 0.8594 - val_loss: 0.5968
Epoch 8/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8828 - loss: 0.5418 - val_accuracy: 0.8750 - val_loss: 0.5812
Epoch 9/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8867 - loss: 0.5247 - val_accuracy: 0.8750 - val_loss: 0.5659
Epoch 10/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8945 - loss: 0.5075 - val_accuracy: 0.8906 - val_loss: 0.5475
Epoch 11/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8945 - loss: 0.4898 - val_accuracy: 0.8906 - val_loss: 0.5299
Epoch 12/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8945 - loss: 0.4717 - val_accuracy: 0.8906 - val_loss: 0.5142
Epoch 13/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8945 - loss: 0.4546 - val_accuracy: 0.8906 - val_loss: 0.4972
Epoch 14/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8945 - loss: 0.4379 - val_accuracy: 0.8906 - val_loss: 0.4815
Epoch 15/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8906 - loss: 0.4226 - val_accuracy: 0.8906 - val_loss: 0.4637
Epoch 16/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8945 - loss: 0.4073 - val_accuracy: 0.8906 - val_loss: 0.4489
Epoch 17/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8867 - loss: 0.3935 - val_accuracy: 0.8906 - val_loss: 0.4329
Epoch 18/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8867 - loss: 0.3796 - val_accuracy: 0.8906 - val_loss: 0.4213
Epoch 19/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8867 - loss: 0.3669 - val_accuracy: 0.8906 - val_loss: 0.4081
Epoch 20/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8828 - loss: 0.3555 - val_accuracy: 0.8906 - val_loss: 0.3962
Epoch 21/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.3450 - val_accuracy: 0.8906 - val_loss: 0.3848
Epoch 22/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8906 - loss: 0.3343 - val_accuracy: 0.8906 - val_loss: 0.3771
Epoch 23/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.3257 - val_accuracy: 0.8906 - val_loss: 0.3681
Epoch 24/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.3175 - val_accuracy: 0.8906 - val_loss: 0.3607
Epoch 25/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.3109 - val_accuracy: 0.8906 - val_loss: 0.3568
Epoch 26/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3041 - val_accuracy: 0.8906 - val_loss: 0.3495
Epoch 27/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8945 - loss: 0.2983 - val_accuracy: 0.8906 - val_loss: 0.3457
Epoch 28/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2933 - val_accuracy: 0.8906 - val_loss: 0.3419
Epoch 29/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2891 - val_accuracy: 0.8906 - val_loss: 0.3384
Epoch 30/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2849 - val_accuracy: 0.8906 - val_loss: 0.3334
Epoch 31/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2814 - val_accuracy: 0.8906 - val_loss: 0.3298
Epoch 32/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2775 - val_accuracy: 0.8906 - val_loss: 0.3286
Epoch 33/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2747 - val_accuracy: 0.8906 - val_loss: 0.3262
Epoch 34/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2718 - val_accuracy: 0.8906 - val_loss: 0.3225
Epoch 35/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2688 - val_accuracy: 0.8906 - val_loss: 0.3235
Epoch 36/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2662 - val_accuracy: 0.8906 - val_loss: 0.3200
Epoch 37/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2639 - val_accuracy: 0.8906 - val_loss: 0.3196
Epoch 38/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2611 - val_accuracy: 0.8906 - val_loss: 0.3178
Epoch 39/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2594 - val_accuracy: 0.8906 - val_loss: 0.3165
Epoch 40/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2582 - val_accuracy: 0.8906 - val_loss: 0.3167
Epoch 41/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2557 - val_accuracy: 0.8906 - val_loss: 0.3157
Epoch 42/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2541 - val_accuracy: 0.8906 - val_loss: 0.3135
Epoch 43/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9023 - loss: 0.2522 - val_accuracy: 0.8906 - val_loss: 0.3129
Epoch 44/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2512 - val_accuracy: 0.8906 - val_loss: 0.3130
Epoch 45/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2496 - val_accuracy: 0.8906 - val_loss: 0.3132
Epoch 46/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2486 - val_accuracy: 0.8906 - val_loss: 0.3114
Epoch 47/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9102 - loss: 0.2472 - val_accuracy: 0.8906 - val_loss: 0.3138
Epoch 48/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2466 - val_accuracy: 0.8906 - val_loss: 0.3113
Epoch 49/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2452 - val_accuracy: 0.8906 - val_loss: 0.3130
Epoch 50/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9102 - loss: 0.2449 - val_accuracy: 0.8906 - val_loss: 0.3109
Epoch 51/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2436 - val_accuracy: 0.8906 - val_loss: 0.3127
Epoch 52/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2421 - val_accuracy: 0.8906 - val_loss: 0.3111
Epoch 53/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2412 - val_accuracy: 0.8906 - val_loss: 0.3101
Epoch 54/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2410 - val_accuracy: 0.8906 - val_loss: 0.3085
Epoch 55/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2399 - val_accuracy: 0.8906 - val_loss: 0.3108
Epoch 56/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2390 - val_accuracy: 0.8906 - val_loss: 0.3109
Epoch 57/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2391 - val_accuracy: 0.8906 - val_loss: 0.3105
Epoch 58/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2380 - val_accuracy: 0.8906 - val_loss: 0.3108
Epoch 59/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9180 - loss: 0.2370 - val_accuracy: 0.8906 - val_loss: 0.3112
Epoch 60/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2364 - val_accuracy: 0.8906 - val_loss: 0.3106
Epoch 61/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2356 - val_accuracy: 0.8906 - val_loss: 0.3085
Epoch 62/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2347 - val_accuracy: 0.8906 - val_loss: 0.3101
Epoch 63/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2342 - val_accuracy: 0.8906 - val_loss: 0.3094
Epoch 64/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2337 - val_accuracy: 0.8906 - val_loss: 0.3105
Epoch 65/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2337 - val_accuracy: 0.8906 - val_loss: 0.3093
Epoch 66/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2326 - val_accuracy: 0.8906 - val_loss: 0.3088
Epoch 67/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9180 - loss: 0.2325 - val_accuracy: 0.8906 - val_loss: 0.3111
Epoch 68/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2315 - val_accuracy: 0.8906 - val_loss: 0.3100
Epoch 69/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2315 - val_accuracy: 0.8906 - val_loss: 0.3090
Epoch 70/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2304 - val_accuracy: 0.8906 - val_loss: 0.3096
Epoch 71/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2312 - val_accuracy: 0.9062 - val_loss: 0.3134
Epoch 72/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2309 - val_accuracy: 0.8906 - val_loss: 0.3079
Epoch 73/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2307 - val_accuracy: 0.8906 - val_loss: 0.3115
Epoch 74/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2312 - val_accuracy: 0.8906 - val_loss: 0.3072
Epoch 75/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2284 - val_accuracy: 0.8906 - val_loss: 0.3093
Epoch 76/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9180 - loss: 0.2281 - val_accuracy: 0.8906 - val_loss: 0.3102
Epoch 77/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2277 - val_accuracy: 0.8906 - val_loss: 0.3099
Epoch 78/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2269 - val_accuracy: 0.9062 - val_loss: 0.3118
Epoch 79/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2269 - val_accuracy: 0.9062 - val_loss: 0.3119
Epoch 80/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2277 - val_accuracy: 0.8906 - val_loss: 0.3098
Epoch 81/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2266 - val_accuracy: 0.9062 - val_loss: 0.3117
Epoch 82/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2254 - val_accuracy: 0.9062 - val_loss: 0.3111
Epoch 83/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9141 - loss: 0.2255 - val_accuracy: 0.9062 - val_loss: 0.3091
Epoch 84/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9141 - loss: 0.2256 - val_accuracy: 0.9062 - val_loss: 0.3093
Epoch 85/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2242 - val_accuracy: 0.9062 - val_loss: 0.3129
Epoch 86/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2244 - val_accuracy: 0.9062 - val_loss: 0.3116
Epoch 87/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2243 - val_accuracy: 0.9062 - val_loss: 0.3158
Epoch 88/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2232 - val_accuracy: 0.9062 - val_loss: 0.3147
Epoch 89/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2230 - val_accuracy: 0.9062 - val_loss: 0.3109
Epoch 90/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2235 - val_accuracy: 0.9062 - val_loss: 0.3119
Epoch 91/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2227 - val_accuracy: 0.9062 - val_loss: 0.3108
Epoch 92/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2218 - val_accuracy: 0.9062 - val_loss: 0.3102
Epoch 93/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2226 - val_accuracy: 0.8906 - val_loss: 0.3070
Epoch 94/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2222 - val_accuracy: 0.9062 - val_loss: 0.3111
Epoch 95/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2217 - val_accuracy: 0.9062 - val_loss: 0.3114
Epoch 96/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2210 - val_accuracy: 0.9062 - val_loss: 0.3120
Epoch 97/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2205 - val_accuracy: 0.9062 - val_loss: 0.3132
Epoch 98/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2210 - val_accuracy: 0.9062 - val_loss: 0.3107
Epoch 99/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9180 - loss: 0.2204 - val_accuracy: 0.9062 - val_loss: 0.3103
Epoch 100/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9141 - loss: 0.2205 - val_accuracy: 0.9062 - val_loss: 0.3125
Epoch 101/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9141 - loss: 0.2198 - val_accuracy: 0.9062 - val_loss: 0.3122
Epoch 102/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9141 - loss: 0.2195 - val_accuracy: 0.9062 - val_loss: 0.3145
Epoch 103/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9141 - loss: 0.2192 - val_accuracy: 0.9062 - val_loss: 0.3125
Epoch 104/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9180 - loss: 0.2192 - val_accuracy: 0.9062 - val_loss: 0.3103
Epoch 105/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9180 - loss: 0.2190 - val_accuracy: 0.9062 - val_loss: 0.3120
Epoch 106/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9180 - loss: 0.2185 - val_accuracy: 0.9062 - val_loss: 0.3113
Epoch 107/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9141 - loss: 0.2187 - val_accuracy: 0.9062 - val_loss: 0.3122
Epoch 108/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9180 - loss: 0.2185 - val_accuracy: 0.9062 - val_loss: 0.3120
Epoch 109/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9219 - loss: 0.2177 - val_accuracy: 0.9062 - val_loss: 0.3124
Epoch 110/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9180 - loss: 0.2182 - val_accuracy: 0.9062 - val_loss: 0.3111
Epoch 111/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9180 - loss: 0.2172 - val_accuracy: 0.9062 - val_loss: 0.3114
Epoch 112/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2180 - val_accuracy: 0.9062 - val_loss: 0.3150
Epoch 113/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2170 - val_accuracy: 0.9062 - val_loss: 0.3142
Epoch 114/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2164 - val_accuracy: 0.9062 - val_loss: 0.3129
Epoch 115/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9180 - loss: 0.2163 - val_accuracy: 0.9062 - val_loss: 0.3116
Epoch 116/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2166 - val_accuracy: 0.9062 - val_loss: 0.3132
Epoch 117/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9180 - loss: 0.2167 - val_accuracy: 0.9062 - val_loss: 0.3138
Epoch 118/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2159 - val_accuracy: 0.9062 - val_loss: 0.3130
Epoch 119/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2159 - val_accuracy: 0.9062 - val_loss: 0.3106
Epoch 120/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2151 - val_accuracy: 0.9062 - val_loss: 0.3114
Epoch 121/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2155 - val_accuracy: 0.9062 - val_loss: 0.3134
Epoch 122/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2148 - val_accuracy: 0.9062 - val_loss: 0.3126
Epoch 123/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2153 - val_accuracy: 0.9062 - val_loss: 0.3103
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9125 - loss: 0.2111
Test Accuracy: 0.9125000238418579
Test Loss: 0.21113333106040955

In [ ]:
# Import Libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

# ----------------------------------------
# Convert labels from (0,1) to (-1,1)
# ----------------------------------------
y_train_tanh = y_train.replace({0: -1, 1: 1})
y_test_tanh = y_test.replace({0: -1, 1: 1})

# ----------------------------------------
# Build Neural Network
# ----------------------------------------
model = Sequential()

# Hidden Layer 1
model.add(Dense(
    32,
    activation='tanh',
    input_shape=(3,)
))

# Hidden Layer 2
model.add(Dense(
    16,
    activation='tanh'
))

# Output Layer
model.add(Dense(
    1,
    activation='tanh'
))

# Display Model Structure
model.summary()

# ----------------------------------------
# Compile Model
# ----------------------------------------
model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='mean_squared_error',
    metrics=['accuracy']
)

# ----------------------------------------
# Early Stopping
# ----------------------------------------
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=30,
    restore_best_weights=True
)

# ----------------------------------------
# Train Model
# ----------------------------------------
history = model.fit(
    X_train,
    y_train_tanh,
    epochs=300,
    batch_size=16,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)

# ----------------------------------------
# Evaluate Model
# ----------------------------------------
loss, accuracy = model.evaluate(
    X_test,
    y_test_tanh
)

print("Test Accuracy:", accuracy)
print("Test Loss:", loss)

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_18 (Dense)                │ (None, 32)             │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 673 (2.63 KB)

 Trainable params: 673 (2.63 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.0000e+00 - loss: 1.1805 - val_accuracy: 0.0000e+00 - val_loss: 1.0491
Epoch 2/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0000e+00 - loss: 0.9340 - val_accuracy: 0.0000e+00 - val_loss: 0.8500
Epoch 3/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0000e+00 - loss: 0.7689 - val_accuracy: 0.0000e+00 - val_loss: 0.7034
Epoch 4/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.0273 - loss: 0.6577 - val_accuracy: 0.0156 - val_loss: 0.6182
Epoch 5/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.0625 - loss: 0.5933 - val_accuracy: 0.0469 - val_loss: 0.5639
Epoch 6/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0820 - loss: 0.5550 - val_accuracy: 0.0469 - val_loss: 0.5302
Epoch 7/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.1016 - loss: 0.5276 - val_accuracy: 0.0625 - val_loss: 0.5104
Epoch 8/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1055 - loss: 0.5125 - val_accuracy: 0.0625 - val_loss: 0.4950
Epoch 9/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1328 - loss: 0.5014 - val_accuracy: 0.0781 - val_loss: 0.4835
Epoch 10/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1406 - loss: 0.4926 - val_accuracy: 0.0938 - val_loss: 0.4753
Epoch 11/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1523 - loss: 0.4857 - val_accuracy: 0.0938 - val_loss: 0.4675
Epoch 12/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1562 - loss: 0.4823 - val_accuracy: 0.0938 - val_loss: 0.4608
Epoch 13/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1641 - loss: 0.4788 - val_accuracy: 0.1094 - val_loss: 0.4578
Epoch 14/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1719 - loss: 0.4767 - val_accuracy: 0.0938 - val_loss: 0.4526
Epoch 15/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1758 - loss: 0.4738 - val_accuracy: 0.1094 - val_loss: 0.4503
Epoch 16/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1836 - loss: 0.4706 - val_accuracy: 0.1094 - val_loss: 0.4462
Epoch 17/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1875 - loss: 0.4695 - val_accuracy: 0.1094 - val_loss: 0.4429
Epoch 18/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1875 - loss: 0.4673 - val_accuracy: 0.1250 - val_loss: 0.4424
Epoch 19/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1914 - loss: 0.4680 - val_accuracy: 0.1250 - val_loss: 0.4410
Epoch 20/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1914 - loss: 0.4657 - val_accuracy: 0.1250 - val_loss: 0.4382
Epoch 21/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1992 - loss: 0.4660 - val_accuracy: 0.1250 - val_loss: 0.4371
Epoch 22/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2031 - loss: 0.4629 - val_accuracy: 0.1250 - val_loss: 0.4361
Epoch 23/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1992 - loss: 0.4629 - val_accuracy: 0.1250 - val_loss: 0.4348
Epoch 24/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2031 - loss: 0.4625 - val_accuracy: 0.1250 - val_loss: 0.4351
Epoch 25/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2031 - loss: 0.4613 - val_accuracy: 0.1250 - val_loss: 0.4323
Epoch 26/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2031 - loss: 0.4605 - val_accuracy: 0.1250 - val_loss: 0.4301
Epoch 27/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2070 - loss: 0.4599 - val_accuracy: 0.1250 - val_loss: 0.4314
Epoch 28/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2031 - loss: 0.4588 - val_accuracy: 0.1250 - val_loss: 0.4298
Epoch 29/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2031 - loss: 0.4578 - val_accuracy: 0.1250 - val_loss: 0.4283
Epoch 30/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2070 - loss: 0.4582 - val_accuracy: 0.1250 - val_loss: 0.4281
Epoch 31/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2070 - loss: 0.4578 - val_accuracy: 0.1250 - val_loss: 0.4273
Epoch 32/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2031 - loss: 0.4578 - val_accuracy: 0.1250 - val_loss: 0.4258
Epoch 33/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2031 - loss: 0.4555 - val_accuracy: 0.1250 - val_loss: 0.4253
Epoch 34/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2070 - loss: 0.4559 - val_accuracy: 0.1250 - val_loss: 0.4249
Epoch 35/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2070 - loss: 0.4550 - val_accuracy: 0.1250 - val_loss: 0.4242
Epoch 36/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2031 - loss: 0.4563 - val_accuracy: 0.1250 - val_loss: 0.4222
Epoch 37/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2070 - loss: 0.4530 - val_accuracy: 0.1250 - val_loss: 0.4232
Epoch 38/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2070 - loss: 0.4524 - val_accuracy: 0.1250 - val_loss: 0.4228
Epoch 39/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2070 - loss: 0.4519 - val_accuracy: 0.1250 - val_loss: 0.4229
Epoch 40/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2070 - loss: 0.4517 - val_accuracy: 0.1250 - val_loss: 0.4217
Epoch 41/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2070 - loss: 0.4503 - val_accuracy: 0.1250 - val_loss: 0.4202
Epoch 42/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2070 - loss: 0.4497 - val_accuracy: 0.1250 - val_loss: 0.4215
Epoch 43/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2070 - loss: 0.4486 - val_accuracy: 0.1250 - val_loss: 0.4193
Epoch 44/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2070 - loss: 0.4488 - val_accuracy: 0.1250 - val_loss: 0.4191
Epoch 45/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2070 - loss: 0.4478 - val_accuracy: 0.1250 - val_loss: 0.4179
Epoch 46/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2070 - loss: 0.4463 - val_accuracy: 0.1250 - val_loss: 0.4170
Epoch 47/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2070 - loss: 0.4462 - val_accuracy: 0.1250 - val_loss: 0.4156
Epoch 48/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2070 - loss: 0.4441 - val_accuracy: 0.1250 - val_loss: 0.4175
Epoch 49/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2070 - loss: 0.4432 - val_accuracy: 0.1250 - val_loss: 0.4151
Epoch 50/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2070 - loss: 0.4417 - val_accuracy: 0.1250 - val_loss: 0.4142
Epoch 51/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2070 - loss: 0.4401 - val_accuracy: 0.1250 - val_loss: 0.4127
Epoch 52/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2070 - loss: 0.4400 - val_accuracy: 0.1250 - val_loss: 0.4118
Epoch 53/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2070 - loss: 0.4414 - val_accuracy: 0.1250 - val_loss: 0.4099
Epoch 54/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.4353 - val_accuracy: 0.1250 - val_loss: 0.4120
Epoch 55/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2109 - loss: 0.4340 - val_accuracy: 0.1406 - val_loss: 0.4124
Epoch 56/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2070 - loss: 0.4333 - val_accuracy: 0.1250 - val_loss: 0.4088
Epoch 57/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.4326 - val_accuracy: 0.1250 - val_loss: 0.4082
Epoch 58/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2109 - loss: 0.4296 - val_accuracy: 0.1250 - val_loss: 0.4071
Epoch 59/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.4290 - val_accuracy: 0.1250 - val_loss: 0.4049
Epoch 60/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2109 - loss: 0.4280 - val_accuracy: 0.1406 - val_loss: 0.4054
Epoch 61/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.4238 - val_accuracy: 0.1250 - val_loss: 0.4024
Epoch 62/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2109 - loss: 0.4218 - val_accuracy: 0.1250 - val_loss: 0.4015
Epoch 63/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2070 - loss: 0.4210 - val_accuracy: 0.1250 - val_loss: 0.4007
Epoch 64/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.4175 - val_accuracy: 0.1250 - val_loss: 0.3984
Epoch 65/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2070 - loss: 0.4177 - val_accuracy: 0.1406 - val_loss: 0.3994
Epoch 66/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.4126 - val_accuracy: 0.1406 - val_loss: 0.3963
Epoch 67/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2148 - loss: 0.4107 - val_accuracy: 0.1250 - val_loss: 0.3939
Epoch 68/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2148 - loss: 0.4086 - val_accuracy: 0.1406 - val_loss: 0.3941
Epoch 69/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.4059 - val_accuracy: 0.1406 - val_loss: 0.3924
Epoch 70/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2148 - loss: 0.4060 - val_accuracy: 0.1250 - val_loss: 0.3924
Epoch 71/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2148 - loss: 0.4008 - val_accuracy: 0.1250 - val_loss: 0.3886
Epoch 72/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2148 - loss: 0.3990 - val_accuracy: 0.1250 - val_loss: 0.3873
Epoch 73/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.3969 - val_accuracy: 0.1250 - val_loss: 0.3863
Epoch 74/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.3929 - val_accuracy: 0.1250 - val_loss: 0.3844
Epoch 75/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.3903 - val_accuracy: 0.1250 - val_loss: 0.3822
Epoch 76/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2109 - loss: 0.3881 - val_accuracy: 0.1250 - val_loss: 0.3816
Epoch 77/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2070 - loss: 0.3883 - val_accuracy: 0.1250 - val_loss: 0.3802
Epoch 78/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.3829 - val_accuracy: 0.1250 - val_loss: 0.3779
Epoch 79/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.3801 - val_accuracy: 0.1250 - val_loss: 0.3759
Epoch 80/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2148 - loss: 0.3772 - val_accuracy: 0.1250 - val_loss: 0.3755
Epoch 81/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.3756 - val_accuracy: 0.1562 - val_loss: 0.3758
Epoch 82/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.3734 - val_accuracy: 0.1406 - val_loss: 0.3718
Epoch 83/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2227 - loss: 0.3708 - val_accuracy: 0.1562 - val_loss: 0.3714
Epoch 84/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2148 - loss: 0.3669 - val_accuracy: 0.1562 - val_loss: 0.3697
Epoch 85/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2148 - loss: 0.3641 - val_accuracy: 0.1562 - val_loss: 0.3693
Epoch 86/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2148 - loss: 0.3617 - val_accuracy: 0.1562 - val_loss: 0.3671
Epoch 87/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2148 - loss: 0.3584 - val_accuracy: 0.1562 - val_loss: 0.3657
Epoch 88/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2148 - loss: 0.3568 - val_accuracy: 0.1562 - val_loss: 0.3633
Epoch 89/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2188 - loss: 0.3536 - val_accuracy: 0.1562 - val_loss: 0.3631
Epoch 90/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2188 - loss: 0.3514 - val_accuracy: 0.1562 - val_loss: 0.3622
Epoch 91/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2227 - loss: 0.3487 - val_accuracy: 0.1562 - val_loss: 0.3613
Epoch 92/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2148 - loss: 0.3479 - val_accuracy: 0.1562 - val_loss: 0.3590
Epoch 93/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2109 - loss: 0.3456 - val_accuracy: 0.1562 - val_loss: 0.3592
Epoch 94/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2109 - loss: 0.3418 - val_accuracy: 0.1562 - val_loss: 0.3580
Epoch 95/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2188 - loss: 0.3398 - val_accuracy: 0.1719 - val_loss: 0.3574
Epoch 96/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2148 - loss: 0.3399 - val_accuracy: 0.1719 - val_loss: 0.3553
Epoch 97/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2188 - loss: 0.3370 - val_accuracy: 0.1719 - val_loss: 0.3547
Epoch 98/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2148 - loss: 0.3349 - val_accuracy: 0.1875 - val_loss: 0.3534
Epoch 99/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2227 - loss: 0.3315 - val_accuracy: 0.1875 - val_loss: 0.3528
Epoch 100/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2227 - loss: 0.3302 - val_accuracy: 0.1875 - val_loss: 0.3525
Epoch 101/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2266 - loss: 0.3270 - val_accuracy: 0.1875 - val_loss: 0.3511
Epoch 102/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2188 - loss: 0.3262 - val_accuracy: 0.1875 - val_loss: 0.3491
Epoch 103/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2305 - loss: 0.3248 - val_accuracy: 0.1875 - val_loss: 0.3490
Epoch 104/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2227 - loss: 0.3219 - val_accuracy: 0.1875 - val_loss: 0.3485
Epoch 105/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2266 - loss: 0.3198 - val_accuracy: 0.1875 - val_loss: 0.3484
Epoch 106/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2305 - loss: 0.3193 - val_accuracy: 0.2031 - val_loss: 0.3495
Epoch 107/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2305 - loss: 0.3162 - val_accuracy: 0.1875 - val_loss: 0.3475
Epoch 108/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2305 - loss: 0.3153 - val_accuracy: 0.2031 - val_loss: 0.3467
Epoch 109/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2266 - loss: 0.3159 - val_accuracy: 0.2031 - val_loss: 0.3456
Epoch 110/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2422 - loss: 0.3123 - val_accuracy: 0.2031 - val_loss: 0.3452
Epoch 111/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2422 - loss: 0.3114 - val_accuracy: 0.2188 - val_loss: 0.3457
Epoch 112/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2383 - loss: 0.3090 - val_accuracy: 0.2188 - val_loss: 0.3445
Epoch 113/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2383 - loss: 0.3080 - val_accuracy: 0.2188 - val_loss: 0.3445
Epoch 114/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2461 - loss: 0.3067 - val_accuracy: 0.2188 - val_loss: 0.3419
Epoch 115/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2461 - loss: 0.3069 - val_accuracy: 0.2188 - val_loss: 0.3435
Epoch 116/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2539 - loss: 0.3031 - val_accuracy: 0.2188 - val_loss: 0.3427
Epoch 117/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2539 - loss: 0.3026 - val_accuracy: 0.2188 - val_loss: 0.3421
Epoch 118/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2578 - loss: 0.3021 - val_accuracy: 0.2188 - val_loss: 0.3412
Epoch 119/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2539 - loss: 0.3003 - val_accuracy: 0.2188 - val_loss: 0.3410
Epoch 120/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2539 - loss: 0.2994 - val_accuracy: 0.2188 - val_loss: 0.3407
Epoch 121/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2578 - loss: 0.2976 - val_accuracy: 0.2188 - val_loss: 0.3408
Epoch 122/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2500 - loss: 0.2970 - val_accuracy: 0.2188 - val_loss: 0.3400
Epoch 123/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2539 - loss: 0.2959 - val_accuracy: 0.2188 - val_loss: 0.3399
Epoch 124/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2578 - loss: 0.2951 - val_accuracy: 0.2188 - val_loss: 0.3395
Epoch 125/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2578 - loss: 0.2944 - val_accuracy: 0.2188 - val_loss: 0.3396
Epoch 126/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2617 - loss: 0.2934 - val_accuracy: 0.2188 - val_loss: 0.3382
Epoch 127/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2617 - loss: 0.2927 - val_accuracy: 0.2188 - val_loss: 0.3398
Epoch 128/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2617 - loss: 0.2930 - val_accuracy: 0.2188 - val_loss: 0.3384
Epoch 129/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2617 - loss: 0.2915 - val_accuracy: 0.2188 - val_loss: 0.3374
Epoch 130/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2617 - loss: 0.2900 - val_accuracy: 0.2188 - val_loss: 0.3391
Epoch 131/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2578 - loss: 0.2880 - val_accuracy: 0.2188 - val_loss: 0.3384
Epoch 132/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2617 - loss: 0.2874 - val_accuracy: 0.2188 - val_loss: 0.3379
Epoch 133/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2656 - loss: 0.2877 - val_accuracy: 0.2188 - val_loss: 0.3387
Epoch 134/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2656 - loss: 0.2855 - val_accuracy: 0.2188 - val_loss: 0.3366
Epoch 135/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.2656 - loss: 0.2864 - val_accuracy: 0.2188 - val_loss: 0.3367
Epoch 136/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2695 - loss: 0.2856 - val_accuracy: 0.2188 - val_loss: 0.3374
Epoch 137/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2695 - loss: 0.2842 - val_accuracy: 0.2188 - val_loss: 0.3367
Epoch 138/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2695 - loss: 0.2833 - val_accuracy: 0.2188 - val_loss: 0.3350
Epoch 139/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2695 - loss: 0.2837 - val_accuracy: 0.2188 - val_loss: 0.3371
Epoch 140/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2617 - loss: 0.2824 - val_accuracy: 0.2188 - val_loss: 0.3368
Epoch 141/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2617 - loss: 0.2836 - val_accuracy: 0.2188 - val_loss: 0.3354
Epoch 142/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2656 - loss: 0.2812 - val_accuracy: 0.2188 - val_loss: 0.3371
Epoch 143/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2656 - loss: 0.2805 - val_accuracy: 0.2188 - val_loss: 0.3355
Epoch 144/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2695 - loss: 0.2795 - val_accuracy: 0.2188 - val_loss: 0.3357
Epoch 145/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2656 - loss: 0.2795 - val_accuracy: 0.2188 - val_loss: 0.3353
Epoch 146/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2695 - loss: 0.2784 - val_accuracy: 0.2188 - val_loss: 0.3358
Epoch 147/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2695 - loss: 0.2786 - val_accuracy: 0.2188 - val_loss: 0.3350
Epoch 148/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2656 - loss: 0.2781 - val_accuracy: 0.2188 - val_loss: 0.3349
Epoch 149/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2695 - loss: 0.2768 - val_accuracy: 0.2188 - val_loss: 0.3357
Epoch 150/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2734 - loss: 0.2772 - val_accuracy: 0.2188 - val_loss: 0.3351
Epoch 151/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2695 - loss: 0.2762 - val_accuracy: 0.2188 - val_loss: 0.3358
Epoch 152/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2695 - loss: 0.2754 - val_accuracy: 0.2188 - val_loss: 0.3350
Epoch 153/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2656 - loss: 0.2755 - val_accuracy: 0.2188 - val_loss: 0.3346
Epoch 154/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2695 - loss: 0.2747 - val_accuracy: 0.2188 - val_loss: 0.3348
Epoch 155/300
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2695 - loss: 0.2741 - val_accuracy: 0.2188 - val_loss: 0.3347
Epoch 156/300

In [ ]:
predictions = model.predict(X_test)

# Convert predictions to classes
y_pred = (predictions >= 0).astype(int)

# Convert true labels back to 0/1
y_true = (y_test_tanh == 1).astype(int)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step

In [ ]:
# Import Libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping


# Build Neural Network
model = Sequential()

# Hidden Layer 1
model.add(Dense(
    32,
    activation='relu',
    input_shape=(3,)
))

# Hidden Layer 2
model.add(Dense(
    16,
    activation='relu'
))

# Output Layer (tanh)
model.add(Dense(
    1,
    activation='tanh'
))


# Display Model Structure
model.summary()


# Compile Model
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


# Early Stopping
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=30,
    restore_best_weights=True
)


# Train Model
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)


# Evaluate Model
loss, accuracy = model.evaluate(
    X_test,
    y_test
)

print("Test Accuracy:", accuracy)
print("Test Loss:", loss)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_21 (Dense)                │ (None, 32)             │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 673 (2.63 KB)

 Trainable params: 673 (2.63 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - accuracy: 0.6289 - loss: 4.5614 - val_accuracy: 0.6875 - val_loss: 3.6860
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6562 - loss: 3.8929 - val_accuracy: 0.7188 - val_loss: 2.9813
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6875 - loss: 3.2181 - val_accuracy: 0.7656 - val_loss: 2.1271
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7266 - loss: 2.4129 - val_accuracy: 0.7656 - val_loss: 1.4070
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7656 - loss: 1.1464 - val_accuracy: 0.7969 - val_loss: 0.4295
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7930 - loss: 0.5606 - val_accuracy: 0.8438 - val_loss: 0.3452
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8242 - loss: 0.4410 - val_accuracy: 0.8438 - val_loss: 0.3260
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.4156 - val_accuracy: 0.8750 - val_loss: 0.3168
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8242 - loss: 0.4015 - val_accuracy: 0.8750 - val_loss: 0.3096
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8438 - loss: 0.3902 - val_accuracy: 0.8750 - val_loss: 0.3031
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3806 - val_accuracy: 0.8906 - val_loss: 0.2990
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8555 - loss: 0.3703 - val_accuracy: 0.8906 - val_loss: 0.2934
Epoch 13/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8711 - loss: 0.3602 - val_accuracy: 0.8906 - val_loss: 0.2891
Epoch 14/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.3520 - val_accuracy: 0.8906 - val_loss: 0.2850
Epoch 15/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.3459 - val_accuracy: 0.8906 - val_loss: 0.2802
Epoch 16/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3401 - val_accuracy: 0.9062 - val_loss: 0.2793
Epoch 17/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3326 - val_accuracy: 0.8906 - val_loss: 0.2797
Epoch 18/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3280 - val_accuracy: 0.8906 - val_loss: 0.2752
Epoch 19/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3235 - val_accuracy: 0.8906 - val_loss: 0.2879
Epoch 20/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.3161 - val_accuracy: 0.8906 - val_loss: 0.2825
Epoch 21/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.3119 - val_accuracy: 0.9062 - val_loss: 0.2791
Epoch 22/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.3079 - val_accuracy: 0.8906 - val_loss: 0.2846
Epoch 23/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.3031 - val_accuracy: 0.9062 - val_loss: 0.2950
Epoch 24/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.3002 - val_accuracy: 0.9062 - val_loss: 0.4688
Epoch 25/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9102 - loss: 0.2964 - val_accuracy: 0.9062 - val_loss: 0.4675
Epoch 26/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2945 - val_accuracy: 0.9219 - val_loss: 0.4685
Epoch 27/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2911 - val_accuracy: 0.9062 - val_loss: 0.4670
Epoch 28/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2898 - val_accuracy: 0.9062 - val_loss: 0.4680
Epoch 29/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2862 - val_accuracy: 0.9062 - val_loss: 0.4676
Epoch 30/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2849 - val_accuracy: 0.9062 - val_loss: 0.4671
Epoch 31/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2835 - val_accuracy: 0.9062 - val_loss: 0.4651
Epoch 32/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2825 - val_accuracy: 0.9062 - val_loss: 0.4708
Epoch 33/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2333 - val_accuracy: 0.9062 - val_loss: 0.2726
Epoch 34/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9062 - loss: 0.2250 - val_accuracy: 0.9062 - val_loss: 0.2764
Epoch 35/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9102 - loss: 0.2215 - val_accuracy: 0.9062 - val_loss: 0.2734
Epoch 36/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9219 - loss: 0.2190 - val_accuracy: 0.9062 - val_loss: 0.2771
Epoch 37/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9219 - loss: 0.2165 - val_accuracy: 0.9062 - val_loss: 0.3044
Epoch 38/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9102 - loss: 0.2156 - val_accuracy: 0.9062 - val_loss: 0.2838
Epoch 39/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9062 - loss: 0.2133 - val_accuracy: 0.9062 - val_loss: 0.2863
Epoch 40/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9141 - loss: 0.2118 - val_accuracy: 0.9062 - val_loss: 0.2893
Epoch 41/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9141 - loss: 0.2117 - val_accuracy: 0.9062 - val_loss: 0.2875
Epoch 42/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9102 - loss: 0.2110 - val_accuracy: 0.9062 - val_loss: 0.2866
Epoch 43/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9102 - loss: 0.2100 - val_accuracy: 0.9062 - val_loss: 0.2929
Epoch 44/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9219 - loss: 0.2104 - val_accuracy: 0.9062 - val_loss: 0.2844
Epoch 45/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9219 - loss: 0.2080 - val_accuracy: 0.9062 - val_loss: 0.2857
Epoch 46/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9180 - loss: 0.2075 - val_accuracy: 0.9062 - val_loss: 0.2867
Epoch 47/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2072 - val_accuracy: 0.9062 - val_loss: 0.2898
Epoch 48/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2078 - val_accuracy: 0.9062 - val_loss: 0.2884
Epoch 49/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9219 - loss: 0.2056 - val_accuracy: 0.9062 - val_loss: 0.2947
Epoch 50/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9141 - loss: 0.2049 - val_accuracy: 0.9062 - val_loss: 0.3123
Epoch 51/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2042 - val_accuracy: 0.9062 - val_loss: 0.3340
Epoch 52/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2034 - val_accuracy: 0.9062 - val_loss: 0.2987
Epoch 53/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2041 - val_accuracy: 0.9062 - val_loss: 0.3174
Epoch 54/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9141 - loss: 0.2022 - val_accuracy: 0.9062 - val_loss: 0.3072
Epoch 55/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.2019 - val_accuracy: 0.9062 - val_loss: 0.3278
Epoch 56/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2011 - val_accuracy: 0.9062 - val_loss: 0.3367
Epoch 57/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2010 - val_accuracy: 0.9062 - val_loss: 0.3630
Epoch 58/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9141 - loss: 0.2008 - val_accuracy: 0.9062 - val_loss: 0.3227
Epoch 59/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.2015 - val_accuracy: 0.9062 - val_loss: 0.3213
Epoch 60/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.1998 - val_accuracy: 0.9062 - val_loss: 0.4947
Epoch 61/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.1988 - val_accuracy: 0.9062 - val_loss: 0.4945
Epoch 62/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9141 - loss: 0.1994 - val_accuracy: 0.9062 - val_loss: 0.4939
Epoch 63/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9180 - loss: 0.1992 - val_accuracy: 0.9062 - val_loss: 0.5001
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9125 - loss: 0.2012
Test Accuracy: 0.9125000238418579
Test Loss: 0.2012288123369217

In [ ]:
# Import Libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping


# Build Neural Network
model = Sequential()

# Hidden Layer 1 (Softplus)
model.add(Dense(
    32,
    activation='softplus',
    input_shape=(3,)
))

# Hidden Layer 2 (Softplus)
model.add(Dense(
    16,
    activation='softplus'
))

# Output Layer (Sigmoid)
model.add(Dense(
    1,
    activation='sigmoid'
))


# Display Model Structure
model.summary()


# Compile Model
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


# Early Stopping
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=30,
    restore_best_weights=True
)


# Train Model
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)


# Evaluate Model
loss, accuracy = model.evaluate(
    X_test,
    y_test
)

print("Test Accuracy:", accuracy)
print("Test Loss:", loss)

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_24 (Dense)                │ (None, 32)             │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_26 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 673 (2.63 KB)

 Trainable params: 673 (2.63 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - accuracy: 0.6289 - loss: 0.7307 - val_accuracy: 0.6875 - val_loss: 0.6496
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6289 - loss: 0.6739 - val_accuracy: 0.6875 - val_loss: 0.6348
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6289 - loss: 0.6434 - val_accuracy: 0.6875 - val_loss: 0.6119
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6289 - loss: 0.6107 - val_accuracy: 0.6875 - val_loss: 0.5814
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6523 - loss: 0.5828 - val_accuracy: 0.7188 - val_loss: 0.5580
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7031 - loss: 0.5535 - val_accuracy: 0.7031 - val_loss: 0.5360
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7852 - loss: 0.5274 - val_accuracy: 0.7500 - val_loss: 0.5129
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7930 - loss: 0.4960 - val_accuracy: 0.7500 - val_loss: 0.4876
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7969 - loss: 0.4768 - val_accuracy: 0.7500 - val_loss: 0.4663
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8164 - loss: 0.4487 - val_accuracy: 0.8125 - val_loss: 0.4521
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8086 - loss: 0.4334 - val_accuracy: 0.7969 - val_loss: 0.4340
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8125 - loss: 0.4165 - val_accuracy: 0.8125 - val_loss: 0.4223
Epoch 13/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8125 - loss: 0.4049 - val_accuracy: 0.8281 - val_loss: 0.4121
Epoch 14/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8164 - loss: 0.3957 - val_accuracy: 0.8438 - val_loss: 0.4044
Epoch 15/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8242 - loss: 0.3885 - val_accuracy: 0.8281 - val_loss: 0.3966
Epoch 16/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8164 - loss: 0.3876 - val_accuracy: 0.8281 - val_loss: 0.3921
Epoch 17/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8203 - loss: 0.3807 - val_accuracy: 0.8594 - val_loss: 0.3906
Epoch 18/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.3750 - val_accuracy: 0.8281 - val_loss: 0.3837
Epoch 19/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8203 - loss: 0.3729 - val_accuracy: 0.8281 - val_loss: 0.3805
Epoch 20/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.3702 - val_accuracy: 0.8438 - val_loss: 0.3776
Epoch 21/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.3699 - val_accuracy: 0.8281 - val_loss: 0.3758
Epoch 22/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8203 - loss: 0.3674 - val_accuracy: 0.8438 - val_loss: 0.3743
Epoch 23/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8320 - loss: 0.3668 - val_accuracy: 0.8594 - val_loss: 0.3737
Epoch 24/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3656 - val_accuracy: 0.8438 - val_loss: 0.3714
Epoch 25/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8242 - loss: 0.3637 - val_accuracy: 0.8438 - val_loss: 0.3696
Epoch 26/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8242 - loss: 0.3631 - val_accuracy: 0.8438 - val_loss: 0.3683
Epoch 27/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8320 - loss: 0.3637 - val_accuracy: 0.8281 - val_loss: 0.3681
Epoch 28/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8242 - loss: 0.3635 - val_accuracy: 0.8281 - val_loss: 0.3663
Epoch 29/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8438 - loss: 0.3621 - val_accuracy: 0.8906 - val_loss: 0.3667
Epoch 30/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3611 - val_accuracy: 0.8438 - val_loss: 0.3643
Epoch 31/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.3603 - val_accuracy: 0.8281 - val_loss: 0.3637
Epoch 32/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3615 - val_accuracy: 0.8750 - val_loss: 0.3638
Epoch 33/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8320 - loss: 0.3589 - val_accuracy: 0.8281 - val_loss: 0.3625
Epoch 34/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3630 - val_accuracy: 0.8906 - val_loss: 0.3630
Epoch 35/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8242 - loss: 0.3601 - val_accuracy: 0.8281 - val_loss: 0.3617
Epoch 36/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3565 - val_accuracy: 0.8750 - val_loss: 0.3610
Epoch 37/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3561 - val_accuracy: 0.8750 - val_loss: 0.3602
Epoch 38/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8438 - loss: 0.3557 - val_accuracy: 0.8438 - val_loss: 0.3581
Epoch 39/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3549 - val_accuracy: 0.8438 - val_loss: 0.3578
Epoch 40/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.3569 - val_accuracy: 0.8281 - val_loss: 0.3569
Epoch 41/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3532 - val_accuracy: 0.8750 - val_loss: 0.3596
Epoch 42/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8242 - loss: 0.3556 - val_accuracy: 0.8281 - val_loss: 0.3555
Epoch 43/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3565 - val_accuracy: 0.8750 - val_loss: 0.3572
Epoch 44/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8477 - loss: 0.3512 - val_accuracy: 0.8281 - val_loss: 0.3536
Epoch 45/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3514 - val_accuracy: 0.8594 - val_loss: 0.3535
Epoch 46/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3497 - val_accuracy: 0.8906 - val_loss: 0.3525
Epoch 47/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3496 - val_accuracy: 0.8906 - val_loss: 0.3521
Epoch 48/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3498 - val_accuracy: 0.8438 - val_loss: 0.3512
Epoch 49/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3491 - val_accuracy: 0.8906 - val_loss: 0.3511
Epoch 50/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3485 - val_accuracy: 0.8281 - val_loss: 0.3498
Epoch 51/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3489 - val_accuracy: 0.8750 - val_loss: 0.3503
Epoch 52/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3447 - val_accuracy: 0.8438 - val_loss: 0.3478
Epoch 53/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8398 - loss: 0.3454 - val_accuracy: 0.8750 - val_loss: 0.3465
Epoch 54/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3439 - val_accuracy: 0.8906 - val_loss: 0.3462
Epoch 55/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3441 - val_accuracy: 0.8906 - val_loss: 0.3454
Epoch 56/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3439 - val_accuracy: 0.8750 - val_loss: 0.3457
Epoch 57/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3419 - val_accuracy: 0.8750 - val_loss: 0.3447
Epoch 58/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3422 - val_accuracy: 0.8750 - val_loss: 0.3429
Epoch 59/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8320 - loss: 0.3401 - val_accuracy: 0.8906 - val_loss: 0.3435
Epoch 60/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3407 - val_accuracy: 0.8906 - val_loss: 0.3435
Epoch 61/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3381 - val_accuracy: 0.8906 - val_loss: 0.3410
Epoch 62/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8398 - loss: 0.3365 - val_accuracy: 0.8750 - val_loss: 0.3402
Epoch 63/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3361 - val_accuracy: 0.8750 - val_loss: 0.3401
Epoch 64/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3354 - val_accuracy: 0.9062 - val_loss: 0.3388
Epoch 65/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3344 - val_accuracy: 0.8594 - val_loss: 0.3378
Epoch 66/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3329 - val_accuracy: 0.9062 - val_loss: 0.3383
Epoch 67/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.3412 - val_accuracy: 0.8906 - val_loss: 0.3392
Epoch 68/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.3282 - val_accuracy: 0.8594 - val_loss: 0.3355
Epoch 69/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8320 - loss: 0.3336 - val_accuracy: 0.9062 - val_loss: 0.3346
Epoch 70/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8320 - loss: 0.3304 - val_accuracy: 0.8906 - val_loss: 0.3332
Epoch 71/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8555 - loss: 0.3327 - val_accuracy: 0.8906 - val_loss: 0.3338
Epoch 72/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3372 - val_accuracy: 0.8438 - val_loss: 0.3338
Epoch 73/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3435 - val_accuracy: 0.8906 - val_loss: 0.3380
Epoch 74/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8555 - loss: 0.3270 - val_accuracy: 0.8750 - val_loss: 0.3306
Epoch 75/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3261 - val_accuracy: 0.9062 - val_loss: 0.3299
Epoch 76/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8398 - loss: 0.3234 - val_accuracy: 0.9062 - val_loss: 0.3289
Epoch 77/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3223 - val_accuracy: 0.9062 - val_loss: 0.3272
Epoch 78/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8555 - loss: 0.3226 - val_accuracy: 0.8906 - val_loss: 0.3282
Epoch 79/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8477 - loss: 0.3203 - val_accuracy: 0.8750 - val_loss: 0.3261
Epoch 80/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8516 - loss: 0.3186 - val_accuracy: 0.8906 - val_loss: 0.3261
Epoch 81/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8516 - loss: 0.3174 - val_accuracy: 0.9062 - val_loss: 0.3245
Epoch 82/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8633 - loss: 0.3175 - val_accuracy: 0.9062 - val_loss: 0.3232
Epoch 83/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8477 - loss: 0.3161 - val_accuracy: 0.9062 - val_loss: 0.3226
Epoch 84/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8672 - loss: 0.3141 - val_accuracy: 0.8906 - val_loss: 0.3219
Epoch 85/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8594 - loss: 0.3132 - val_accuracy: 0.8906 - val_loss: 0.3209
Epoch 86/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8594 - loss: 0.3117 - val_accuracy: 0.8906 - val_loss: 0.3194
Epoch 87/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8477 - loss: 0.3106 - val_accuracy: 0.8906 - val_loss: 0.3184
Epoch 88/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8750 - loss: 0.3095 - val_accuracy: 0.8906 - val_loss: 0.3208
Epoch 89/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8516 - loss: 0.3123 - val_accuracy: 0.8750 - val_loss: 0.3176
Epoch 90/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8555 - loss: 0.3051 - val_accuracy: 0.8906 - val_loss: 0.3161
Epoch 91/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.3050 - val_accuracy: 0.8906 - val_loss: 0.3184
Epoch 92/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8594 - loss: 0.3100 - val_accuracy: 0.8750 - val_loss: 0.3141
Epoch 93/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8594 - loss: 0.3107 - val_accuracy: 0.9062 - val_loss: 0.3205
Epoch 94/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8477 - loss: 0.3027 - val_accuracy: 0.8750 - val_loss: 0.3136
Epoch 95/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8633 - loss: 0.3044 - val_accuracy: 0.8906 - val_loss: 0.3136
Epoch 96/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.2988 - val_accuracy: 0.8906 - val_loss: 0.3114
Epoch 97/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.2976 - val_accuracy: 0.8906 - val_loss: 0.3092
Epoch 98/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.2961 - val_accuracy: 0.8750 - val_loss: 0.3086
Epoch 99/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.2939 - val_accuracy: 0.8906 - val_loss: 0.3097
Epoch 100/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2933 - val_accuracy: 0.9062 - val_loss: 0.3102
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9375 - loss: 0.1854
Test Accuracy: 0.9375
Test Loss: 0.18537528812885284

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization
from tensorflow.keras.optimizers import Adam


model = Sequential()

model.add(Dense(
    64,
    activation='softplus',
    input_shape=(3,)
))

model.add(BatchNormalization())


model.add(Dense(
    32,
    activation='softplus'
))

model.add(BatchNormalization())


model.add(Dense(
    1,
    activation='sigmoid'
))


model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


history = model.fit(
    X_train,
    y_train,
    epochs=200,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)


loss, accuracy = model.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy)
print("Test Loss:", loss)

Epoch 1/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - accuracy: 0.6289 - loss: 0.7092 - val_accuracy: 0.3125 - val_loss: 1.1177
Epoch 2/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8477 - loss: 0.3850 - val_accuracy: 0.3125 - val_loss: 0.9529
Epoch 3/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8242 - loss: 0.4476 - val_accuracy: 0.3125 - val_loss: 0.8154
Epoch 4/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8516 - loss: 0.3678 - val_accuracy: 0.3281 - val_loss: 0.7409
Epoch 5/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8633 - loss: 0.3690 - val_accuracy: 0.5781 - val_loss: 0.6652
Epoch 6/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8281 - loss: 0.3618 - val_accuracy: 0.8750 - val_loss: 0.6093
Epoch 7/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8711 - loss: 0.3430 - val_accuracy: 0.8125 - val_loss: 0.5671
Epoch 8/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8633 - loss: 0.3415 - val_accuracy: 0.7969 - val_loss: 0.5329
Epoch 9/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.3375 - val_accuracy: 0.7812 - val_loss: 0.5109
Epoch 10/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.3136 - val_accuracy: 0.7188 - val_loss: 0.4821
Epoch 11/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.3019 - val_accuracy: 0.7344 - val_loss: 0.4655
Epoch 12/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8945 - loss: 0.3028 - val_accuracy: 0.7656 - val_loss: 0.4503
Epoch 13/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.3068 - val_accuracy: 0.7344 - val_loss: 0.4362
Epoch 14/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8633 - loss: 0.3234 - val_accuracy: 0.7812 - val_loss: 0.4245
Epoch 15/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.3118 - val_accuracy: 0.7812 - val_loss: 0.4080
Epoch 16/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3151 - val_accuracy: 0.7656 - val_loss: 0.4025
Epoch 17/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.2987 - val_accuracy: 0.7969 - val_loss: 0.3883
Epoch 18/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.2844 - val_accuracy: 0.8125 - val_loss: 0.3736
Epoch 19/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3299 - val_accuracy: 0.8281 - val_loss: 0.3571
Epoch 20/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8945 - loss: 0.2924 - val_accuracy: 0.8281 - val_loss: 0.3645
Epoch 21/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.2862 - val_accuracy: 0.8281 - val_loss: 0.3514
Epoch 22/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.3177 - val_accuracy: 0.8125 - val_loss: 0.3476
Epoch 23/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8398 - loss: 0.3372 - val_accuracy: 0.8281 - val_loss: 0.3477
Epoch 24/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.3255 - val_accuracy: 0.8594 - val_loss: 0.3317
Epoch 25/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2831 - val_accuracy: 0.8750 - val_loss: 0.3274
Epoch 26/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.3171 - val_accuracy: 0.8750 - val_loss: 0.3289
Epoch 27/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2878 - val_accuracy: 0.8750 - val_loss: 0.3363
Epoch 28/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8711 - loss: 0.2870 - val_accuracy: 0.8594 - val_loss: 0.3232
Epoch 29/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8750 - loss: 0.3210 - val_accuracy: 0.8594 - val_loss: 0.3145
Epoch 30/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2757 - val_accuracy: 0.8594 - val_loss: 0.3202
Epoch 31/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.3007 - val_accuracy: 0.8594 - val_loss: 0.3217
Epoch 32/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2788 - val_accuracy: 0.8594 - val_loss: 0.3346
Epoch 33/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.3293 - val_accuracy: 0.8594 - val_loss: 0.3300
Epoch 34/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.3129 - val_accuracy: 0.8906 - val_loss: 0.3312
Epoch 35/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.3008 - val_accuracy: 0.8594 - val_loss: 0.3205
Epoch 36/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2720 - val_accuracy: 0.8750 - val_loss: 0.3176
Epoch 37/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8984 - loss: 0.2638 - val_accuracy: 0.8594 - val_loss: 0.3204
Epoch 38/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.2762 - val_accuracy: 0.8750 - val_loss: 0.3212
Epoch 39/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2544 - val_accuracy: 0.8750 - val_loss: 0.3284
Epoch 40/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.3178 - val_accuracy: 0.8906 - val_loss: 0.3202
Epoch 41/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.2940 - val_accuracy: 0.8750 - val_loss: 0.3329
Epoch 42/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.3044 - val_accuracy: 0.8750 - val_loss: 0.3125
Epoch 43/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.2965 - val_accuracy: 0.8594 - val_loss: 0.3185
Epoch 44/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2927 - val_accuracy: 0.8750 - val_loss: 0.3221
Epoch 45/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8711 - loss: 0.2816 - val_accuracy: 0.8750 - val_loss: 0.3251
Epoch 46/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9102 - loss: 0.2413 - val_accuracy: 0.8906 - val_loss: 0.3342
Epoch 47/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8750 - loss: 0.3198 - val_accuracy: 0.8750 - val_loss: 0.3285
Epoch 48/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8789 - loss: 0.2952 - val_accuracy: 0.8750 - val_loss: 0.3254
Epoch 49/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8789 - loss: 0.3077 - val_accuracy: 0.8906 - val_loss: 0.3163
Epoch 50/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8711 - loss: 0.3206 - val_accuracy: 0.8906 - val_loss: 0.3256
Epoch 51/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8789 - loss: 0.2750 - val_accuracy: 0.8438 - val_loss: 0.3229
Epoch 52/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8945 - loss: 0.2624 - val_accuracy: 0.8750 - val_loss: 0.3229
Epoch 53/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8672 - loss: 0.3388 - val_accuracy: 0.8906 - val_loss: 0.3223
Epoch 54/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8789 - loss: 0.3002 - val_accuracy: 0.8750 - val_loss: 0.3320
Epoch 55/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8789 - loss: 0.3089 - val_accuracy: 0.8906 - val_loss: 0.3273
Epoch 56/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8594 - loss: 0.3289 - val_accuracy: 0.8906 - val_loss: 0.3144
Epoch 57/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8711 - loss: 0.3142 - val_accuracy: 0.8750 - val_loss: 0.3098
Epoch 58/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.2878 - val_accuracy: 0.8750 - val_loss: 0.3062
Epoch 59/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8906 - loss: 0.2713 - val_accuracy: 0.8906 - val_loss: 0.3164
Epoch 60/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8867 - loss: 0.2782 - val_accuracy: 0.8906 - val_loss: 0.3156
Epoch 61/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8867 - loss: 0.2762 - val_accuracy: 0.8750 - val_loss: 0.3143
Epoch 62/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.3034 - val_accuracy: 0.8594 - val_loss: 0.2996
Epoch 63/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.2847 - val_accuracy: 0.8906 - val_loss: 0.3212
Epoch 64/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8555 - loss: 0.3024 - val_accuracy: 0.8750 - val_loss: 0.3227
Epoch 65/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.3182 - val_accuracy: 0.8594 - val_loss: 0.3176
Epoch 66/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.3125 - val_accuracy: 0.8906 - val_loss: 0.3258
Epoch 67/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.2787 - val_accuracy: 0.8906 - val_loss: 0.3306
Epoch 68/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8594 - loss: 0.2897 - val_accuracy: 0.8750 - val_loss: 0.3197
Epoch 69/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.3011 - val_accuracy: 0.8750 - val_loss: 0.3224
Epoch 70/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2773 - val_accuracy: 0.8906 - val_loss: 0.3182
Epoch 71/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.2943 - val_accuracy: 0.8906 - val_loss: 0.3179
Epoch 72/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.2980 - val_accuracy: 0.8906 - val_loss: 0.3210
Epoch 73/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2605 - val_accuracy: 0.8906 - val_loss: 0.3382
Epoch 74/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8711 - loss: 0.2971 - val_accuracy: 0.8906 - val_loss: 0.3283
Epoch 75/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2716 - val_accuracy: 0.8750 - val_loss: 0.3178
Epoch 76/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.2888 - val_accuracy: 0.8906 - val_loss: 0.3172
Epoch 77/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8633 - loss: 0.2861 - val_accuracy: 0.8906 - val_loss: 0.3071
Epoch 78/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2457 - val_accuracy: 0.8750 - val_loss: 0.3113
Epoch 79/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2456 - val_accuracy: 0.8906 - val_loss: 0.3191
Epoch 80/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8555 - loss: 0.3296 - val_accuracy: 0.8906 - val_loss: 0.3185
Epoch 81/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.2963 - val_accuracy: 0.8594 - val_loss: 0.3154
Epoch 82/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8633 - loss: 0.3216 - val_accuracy: 0.8750 - val_loss: 0.3080
Epoch 83/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2532 - val_accuracy: 0.8750 - val_loss: 0.3062
Epoch 84/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2532 - val_accuracy: 0.8906 - val_loss: 0.3199
Epoch 85/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9062 - loss: 0.2875 - val_accuracy: 0.8906 - val_loss: 0.3084
Epoch 86/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8867 - loss: 0.2865 - val_accuracy: 0.8906 - val_loss: 0.3151
Epoch 87/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8711 - loss: 0.3029 - val_accuracy: 0.8750 - val_loss: 0.3091
Epoch 88/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2832 - val_accuracy: 0.8750 - val_loss: 0.3066
Epoch 89/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.2966 - val_accuracy: 0.8906 - val_loss: 0.3072
Epoch 90/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2880 - val_accuracy: 0.8906 - val_loss: 0.3123
Epoch 91/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2677 - val_accuracy: 0.8750 - val_loss: 0.3211
Epoch 92/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8633 - loss: 0.3001 - val_accuracy: 0.8750 - val_loss: 0.3053
Epoch 93/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2587 - val_accuracy: 0.8906 - val_loss: 0.3168
Epoch 94/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8867 - loss: 0.3010 - val_accuracy: 0.8750 - val_loss: 0.3181
Epoch 95/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2603 - val_accuracy: 0.8906 - val_loss: 0.3100
Epoch 96/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2520 - val_accuracy: 0.8906 - val_loss: 0.2991
Epoch 97/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.2784 - val_accuracy: 0.8750 - val_loss: 0.3194
Epoch 98/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8711 - loss: 0.2849 - val_accuracy: 0.8906 - val_loss: 0.3184
Epoch 99/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8711 - loss: 0.2765 - val_accuracy: 0.8906 - val_loss: 0.3259
Epoch 100/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.2685 - val_accuracy: 0.8906 - val_loss: 0.3142
Epoch 101/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8633 - loss: 0.3164 - val_accuracy: 0.8594 - val_loss: 0.3177
Epoch 102/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.3111 - val_accuracy: 0.8594 - val_loss: 0.3119
Epoch 103/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8945 - loss: 0.2792 - val_accuracy: 0.8750 - val_loss: 0.3178
Epoch 104/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.2879 - val_accuracy: 0.8750 - val_loss: 0.3056
Epoch 105/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8281 - loss: 0.3443 - val_accuracy: 0.8750 - val_loss: 0.3112
Epoch 106/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.2748 - val_accuracy: 0.8750 - val_loss: 0.3144
Epoch 107/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8828 - loss: 0.2549 - val_accuracy: 0.8906 - val_loss: 0.3318
Epoch 108/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2660 - val_accuracy: 0.8906 - val_loss: 0.3027
Epoch 109/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.2744 - val_accuracy: 0.8594 - val_loss: 0.3042
Epoch 110/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.2732 - val_accuracy: 0.8906 - val_loss: 0.3165
Epoch 111/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9062 - loss: 0.2399 - val_accuracy: 0.8906 - val_loss: 0.3195
Epoch 112/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2346 - val_accuracy: 0.8906 - val_loss: 0.3177
Epoch 113/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8711 - loss: 0.3136 - val_accuracy: 0.8906 - val_loss: 0.3180
Epoch 114/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2646 - val_accuracy: 0.8906 - val_loss: 0.3046
Epoch 115/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.3138 - val_accuracy: 0.8906 - val_loss: 0.2933
Epoch 116/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2573 - val_accuracy: 0.8906 - val_loss: 0.3006
Epoch 117/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.2807 - val_accuracy: 0.8906 - val_loss: 0.3093
Epoch 118/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8867 - loss: 0.3012 - val_accuracy: 0.8750 - val_loss: 0.3062
Epoch 119/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8789 - loss: 0.2898 - val_accuracy: 0.8750 - val_loss: 0.3147
Epoch 120/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8945 - loss: 0.2869 - val_accuracy: 0.8750 - val_loss: 0.3062
Epoch 121/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.2771 - val_accuracy: 0.8906 - val_loss: 0.3026
Epoch 122/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.2650 - val_accuracy: 0.8750 - val_loss: 0.2974
Epoch 123/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8711 - loss: 0.2821 - val_accuracy: 0.8750 - val_loss: 0.2961
Epoch 124/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8711 - loss: 0.3168 - val_accuracy: 0.8906 - val_loss: 0.3094
Epoch 125/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8789 - loss: 0.2729 - val_accuracy: 0.8750 - val_loss: 0.3061
Epoch 126/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2709 - val_accuracy: 0.8906 - val_loss: 0.3305
Epoch 127/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2802 - val_accuracy: 0.8906 - val_loss: 0.3210
Epoch 128/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2635 - val_accuracy: 0.8906 - val_loss: 0.3183
Epoch 129/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.2604 - val_accuracy: 0.8906 - val_loss: 0.3138
Epoch 130/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8945 - loss: 0.2792 - val_accuracy: 0.8906 - val_loss: 0.2971
Epoch 131/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2509 - val_accuracy: 0.8906 - val_loss: 0.3110
Epoch 132/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8750 - loss: 0.3196 - val_accuracy: 0.8906 - val_loss: 0.3042
Epoch 133/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9102 - loss: 0.2365 - val_accuracy: 0.8906 - val_loss: 0.3041
Epoch 134/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9062 - loss: 0.2620 - val_accuracy: 0.8906 - val_loss: 0.3128
Epoch 135/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2735 - val_accuracy: 0.8906 - val_loss: 0.3031
Epoch 136/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8984 - loss: 0.2549 - val_accuracy: 0.8906 - val_loss: 0.3013
Epoch 137/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9102 - loss: 0.2578 - val_accuracy: 0.8906 - val_loss: 0.3057
Epoch 138/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9062 - loss: 0.2613 - val_accuracy: 0.8906 - val_loss: 0.3185
Epoch 139/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9102 - loss: 0.2285 - val_accuracy: 0.8906 - val_loss: 0.3158
Epoch 140/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8867 - loss: 0.2610 - val_accuracy: 0.8906 - val_loss: 0.3242
Epoch 141/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9062 - loss: 0.2691 - val_accuracy: 0.8750 - val_loss: 0.3043
Epoch 142/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8672 - loss: 0.3396 - val_accuracy: 0.8906 - val_loss: 0.3060
Epoch 143/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8750 - loss: 0.2560 - val_accuracy: 0.8906 - val_loss: 0.2971
Epoch 144/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9180 - loss: 0.2382 - val_accuracy: 0.8906 - val_loss: 0.2966
Epoch 145/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8984 - loss: 0.2524 - val_accuracy: 0.8906 - val_loss: 0.3120
Epoch 146/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8789 - loss: 0.2808 - val_accuracy: 0.8906 - val_loss: 0.3007
Epoch 147/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8867 - loss: 0.2897 - val_accuracy: 0.8906 - val_loss: 0.2984
Epoch 148/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8867 - loss: 0.2528 - val_accuracy: 0.8594 - val_loss: 0.2860
Epoch 149/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8828 - loss: 0.2722 - val_accuracy: 0.8906 - val_loss: 0.3005
Epoch 150/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9102 - loss: 0.2331 - val_accuracy: 0.8750 - val_loss: 0.3043
Epoch 151/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8672 - loss: 0.2642 - val_accuracy: 0.8750 - val_loss: 0.3114
Epoch 152/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8555 - loss: 0.3580 - val_accuracy: 0.8906 - val_loss: 0.3092
Epoch 153/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.2720 - val_accuracy: 0.8906 - val_loss: 0.3149
Epoch 154/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9219 - loss: 0.2380 - val_accuracy: 0.8906 - val_loss: 0.3080
Epoch 155/200
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8906 - loss: 0.2847 - val_accuracy: 0.8594 - val_loss: 0.2978
Epoch 156/200

In [ ]:
!pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.81.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 4.8 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [ ]:
# Import Libraries
import keras_tuner as kt
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam


# Build Model Function
def build_model(hp):

    model = Sequential()

    # First Hidden Layer
    model.add(Dense(
        units=hp.Int(
            'units_1',
            min_value=8,
            max_value=64,
            step=8
        ),
        activation=hp.Choice(
            'activation_1',
            ['relu', 'softplus', 'tanh', 'elu']
        ),
        input_shape=(3,)
    ))


    # Second Hidden Layer
    model.add(Dense(
        units=hp.Int(
            'units_2',
            min_value=4,
            max_value=32,
            step=4
        ),
        activation=hp.Choice(
            'activation_2',
            ['relu', 'softplus', 'tanh', 'elu']
        )
    ))


    # Dropout
    model.add(Dropout(
        hp.Float(
            'dropout',
            min_value=0.0,
            max_value=0.5,
            step=0.1
        )
    ))


    # Output Layer
    model.add(Dense(
        1,
        activation='sigmoid'
    ))


    # Learning Rate
    learning_rate = hp.Choice(
        'learning_rate',
        [0.001, 0.0005, 0.0001]
    )


    model.compile(
        optimizer=Adam(
            learning_rate=learning_rate
        ),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )


    return model



# Create Tuner
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=20,
    executions_per_trial=3,
    directory='tuning_results',
    project_name='iphone_purchase'
)


# Search Best Model
tuner.search(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)


# Get Best Model
best_model = tuner.get_best_models(num_models=1)[0]


# Show Best Architecture
best_model.summary()


# Evaluate Best Model
loss, accuracy = best_model.evaluate(
    X_test,
    y_test
)


print("Best Test Accuracy:", accuracy)
print("Best Test Loss:", loss)


# Get Best Hyperparameters
best_hp = tuner.get_best_hyperparameters(1)[0]

print("\nBest Hyperparameters:")
print("Layer 1 Neurons:", best_hp.get('units_1'))
print("Layer 1 Activation:", best_hp.get('activation_1'))
print("Layer 2 Neurons:", best_hp.get('units_2'))
print("Layer 2 Activation:", best_hp.get('activation_2'))
print("Dropout:", best_hp.get('dropout'))
print("Learning Rate:", best_hp.get('learning_rate'))

Trial 20 Complete [00h 00m 50s]
val_accuracy: 0.6979166666666666

Best val_accuracy So Far: 0.9114583333333334
Total elapsed time: 00h 16m 53s

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            64 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 209 (836.00 B)

 Trainable params: 209 (836.00 B)

 Non-trainable params: 0 (0.00 B)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9000 - loss: 0.5611
Best Test Accuracy: 0.8999999761581421
Best Test Loss: 0.5611392259597778

Best Hyperparameters:
Layer 1 Neurons: 16
Layer 1 Activation: tanh
Layer 2 Neurons: 8
Layer 2 Activation: relu
Dropout: 0.30000000000000004
Learning Rate: 0.0005