In [1]:
import pandas as pd
import glob
import os

In [2]:
path = "data/"
files = glob.glob(path + "/*.csv")

df_list = []

for file in files:
    df = pd.read_csv(file)
    df["Store"] = os.path.basename(file)
    df_list.append(df)

raw_df = pd.concat(df_list, ignore_index=True)

In [3]:
print(raw_df.shape)
print(raw_df.columns)
raw_df.head()

(300, 8)
Index(['ProductName', 'Qty', 'Unit_Price', 'SaleDate', 'CurrencyType',
       'CustomerID', 'StoreID', 'Store'],
      dtype='str')

,ProductName,Qty,Unit_Price,SaleDate,CurrencyType,CustomerID,StoreID,Store
0,Smith Paper,3.0,10.5,7/13/2024,OMR,9ca482a2-0356-49c1-b5e3-88ae98d1cc2f,Store_A,store_sales_1.csv
1,Johnson Screen,NaN,NaN,2/23/2025,Usd,c0b9df4e-8f03-4bf0-a31b-0a7d7c2a8907,Store_A,store_sales_1.csv
2,Roberts Ingredient,3.0,30.0,11/13/2024,USD,97dc18e3-2c12-4e26-9863-32514e82e822,Store_A,store_sales_1.csv
3,White Monitor,NaN,10.5,4/16/2025,USD,e4d09733-d496-47b3-a4b5-04de84d8fd06,Store_A,store_sales_1.csv
4,Rodriguez Keyboard,2.0,20.0,8/3/2024,usd,435ecb46-4545-4af7-b72c-119f64d193a5,Store_A,store_sales_1.csv

In [5]:
numeric_cols = raw_df.select_dtypes(include=["number"]).columns.tolist()

categorical_cols = raw_df.select_dtypes(
    include=["object", "string"]
).columns.tolist()

In [6]:
X = raw_df[numeric_cols + categorical_cols]

In [7]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [8]:
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

In [9]:
categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

In [10]:
preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numeric_cols),
    ("cat", categorical_transformer, categorical_cols)
])

In [11]:
X_transformed = preprocessor.fit_transform(X)
print(X_transformed.shape)

(300, 669)

In [12]:
encoded_cols = preprocessor.get_feature_names_out()

df_final = pd.DataFrame(X_transformed, columns=encoded_cols)
df_final.head()

,num__Qty,num__Unit_Price,cat__ProductName_Actually,cat__ProductName_Adams Brush,cat__ProductName_Alexander Spray,cat__ProductName_Allen Brush,cat__ProductName_Allen Notebook,cat__ProductName_Anderson Lamp,cat__ProductName_Arnold Fork,cat__ProductName_Arnold Speaker,...,cat__CustomerID_fe6e6f78-bdc3-4deb-a6a2-5f9cd36d2484,cat__CustomerID_feaeae49-e208-4b0b-a4ee-88ab5eb6a7c5,cat__CustomerID_ff1f1a3e-4889-46d4-824e-d92e4c51cf45,cat__CustomerID_ff8159fe-b68a-4bd9-848d-64b836a96eae,cat__StoreID_STORE_A,cat__StoreID_Store_A,cat__StoreID_store-A,cat__Store_store_sales_1.csv,cat__Store_store_sales_2.csv,cat__Store_store_sales_3.csv
0,1.270501e+00,-1.330720,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,6.217329e-16,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,1.270501e+00,1.726353,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,6.217329e-16,-1.330720,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,-1.295171e-01,0.158623,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [13]:
pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl (72 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [16]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (9.7.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [18]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="1234",
    database="RetailDW"
)

cursor = conn.cursor()

print("Connected to MySQL!")

Connected to MySQL!

In [19]:
pip install sqlalchemy pymysql

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.50-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.1-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.50-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ------------------- -------------------- 1.0/2.1 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 8.8 MB/s  0:00:00
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Downloading greenlet-3.5.1-cp314-cp314-win_amd64.whl (239 kB)
Installing collected packages: pymysql, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [pymysql]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.1 pymysql-1.2.0 sqlalchemy-2.0.50
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [21]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:1234@localhost/RetailDW"
)

df_final.to_sql(
    "sales_processed",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data loaded into MySQL!")

OperationalError: (pymysql.err.OperationalError) (1060, "Duplicate column name 'cat__CurrencyType_Usd'")
[SQL:
CREATE TABLE sales_processed (
	`num__Qty` FLOAT(53),
	`num__Unit_Price` FLOAT(53),
	`cat__ProductName_Actually` FLOAT(53),
	`cat__ProductName_Adams Brush` FLOAT(53),
	`cat__ProductName_Alexander Spray` FLOAT(53),
	`cat__ProductName_Allen Brush` FLOAT(53),
	`cat__ProductName_Allen Notebook` FLOAT(53),
	`cat__ProductName_Anderson Lamp` FLOAT(53),
	`cat__ProductName_Arnold Fork` FLOAT(53),
	`cat__ProductName_Arnold Speaker` FLOAT(53),
	`cat__ProductName_Arnold Stick` FLOAT(53),
	`cat__ProductName_Bailey Drill` FLOAT(53),
	`cat__ProductName_Baker Speaker` FLOAT(53),
	`cat__ProductName_Ball Notebook` FLOAT(53),
	`cat__ProductName_Banks Gloves` FLOAT(53),
	`cat__ProductName_Barker Book` FLOAT(53),
	`cat__ProductName_Barker Deodorant` FLOAT(53),
	`cat__ProductName_Barnes Belt` FLOAT(53),
	`cat__ProductName_Barrett Basket` FLOAT(53),
	`cat__ProductName_Bell Glove` FLOAT(53),
	`cat__ProductName_Bennett Lock` FLOAT(53),
	`cat__ProductName_Black` FLOAT(53),
	`cat__ProductName_Boone Balm` FLOAT(53),
	`cat__ProductName_Boone Polish` FLOAT(53),
	`cat__ProductName_Bowen Tire` FLOAT(53),
	`cat__ProductName_Brooks Cap` FLOAT(53),
	`cat__ProductName_Bryant Brush` FLOAT(53),
	`cat__ProductName_Butler Jacket` FLOAT(53),
	`cat__ProductName_Cameron Fan` FLOAT(53),
	`cat__ProductName_Carter Fan` FLOAT(53),
	`cat__ProductName_Case` FLOAT(53),
	`cat__ProductName_Chavez Printer` FLOAT(53),
	`cat__ProductName_Clark Glass` FLOAT(53),
	`cat__ProductName_Cole Disk` FLOAT(53),
	`cat__ProductName_Cole Polish` FLOAT(53),
	`cat__ProductName_Coleman Case` FLOAT(53),
	`cat__ProductName_Collins Rug` FLOAT(53),
	`cat__ProductName_Conner Gel` FLOAT(53),
	`cat__ProductName_Cook Ball` FLOAT(53),
	`cat__ProductName_Cook Tray` FLOAT(53),
	`cat__ProductName_Cooper Knife` FLOAT(53),
	`cat__ProductName_Cox Screw` FLOAT(53),
	`cat__ProductName_Cross Rack` FLOAT(53),
	`cat__ProductName_Daniels Coat` FLOAT(53),
	`cat__ProductName_Dean Screw` FLOAT(53),
	`cat__ProductName_Dean Shelf` FLOAT(53),
	`cat__ProductName_Dennis Mug` FLOAT(53),
	`cat__ProductName_Diaz Soap` FLOAT(53),
	`cat__ProductName_Dixon Marker` FLOAT(53),
	`cat__ProductName_Doyle Grip` FLOAT(53),
	`cat__ProductName_Doyle Powder` FLOAT(53),
	`cat__ProductName_Edwards Mixer` FLOAT(53),
	`cat__ProductName_Evans Tape` FLOAT(53),
	`cat__ProductName_Fisher Clip` FLOAT(53),
	`cat__ProductName_Fisher Cover` FLOAT(53),
	`cat__ProductName_Fleming Tray` FLOAT(53),
	`cat__ProductName_Flores Coat` FLOAT(53),
	`cat__ProductName_Flowers Thread` FLOAT(53),
	`cat__ProductName_Ford Gel` FLOAT(53),
	`cat__ProductName_Foster Hat` FLOAT(53),
	`cat__ProductName_Foster Hook` FLOAT(53),
	`cat__ProductName_Fox Calendar` FLOAT(53),
	`cat__ProductName_Franklin Bag` FLOAT(53),
	`cat__ProductName_Gardner Sheet` FLOAT(53),
	`cat__ProductName_Gibbs Cream` FLOAT(53),
	`cat__ProductName_Gibson Clock` FLOAT(53),
	`cat__ProductName_Gilbert Pad` FLOAT(53),
	`cat__ProductName_Gonzales Sock` FLOAT(53),
	`cat__ProductName_Graham Cleaner` FLOAT(53),
	`cat__ProductName_Gray Tool` FLOAT(53),
	`cat__ProductName_Green Folder` FLOAT(53),
	`cat__ProductName_Gregory Helmet` FLOAT(53),
	`cat__ProductName_Griffin Cream` FLOAT(53),
	`cat__ProductName_Hall Cup` FLOAT(53),
	`cat__ProductName_Hamilton Paste` FLOAT(53),
	`cat__ProductName_Hanson Flashlight` FLOAT(53),
	`cat__ProductName_Harmon Net` FLOAT(53),
	`cat__ProductName_Harper Phone` FLOAT(53),
	`cat__ProductName_Harris Pen` FLOAT(53),
	`cat__ProductName_Hayes Lotion` FLOAT(53),
	`cat__ProductName_Henderson Gear` FLOAT(53),
	`cat__ProductName_Hill Phone` FLOAT(53),
	`cat__ProductName_Holland Nail` FLOAT(53),
	`cat__ProductName_Holmes Book` FLOAT(53),
	`cat__ProductName_Holmes Hook` FLOAT(53),
	`cat__ProductName_Horton Cable` FLOAT(53),
	`cat__ProductName_Howard Can` FLOAT(53),
	`cat__ProductName_Hudson Lamp` FLOAT(53),
	`cat__ProductName_Hughes Strap` FLOAT(53),
	`cat__ProductName_Ingram Booklet` FLOAT(53),
	`cat__ProductName_Jackson Cable` FLOAT(53),
	`cat__ProductName_James Grip` FLOAT(53),
	`cat__ProductName_Jenkins Valve` FLOAT(53),
	`cat__ProductName_Johnson Mirror` FLOAT(53),
	`cat__ProductName_Johnson Screen` FLOAT(53),
	`cat__ProductName_Jordan Bleach` FLOAT(53),
	`cat__ProductName_Kelly String` FLOAT(53),
	`cat__ProductName_Lane Mug` FLOAT(53),
	`cat__ProductName_Larson Rack` FLOAT(53),
	`cat__ProductName_Lee Clock` FLOAT(53),
	`cat__ProductName_Lewis Ruler` FLOAT(53),
	`cat__ProductName_Line` FLOAT(53),
	`cat__ProductName_Lloyd Mixer` FLOAT(53),
	`cat__ProductName_Long Mat` FLOAT(53),
	`cat__ProductName_Marsh Jar` FLOAT(53),
	`cat__ProductName_Martin Charger` FLOAT(53),
	`cat__ProductName_Matthews Plate` FLOAT(53),
	`cat__ProductName_Mitchell Frame` FLOAT(53),
	`cat__ProductName_Moody Net` FLOAT(53),
	`cat__ProductName_Moore Chair` FLOAT(53),
	`cat__ProductName_Morgan Stick` FLOAT(53),
	`cat__ProductName_Morris Bottle` FLOAT(53),
	`cat__ProductName_Morris Tray` FLOAT(53),
	`cat__ProductName_Murphy Dish` FLOAT(53),
	`cat__ProductName_Myers Shampoo` FLOAT(53),
	`cat__ProductName_Nelson Knife` FLOAT(53),
	`cat__ProductName_Newman Rod` FLOAT(53),
	`cat__ProductName_On` FLOAT(53),
	`cat__ProductName_Owens Powder` FLOAT(53),
	`cat__ProductName_Owens Tape` FLOAT(53),
	`cat__ProductName_Page Pen` FLOAT(53),
	`cat__ProductName_Palmer Screen` FLOAT(53),
	`cat__ProductName_Parker Cable` FLOAT(53),
	`cat__ProductName_Patterson Filter` FLOAT(53),
	`cat__ProductName_Perez Board` FLOAT(53),
	`cat__ProductName_Perry Switch` FLOAT(53),
	`cat__ProductName_Peterson Sheet` FLOAT(53),
	`cat__ProductName_Phillips Hook` FLOAT(53),
	`cat__ProductName_Pierce File` FLOAT(53),
	`cat__ProductName_Pierce Plate` FLOAT(53),
	`cat__ProductName_Potter Shield` FLOAT(53),
	`cat__ProductName_Powell Tube` FLOAT(53),
	`cat__ProductName_Price Clip` FLOAT(53),
	`cat__ProductName_Ramirez Bar` FLOAT(53),
	`cat__ProductName_Reed Rack` FLOAT(53),
	`cat__ProductName_Reid Strap` FLOAT(53),
	`cat__ProductName_Richardson Nail` FLOAT(53),
	`cat__ProductName_Rivera Block` FLOAT(53),
	`cat__ProductName_Rivers Lid` FLOAT(53),
	`cat__ProductName_Roberts Ingredient` FLOAT(53),
	`cat__ProductName_Roberts Pen` FLOAT(53),
	`cat__ProductName_Robinson Shelf` FLOAT(53),
	`cat__ProductName_Rodriguez Keyboard` FLOAT(53),
	`cat__ProductName_Rogers Lid` FLOAT(53),
	`cat__ProductName_Ross Cover` FLOAT(53),
	`cat__ProductName_Russell Oil` FLOAT(53),
	`cat__ProductName_Sanchez Book` FLOAT(53),
	`cat__ProductName_Sanders Pin` FLOAT(53),
	`cat__ProductName_Sanderson Spray` FLOAT(53),
	`cat__ProductName_Scott Plate` FLOAT(53),
	`cat__ProductName_Simmons Shorts` FLOAT(53),
	`cat__ProductName_Sims Brush` FLOAT(53),
	`cat__ProductName_Skill` FLOAT(53),
	`cat__ProductName_Smith Bag` FLOAT(53),
	`cat__ProductName_Smith Paper` FLOAT(53),
	`cat__ProductName_Soon` FLOAT(53),
	`cat__ProductName_Spencer Frame` FLOAT(53),
	`cat__ProductName_Stevens Cap` FLOAT(53),
	`cat__ProductName_Stewart Mouse` FLOAT(53),
	`cat__ProductName_Sullivan Wax` FLOAT(53),
	`cat__ProductName_Swanson Bucket` FLOAT(53),
	`cat__ProductName_Taylor Table` FLOAT(53),
	`cat__ProductName_Torres Stand` FLOAT(53),
	`cat__ProductName_Torres Table` FLOAT(53),
	`cat__ProductName_Tucker Helmet` FLOAT(53),
	`cat__ProductName_Turner Pad` FLOAT(53),
	`cat__ProductName_Vang Charger` FLOAT(53),
	`cat__ProductName_Vasquez Bottle` FLOAT(53),
	`cat__ProductName_Wade Charger` FLOAT(53),
	`cat__ProductName_Walker Camera` FLOAT(53),
	`cat__ProductName_Wallace Polish` FLOAT(53),
	`cat__ProductName_Wallace Sheet` FLOAT(53),
	`cat__ProductName_Ward Plug` FLOAT(53),
	`cat__ProductName_Warren Lamp` FLOAT(53),
	`cat__ProductName_Washington Skirt` FLOAT(53),
	`cat__ProductName_Watson Chain` FLOAT(53),
	`cat__ProductName_Welch Mirror` FLOAT(53),
	`cat__ProductName_Welch Spray` FLOAT(53),
	`cat__ProductName_West Shine` FLOAT(53),
	`cat__ProductName_White Monitor` FLOAT(53),
	`cat__ProductName_Williams Bottle` FLOAT(53),
	`cat__ProductName_Wood Tire` FLOAT(53),
	`cat__ProductName_Woods Detergent` FLOAT(53),
	`cat__ProductName_Young Printer` FLOAT(53),
	`cat__SaleDate_1/1/2025` FLOAT(53),
	`cat__SaleDate_1/10/2025` FLOAT(53),
	`cat__SaleDate_1/11/2025` FLOAT(53),
	`cat__SaleDate_1/15/2025` FLOAT(53),
	`cat__SaleDate_1/16/2025` FLOAT(53),
	`cat__SaleDate_1/19/2025` FLOAT(53),
	`cat__SaleDate_1/20/2025` FLOAT(53),
	`cat__SaleDate_1/21/2025` FLOAT(53),
	`cat__SaleDate_1/22/2025` FLOAT(53),
	`cat__SaleDate_1/23/2025` FLOAT(53),
	`cat__SaleDate_1/24/2025` FLOAT(53),
	`cat__SaleDate_1/5/2025` FLOAT(53),
	`cat__SaleDate_1/6/2025` FLOAT(53),
	`cat__SaleDate_1/7/2025` FLOAT(53),
	`cat__SaleDate_1/9/2025` FLOAT(53),
	`cat__SaleDate_10/10/2024` FLOAT(53),
	`cat__SaleDate_10/11/2024` FLOAT(53),
	`cat__SaleDate_10/12/2024` FLOAT(53),
	`cat__SaleDate_10/13/2024` FLOAT(53),
	`cat__SaleDate_10/14/2024` FLOAT(53),
	`cat__SaleDate_10/15/2024` FLOAT(53),
	`cat__SaleDate_10/17/2024` FLOAT(53),
	`cat__SaleDate_10/18/2024` FLOAT(53),
	`cat__SaleDate_10/19/2024` FLOAT(53),
	`cat__SaleDate_10/20/2024` FLOAT(53),
	`cat__SaleDate_10/21/2024` FLOAT(53),
	`cat__SaleDate_10/25/2024` FLOAT(53),
	`cat__SaleDate_10/26/2024` FLOAT(53),
	`cat__SaleDate_10/27/2024` FLOAT(53),
	`cat__SaleDate_10/4/2024` FLOAT(53),
	`cat__SaleDate_10/6/2024` FLOAT(53),
	`cat__SaleDate_10/8/2024` FLOAT(53),
	`cat__SaleDate_11/1/2024` FLOAT(53),
	`cat__SaleDate_11/10/2024` FLOAT(53),
	`cat__SaleDate_11/11/2024` FLOAT(53),
	`cat__SaleDate_11/13/2024` FLOAT(53),
	`cat__SaleDate_11/18/2024` FLOAT(53),
	`cat__SaleDate_11/19/2024` FLOAT(53),
	`cat__SaleDate_11/2/2024` FLOAT(53),
	`cat__SaleDate_11/22/2024` FLOAT(53),
	`cat__SaleDate_11/23/2024` FLOAT(53),
	`cat__SaleDate_11/24/2024` FLOAT(53),
	`cat__SaleDate_11/25/2024` FLOAT(53),
	`cat__SaleDate_11/26/2024` FLOAT(53),
	`cat__SaleDate_11/3/2024` FLOAT(53),
	`cat__SaleDate_11/30/2024` FLOAT(53),
	`cat__SaleDate_11/5/2024` FLOAT(53),
	`cat__SaleDate_11/6/2024` FLOAT(53),
	`cat__SaleDate_11/7/2024` FLOAT(53),
	`cat__SaleDate_11/8/2024` FLOAT(53),
	`cat__SaleDate_11/9/2024` FLOAT(53),
	`cat__SaleDate_12/1/2024` FLOAT(53),
	`cat__SaleDate_12/13/2024` FLOAT(53),
	`cat__SaleDate_12/15/2024` FLOAT(53),
	`cat__SaleDate_12/17/2024` FLOAT(53),
	`cat__SaleDate_12/18/2024` FLOAT(53),
	`cat__SaleDate_12/2/2024` FLOAT(53),
	`cat__SaleDate_12/20/2024` FLOAT(53),
	`cat__SaleDate_12/24/2024` FLOAT(53),
	`cat__SaleDate_12/25/2024` FLOAT(53),
	`cat__SaleDate_12/26/2024` FLOAT(53),
	`cat__SaleDate_12/27/2024` FLOAT(53),
	`cat__SaleDate_12/28/2024` FLOAT(53),
	`cat__SaleDate_12/29/2024` FLOAT(53),
	`cat__SaleDate_12/3/2024` FLOAT(53),
	`cat__SaleDate_12/31/2024` FLOAT(53),
	`cat__SaleDate_12/7/2024` FLOAT(53),
	`cat__SaleDate_12/9/2024` FLOAT(53),
	`cat__SaleDate_2/10/2025` FLOAT(53),
	`cat__SaleDate_2/11/2025` FLOAT(53),
	`cat__SaleDate_2/12/2025` FLOAT(53),
	`cat__SaleDate_2/17/2025` FLOAT(53),
	`cat__SaleDate_2/18/2025` FLOAT(53),
	`cat__SaleDate_2/19/2025` FLOAT(53),
	`cat__SaleDate_2/2/2025` FLOAT(53),
	`cat__SaleDate_2/20/2025` FLOAT(53),
	`cat__SaleDate_2/21/2025` FLOAT(53),
	`cat__SaleDate_2/22/2025` FLOAT(53),
	`cat__SaleDate_2/23/2025` FLOAT(53),
	`cat__SaleDate_2/24/2025` FLOAT(53),
	`cat__SaleDate_2/25/2025` FLOAT(53),
	`cat__SaleDate_2/3/2025` FLOAT(53),
	`cat__SaleDate_2/6/2025` FLOAT(53),
	`cat__SaleDate_2/7/2025` FLOAT(53),
	`cat__SaleDate_2/9/2025` FLOAT(53),
	`cat__SaleDate_3/12/2025` FLOAT(53),
	`cat__SaleDate_3/16/2025` FLOAT(53),
	`cat__SaleDate_3/17/2025` FLOAT(53),
	`cat__SaleDate_3/18/2025` FLOAT(53),
	`cat__SaleDate_3/20/2025` FLOAT(53),
	`cat__SaleDate_3/21/2025` FLOAT(53),
	`cat__SaleDate_3/22/2025` FLOAT(53),
	`cat__SaleDate_3/23/2025` FLOAT(53),
	`cat__SaleDate_3/24/2025` FLOAT(53),
	`cat__SaleDate_3/25/2025` FLOAT(53),
	`cat__SaleDate_3/27/2025` FLOAT(53),
	`cat__SaleDate_3/28/2025` FLOAT(53),
	`cat__SaleDate_3/3/2025` FLOAT(53),
	`cat__SaleDate_3/30/2025` FLOAT(53),
	`cat__SaleDate_3/31/2025` FLOAT(53),
	`cat__SaleDate_3/4/2025` FLOAT(53),
	`cat__SaleDate_3/5/2025` FLOAT(53),
	`cat__SaleDate_3/6/2025` FLOAT(53),
	`cat__SaleDate_3/7/2025` FLOAT(53),
	`cat__SaleDate_3/8/2025` FLOAT(53),
	`cat__SaleDate_3/9/2025` FLOAT(53),
	`cat__SaleDate_4/1/2025` FLOAT(53),
	`cat__SaleDate_4/11/2025` FLOAT(53),
	`cat__SaleDate_4/15/2025` FLOAT(53),
	`cat__SaleDate_4/16/2025` FLOAT(53),
	`cat__SaleDate_4/19/2025` FLOAT(53),
	`cat__SaleDate_4/22/2025` FLOAT(53),
	`cat__SaleDate_4/23/2025` FLOAT(53),
	`cat__SaleDate_4/27/2025` FLOAT(53),
	`cat__SaleDate_4/28/2025` FLOAT(53),
	`cat__SaleDate_4/3/2025` FLOAT(53),
	`cat__SaleDate_4/5/2025` FLOAT(53),
	`cat__SaleDate_4/7/2025` FLOAT(53),
	`cat__SaleDate_4/8/2025` FLOAT(53),
	`cat__SaleDate_4/9/2025` FLOAT(53),
	`cat__SaleDate_5/10/2025` FLOAT(53),
	`cat__SaleDate_5/11/2025` FLOAT(53),
	`cat__SaleDate_5/12/2025` FLOAT(53),
	`cat__SaleDate_5/13/2025` FLOAT(53),
	`cat__SaleDate_5/14/2025` FLOAT(53),
	`cat__SaleDate_5/15/2025` FLOAT(53),
	`cat__SaleDate_5/18/2025` FLOAT(53),
	`cat__SaleDate_5/22/2025` FLOAT(53),
	`cat__SaleDate_5/23/2025` FLOAT(53),
	`cat__SaleDate_5/24/2025` FLOAT(53),
	`cat__SaleDate_5/25/2024` FLOAT(53),
	`cat__SaleDate_5/25/2025` FLOAT(53),
	`cat__SaleDate_5/26/2024` FLOAT(53),
	`cat__SaleDate_5/28/2024` FLOAT(53),
	`cat__SaleDate_5/3/2025` FLOAT(53),
	`cat__SaleDate_5/31/2024` FLOAT(53),
	`cat__SaleDate_5/5/2025` FLOAT(53),
	`cat__SaleDate_5/7/2025` FLOAT(53),
	`cat__SaleDate_6/1/2024` FLOAT(53),
	`cat__SaleDate_6/11/2024` FLOAT(53),
	`cat__SaleDate_6/13/2024` FLOAT(53),
	`cat__SaleDate_6/14/2024` FLOAT(53),
	`cat__SaleDate_6/15/2024` FLOAT(53),
	`cat__SaleDate_6/16/2024` FLOAT(53),
	`cat__SaleDate_6/17/2024` FLOAT(53),
	`cat__SaleDate_6/18/2024` FLOAT(53),
	`cat__SaleDate_6/19/2024` FLOAT(53),
	`cat__SaleDate_6/22/2024` FLOAT(53),
	`cat__SaleDate_6/24/2024` FLOAT(53),
	`cat__SaleDate_6/27/2024` FLOAT(53),
	`cat__SaleDate_6/29/2024` FLOAT(53),
	`cat__SaleDate_6/30/2024` FLOAT(53),
	`cat__SaleDate_6/4/2024` FLOAT(53),
	`cat__SaleDate_6/5/2024` FLOAT(53),
	`cat__SaleDate_6/6/2024` FLOAT(53),
	`cat__SaleDate_6/7/2024` FLOAT(53),
	`cat__SaleDate_6/9/2024` FLOAT(53),
	`cat__SaleDate_7/13/2024` FLOAT(53),
	`cat__SaleDate_7/14/2024` FLOAT(53),
	`cat__SaleDate_7/15/2024` FLOAT(53),
	`cat__SaleDate_7/16/2024` FLOAT(53),
	`cat__SaleDate_7/17/2024` FLOAT(53),
	`cat__SaleDate_7/18/2024` FLOAT(53),
	`cat__SaleDate_7/20/2024` FLOAT(53),
	`cat__SaleDate_7/21/2024` FLOAT(53),
	`cat__SaleDate_7/26/2024` FLOAT(53),
	`cat__SaleDate_7/27/2024` FLOAT(53),
	`cat__SaleDate_7/28/2024` FLOAT(53),
	`cat__SaleDate_7/31/2024` FLOAT(53),
	`cat__SaleDate_7/4/2024` FLOAT(53),
	`cat__SaleDate_7/5/2024` FLOAT(53),
	`cat__SaleDate_7/7/2024` FLOAT(53),
	`cat__SaleDate_7/8/2024` FLOAT(53),
	`cat__SaleDate_7/9/2024` FLOAT(53),
	`cat__SaleDate_8/10/2024` FLOAT(53),
	`cat__SaleDate_8/11/2024` FLOAT(53),
	`cat__SaleDate_8/12/2024` FLOAT(53),
	`cat__SaleDate_8/15/2024` FLOAT(53),
	`cat__SaleDate_8/2/2024` FLOAT(53),
	`cat__SaleDate_8/20/2024` FLOAT(53),
	`cat__SaleDate_8/21/2024` FLOAT(53),
	`cat__SaleDate_8/22/2024` FLOAT(53),
	`cat__SaleDate_8/23/2024` FLOAT(53),
	`cat__SaleDate_8/24/2024` FLOAT(53),
	`cat__SaleDate_8/25/2024` FLOAT(53),
	`cat__SaleDate_8/29/2024` FLOAT(53),
	`cat__SaleDate_8/3/2024` FLOAT(53),
	`cat__SaleDate_8/31/2024` FLOAT(53),
	`cat__SaleDate_8/5/2024` FLOAT(53),
	`cat__SaleDate_8/7/2024` FLOAT(53),
	`cat__SaleDate_8/8/2024` FLOAT(53),
	`cat__SaleDate_9/1/2024` FLOAT(53),
	`cat__SaleDate_9/10/2024` FLOAT(53),
	`cat__SaleDate_9/15/2024` FLOAT(53),
	`cat__SaleDate_9/2/2024` FLOAT(53),
	`cat__SaleDate_9/20/2024` FLOAT(53),
	`cat__SaleDate_9/22/2024` FLOAT(53),
	`cat__SaleDate_9/25/2024` FLOAT(53),
	`cat__SaleDate_9/26/2024` FLOAT(53),
	`cat__SaleDate_9/27/2024` FLOAT(53),
	`cat__SaleDate_9/28/2024` FLOAT(53),
	`cat__SaleDate_9/29/2024` FLOAT(53),
	`cat__SaleDate_9/30/2024` FLOAT(53),
	`cat__SaleDate_9/5/2024` FLOAT(53),
	`cat__SaleDate_9/6/2024` FLOAT(53),
	`cat__SaleDate_9/8/2024` FLOAT(53),
	`cat__CurrencyType_OMR` FLOAT(53),
	`cat__CurrencyType_USD` FLOAT(53),
	`cat__CurrencyType_Usd` FLOAT(53),
	`cat__CurrencyType_usd` FLOAT(53),
	`cat__CustomerID_0104ec48-84a4-4638-9ed4-dad335d44c43` FLOAT(53),
	`cat__CustomerID_0403d558-166d-4616-9f3e-98d3d7414d35` FLOAT(53),
	`cat__CustomerID_0437bab5-0dae-422e-9d2d-719091ea2dd9` FLOAT(53),
	`cat__CustomerID_045081fa-0df3-4904-820b-067b4176fb85` FLOAT(53),
	`cat__CustomerID_051e499e-f4d0-4a1e-a595-21fc69b2db45` FLOAT(53),
	`cat__CustomerID_0534e616-cbd9-4eba-82bf-f3903ad76eb9` FLOAT(53),
	`cat__CustomerID_05d39b68-833c-45d0-9af3-c0b3bad43a5c` FLOAT(53),
	`cat__CustomerID_05d75424-135a-40ea-9f43-7297d527e0e0` FLOAT(53),
	`cat__CustomerID_07991be5-0500-4bdc-95bc-a3ee50f4d268` FLOAT(53),
	`cat__CustomerID_0822d2d7-9454-4aa3-95bc-b869d6957852` FLOAT(53),
	`cat__CustomerID_089f6dd7-f901-4521-a02c-eb1bf002c6c7` FLOAT(53),
	`cat__CustomerID_0957271b-9145-4838-a842-c40eddb6a2f6` FLOAT(53),
	`cat__CustomerID_0b4a7550-cb81-475b-b8f0-4d4e9668f7e8` FLOAT(53),
	`cat__CustomerID_0bbb7256-0ad2-4b07-a1b0-cba178732f64` FLOAT(53),
	`cat__CustomerID_0bffb839-d519-494d-8b15-9498de261bd6` FLOAT(53),
	`cat__CustomerID_0dadb5f8-e924-45a5-806b-681dd7aebdea` FLOAT(53),
	`cat__CustomerID_0e57e6c8-d5c5-43fa-919e-3640f6ebba01` FLOAT(53),
	`cat__CustomerID_0ead620f-7c7d-4908-bdda-c73282d77d87` FLOAT(53),
	`cat__CustomerID_0ec24f4e-0f17-4c4c-8b16-7b53519d7ce2` FLOAT(53),
	`cat__CustomerID_103bc58d-7df8-47ae-988b-8738b4b2b050` FLOAT(53),
	`cat__CustomerID_104d0c3e-ccfc-43a7-b3e7-e1c56e986cdd` FLOAT(53),
	`cat__CustomerID_10c8ed7e-bba0-4f05-99b7-c72d90c66aaf` FLOAT(53),
	`cat__CustomerID_10f25bba-5c31-4c70-b065-e050a9b6803a` FLOAT(53),
	`cat__CustomerID_11444ef2-a6c9-42e9-8015-6446784d11a7` FLOAT(53),
	`cat__CustomerID_124ea517-d2c8-4ce0-8b00-fcdcfecff89e` FLOAT(53),
	`cat__CustomerID_134fd311-9094-4aef-9068-78b44f308566` FLOAT(53),
	`cat__CustomerID_13c53f9f-0f5f-492c-8660-001021d8745e` FLOAT(53),
	`cat__CustomerID_14cd77f7-8505-47df-a916-b64aae66ebd2` FLOAT(53),
	`cat__CustomerID_15c37dcb-1c11-4482-b1fc-da11997f0d63` FLOAT(53),
	`cat__CustomerID_15fda73e-7b88-4ad7-85c9-d23d8187e574` FLOAT(53),
	`cat__CustomerID_174cb239-fa9b-49fc-88b8-052996b04e57` FLOAT(53),
	`cat__CustomerID_186c1f4d-5f57-49c0-98c6-e20b6fb281bf` FLOAT(53),
	`cat__CustomerID_1889ca5a-60c6-4da8-8289-4cd9af1f7152` FLOAT(53),
	`cat__CustomerID_1a26ed92-27bd-4be2-8386-45682bfc37f5` FLOAT(53),
	`cat__CustomerID_1a52951e-af95-4353-aed3-385ce0718034` FLOAT(53),
	`cat__CustomerID_1b35b6d8-800e-4972-879e-7235f8840cb3` FLOAT(53),
	`cat__CustomerID_1b626cad-36b0-4cd8-ad1a-5bae2dc27b61` FLOAT(53),
	`cat__CustomerID_1b96902d-270f-44ad-8e0c-b401104aaadb` FLOAT(53),
	`cat__CustomerID_1cc1e21a-c2e5-4616-a5cf-a544eb8a944e` FLOAT(53),
	`cat__CustomerID_1e871ef8-cdf7-4f1b-888f-18086f3dc030` FLOAT(53),
	`cat__CustomerID_1f3219ac-02a6-455b-af6a-87711e6653d1` FLOAT(53),
	`cat__CustomerID_1f696c4e-14d1-40b4-a151-52968f14a663` FLOAT(53),
	`cat__CustomerID_22974c53-2595-473f-bbd2-9f309d5e742f` FLOAT(53),
	`cat__CustomerID_232d1545-43b1-477b-ac22-4b1d25b9f81a` FLOAT(53),
	`cat__CustomerID_2398f009-a88e-4af1-b32e-e9eaf1c0409c` FLOAT(53),
	`cat__CustomerID_23eef71c-2019-4005-b8ac-c849cc15b25a` FLOAT(53),
	`cat__CustomerID_2520f9ed-572a-45a1-96af-3d25c78e1b98` FLOAT(53),
	`cat__CustomerID_259051fc-5e0b-49ed-b0a7-09140016fe70` FLOAT(53),
	`cat__CustomerID_25debb26-0ef4-4c61-a5bc-dc5d74696803` FLOAT(53),
	`cat__CustomerID_267f6422-e359-4bb5-98c9-300691a129bf` FLOAT(53),
	`cat__CustomerID_27055332-a7e4-4ed9-a629-240d59715f87` FLOAT(53),
	`cat__CustomerID_2763a02b-2940-4497-931c-db0ad39455be` FLOAT(53),
	`cat__CustomerID_276d23d2-aa88-4056-9480-acc4c7d6a499` FLOAT(53),
	`cat__CustomerID_27f9e498-f3d9-4c22-a051-8b1bd11e4fad` FLOAT(53),
	`cat__CustomerID_28db4b77-bf17-4d5e-8c81-aa62e84a1b6e` FLOAT(53),
	`cat__CustomerID_2a5e6434-a903-4944-ac8c-aedf06d19d05` FLOAT(53),
	`cat__CustomerID_2ac529aa-c34d-4dcd-9f91-ba34671c0e28` FLOAT(53),
	`cat__CustomerID_2b06b9cf-bfd9-4a6b-809c-ae5d5b4202e1` FLOAT(53),

In [22]:
df["CurrencyType"] = df["CurrencyType"].str.upper()

In [23]:
df_final = df_final.loc[:, ~df_final.columns.duplicated()]

In [24]:
duplicates = df_final.columns[df_final.columns.duplicated()]
print(duplicates)

Index([], dtype='str')

In [25]:
df_final.columns = pd.io.parsers.ParserBase({'names': df_final.columns})._maybe_dedup_names(df_final.columns)

AttributeError: module 'pandas.io.parsers' has no attribute 'ParserBase'

In [26]:
df_final = df_final.loc[:, ~df_final.columns.duplicated()]

In [27]:
print(df_final.shape)
print(df_final.columns)

(300, 669)
Index(['num__Qty', 'num__Unit_Price', 'cat__ProductName_Actually',
       'cat__ProductName_Adams Brush', 'cat__ProductName_Alexander Spray',
       'cat__ProductName_Allen Brush', 'cat__ProductName_Allen Notebook',
       'cat__ProductName_Anderson Lamp', 'cat__ProductName_Arnold Fork',
       'cat__ProductName_Arnold Speaker',
       ...
       'cat__CustomerID_fe6e6f78-bdc3-4deb-a6a2-5f9cd36d2484',
       'cat__CustomerID_feaeae49-e208-4b0b-a4ee-88ab5eb6a7c5',
       'cat__CustomerID_ff1f1a3e-4889-46d4-824e-d92e4c51cf45',
       'cat__CustomerID_ff8159fe-b68a-4bd9-848d-64b836a96eae',
       'cat__StoreID_STORE_A', 'cat__StoreID_Store_A', 'cat__StoreID_store-A',
       'cat__Store_store_sales_1.csv', 'cat__Store_store_sales_2.csv',
       'cat__Store_store_sales_3.csv'],
      dtype='str', length=669)

In [28]:
print(df_final.columns[df_final.columns.duplicated()])

Index([], dtype='str')

In [32]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:1234@localhost/RetailDW")

df_final.to_sql(
    "sales_processed",
    con=engine,
    if_exists="replace",
    index=False
)

OperationalError: (pymysql.err.OperationalError) (1060, "Duplicate column name 'cat__CurrencyType_Usd'")
[SQL:
CREATE TABLE sales_processed (
	`num__Qty` FLOAT(53),
	`num__Unit_Price` FLOAT(53),
	`cat__ProductName_Actually` FLOAT(53),
	`cat__ProductName_Adams Brush` FLOAT(53),
	`cat__ProductName_Alexander Spray` FLOAT(53),
	`cat__ProductName_Allen Brush` FLOAT(53),
	`cat__ProductName_Allen Notebook` FLOAT(53),
	`cat__ProductName_Anderson Lamp` FLOAT(53),
	`cat__ProductName_Arnold Fork` FLOAT(53),
	`cat__ProductName_Arnold Speaker` FLOAT(53),
	`cat__ProductName_Arnold Stick` FLOAT(53),
	`cat__ProductName_Bailey Drill` FLOAT(53),
	`cat__ProductName_Baker Speaker` FLOAT(53),
	`cat__ProductName_Ball Notebook` FLOAT(53),
	`cat__ProductName_Banks Gloves` FLOAT(53),
	`cat__ProductName_Barker Book` FLOAT(53),
	`cat__ProductName_Barker Deodorant` FLOAT(53),
	`cat__ProductName_Barnes Belt` FLOAT(53),
	`cat__ProductName_Barrett Basket` FLOAT(53),
	`cat__ProductName_Bell Glove` FLOAT(53),
	`cat__ProductName_Bennett Lock` FLOAT(53),
	`cat__ProductName_Black` FLOAT(53),
	`cat__ProductName_Boone Balm` FLOAT(53),
	`cat__ProductName_Boone Polish` FLOAT(53),
	`cat__ProductName_Bowen Tire` FLOAT(53),
	`cat__ProductName_Brooks Cap` FLOAT(53),
	`cat__ProductName_Bryant Brush` FLOAT(53),
	`cat__ProductName_Butler Jacket` FLOAT(53),
	`cat__ProductName_Cameron Fan` FLOAT(53),
	`cat__ProductName_Carter Fan` FLOAT(53),
	`cat__ProductName_Case` FLOAT(53),
	`cat__ProductName_Chavez Printer` FLOAT(53),
	`cat__ProductName_Clark Glass` FLOAT(53),
	`cat__ProductName_Cole Disk` FLOAT(53),
	`cat__ProductName_Cole Polish` FLOAT(53),
	`cat__ProductName_Coleman Case` FLOAT(53),
	`cat__ProductName_Collins Rug` FLOAT(53),
	`cat__ProductName_Conner Gel` FLOAT(53),
	`cat__ProductName_Cook Ball` FLOAT(53),
	`cat__ProductName_Cook Tray` FLOAT(53),
	`cat__ProductName_Cooper Knife` FLOAT(53),
	`cat__ProductName_Cox Screw` FLOAT(53),
	`cat__ProductName_Cross Rack` FLOAT(53),
	`cat__ProductName_Daniels Coat` FLOAT(53),
	`cat__ProductName_Dean Screw` FLOAT(53),
	`cat__ProductName_Dean Shelf` FLOAT(53),
	`cat__ProductName_Dennis Mug` FLOAT(53),
	`cat__ProductName_Diaz Soap` FLOAT(53),
	`cat__ProductName_Dixon Marker` FLOAT(53),
	`cat__ProductName_Doyle Grip` FLOAT(53),
	`cat__ProductName_Doyle Powder` FLOAT(53),
	`cat__ProductName_Edwards Mixer` FLOAT(53),
	`cat__ProductName_Evans Tape` FLOAT(53),
	`cat__ProductName_Fisher Clip` FLOAT(53),
	`cat__ProductName_Fisher Cover` FLOAT(53),
	`cat__ProductName_Fleming Tray` FLOAT(53),
	`cat__ProductName_Flores Coat` FLOAT(53),
	`cat__ProductName_Flowers Thread` FLOAT(53),
	`cat__ProductName_Ford Gel` FLOAT(53),
	`cat__ProductName_Foster Hat` FLOAT(53),
	`cat__ProductName_Foster Hook` FLOAT(53),
	`cat__ProductName_Fox Calendar` FLOAT(53),
	`cat__ProductName_Franklin Bag` FLOAT(53),
	`cat__ProductName_Gardner Sheet` FLOAT(53),
	`cat__ProductName_Gibbs Cream` FLOAT(53),
	`cat__ProductName_Gibson Clock` FLOAT(53),
	`cat__ProductName_Gilbert Pad` FLOAT(53),
	`cat__ProductName_Gonzales Sock` FLOAT(53),
	`cat__ProductName_Graham Cleaner` FLOAT(53),
	`cat__ProductName_Gray Tool` FLOAT(53),
	`cat__ProductName_Green Folder` FLOAT(53),
	`cat__ProductName_Gregory Helmet` FLOAT(53),
	`cat__ProductName_Griffin Cream` FLOAT(53),
	`cat__ProductName_Hall Cup` FLOAT(53),
	`cat__ProductName_Hamilton Paste` FLOAT(53),
	`cat__ProductName_Hanson Flashlight` FLOAT(53),
	`cat__ProductName_Harmon Net` FLOAT(53),
	`cat__ProductName_Harper Phone` FLOAT(53),
	`cat__ProductName_Harris Pen` FLOAT(53),
	`cat__ProductName_Hayes Lotion` FLOAT(53),
	`cat__ProductName_Henderson Gear` FLOAT(53),
	`cat__ProductName_Hill Phone` FLOAT(53),
	`cat__ProductName_Holland Nail` FLOAT(53),
	`cat__ProductName_Holmes Book` FLOAT(53),
	`cat__ProductName_Holmes Hook` FLOAT(53),
	`cat__ProductName_Horton Cable` FLOAT(53),
	`cat__ProductName_Howard Can` FLOAT(53),
	`cat__ProductName_Hudson Lamp` FLOAT(53),
	`cat__ProductName_Hughes Strap` FLOAT(53),
	`cat__ProductName_Ingram Booklet` FLOAT(53),
	`cat__ProductName_Jackson Cable` FLOAT(53),
	`cat__ProductName_James Grip` FLOAT(53),
	`cat__ProductName_Jenkins Valve` FLOAT(53),
	`cat__ProductName_Johnson Mirror` FLOAT(53),
	`cat__ProductName_Johnson Screen` FLOAT(53),
	`cat__ProductName_Jordan Bleach` FLOAT(53),
	`cat__ProductName_Kelly String` FLOAT(53),
	`cat__ProductName_Lane Mug` FLOAT(53),
	`cat__ProductName_Larson Rack` FLOAT(53),
	`cat__ProductName_Lee Clock` FLOAT(53),
	`cat__ProductName_Lewis Ruler` FLOAT(53),
	`cat__ProductName_Line` FLOAT(53),
	`cat__ProductName_Lloyd Mixer` FLOAT(53),
	`cat__ProductName_Long Mat` FLOAT(53),
	`cat__ProductName_Marsh Jar` FLOAT(53),
	`cat__ProductName_Martin Charger` FLOAT(53),
	`cat__ProductName_Matthews Plate` FLOAT(53),
	`cat__ProductName_Mitchell Frame` FLOAT(53),
	`cat__ProductName_Moody Net` FLOAT(53),
	`cat__ProductName_Moore Chair` FLOAT(53),
	`cat__ProductName_Morgan Stick` FLOAT(53),
	`cat__ProductName_Morris Bottle` FLOAT(53),
	`cat__ProductName_Morris Tray` FLOAT(53),
	`cat__ProductName_Murphy Dish` FLOAT(53),
	`cat__ProductName_Myers Shampoo` FLOAT(53),
	`cat__ProductName_Nelson Knife` FLOAT(53),
	`cat__ProductName_Newman Rod` FLOAT(53),
	`cat__ProductName_On` FLOAT(53),
	`cat__ProductName_Owens Powder` FLOAT(53),
	`cat__ProductName_Owens Tape` FLOAT(53),
	`cat__ProductName_Page Pen` FLOAT(53),
	`cat__ProductName_Palmer Screen` FLOAT(53),
	`cat__ProductName_Parker Cable` FLOAT(53),
	`cat__ProductName_Patterson Filter` FLOAT(53),
	`cat__ProductName_Perez Board` FLOAT(53),
	`cat__ProductName_Perry Switch` FLOAT(53),
	`cat__ProductName_Peterson Sheet` FLOAT(53),
	`cat__ProductName_Phillips Hook` FLOAT(53),
	`cat__ProductName_Pierce File` FLOAT(53),
	`cat__ProductName_Pierce Plate` FLOAT(53),
	`cat__ProductName_Potter Shield` FLOAT(53),
	`cat__ProductName_Powell Tube` FLOAT(53),
	`cat__ProductName_Price Clip` FLOAT(53),
	`cat__ProductName_Ramirez Bar` FLOAT(53),
	`cat__ProductName_Reed Rack` FLOAT(53),
	`cat__ProductName_Reid Strap` FLOAT(53),
	`cat__ProductName_Richardson Nail` FLOAT(53),
	`cat__ProductName_Rivera Block` FLOAT(53),
	`cat__ProductName_Rivers Lid` FLOAT(53),
	`cat__ProductName_Roberts Ingredient` FLOAT(53),
	`cat__ProductName_Roberts Pen` FLOAT(53),
	`cat__ProductName_Robinson Shelf` FLOAT(53),
	`cat__ProductName_Rodriguez Keyboard` FLOAT(53),
	`cat__ProductName_Rogers Lid` FLOAT(53),
	`cat__ProductName_Ross Cover` FLOAT(53),
	`cat__ProductName_Russell Oil` FLOAT(53),
	`cat__ProductName_Sanchez Book` FLOAT(53),
	`cat__ProductName_Sanders Pin` FLOAT(53),
	`cat__ProductName_Sanderson Spray` FLOAT(53),
	`cat__ProductName_Scott Plate` FLOAT(53),
	`cat__ProductName_Simmons Shorts` FLOAT(53),
	`cat__ProductName_Sims Brush` FLOAT(53),
	`cat__ProductName_Skill` FLOAT(53),
	`cat__ProductName_Smith Bag` FLOAT(53),
	`cat__ProductName_Smith Paper` FLOAT(53),
	`cat__ProductName_Soon` FLOAT(53),
	`cat__ProductName_Spencer Frame` FLOAT(53),
	`cat__ProductName_Stevens Cap` FLOAT(53),
	`cat__ProductName_Stewart Mouse` FLOAT(53),
	`cat__ProductName_Sullivan Wax` FLOAT(53),
	`cat__ProductName_Swanson Bucket` FLOAT(53),
	`cat__ProductName_Taylor Table` FLOAT(53),
	`cat__ProductName_Torres Stand` FLOAT(53),
	`cat__ProductName_Torres Table` FLOAT(53),
	`cat__ProductName_Tucker Helmet` FLOAT(53),
	`cat__ProductName_Turner Pad` FLOAT(53),
	`cat__ProductName_Vang Charger` FLOAT(53),
	`cat__ProductName_Vasquez Bottle` FLOAT(53),
	`cat__ProductName_Wade Charger` FLOAT(53),
	`cat__ProductName_Walker Camera` FLOAT(53),
	`cat__ProductName_Wallace Polish` FLOAT(53),
	`cat__ProductName_Wallace Sheet` FLOAT(53),
	`cat__ProductName_Ward Plug` FLOAT(53),
	`cat__ProductName_Warren Lamp` FLOAT(53),
	`cat__ProductName_Washington Skirt` FLOAT(53),
	`cat__ProductName_Watson Chain` FLOAT(53),
	`cat__ProductName_Welch Mirror` FLOAT(53),
	`cat__ProductName_Welch Spray` FLOAT(53),
	`cat__ProductName_West Shine` FLOAT(53),
	`cat__ProductName_White Monitor` FLOAT(53),
	`cat__ProductName_Williams Bottle` FLOAT(53),
	`cat__ProductName_Wood Tire` FLOAT(53),
	`cat__ProductName_Woods Detergent` FLOAT(53),
	`cat__ProductName_Young Printer` FLOAT(53),
	`cat__SaleDate_1/1/2025` FLOAT(53),
	`cat__SaleDate_1/10/2025` FLOAT(53),
	`cat__SaleDate_1/11/2025` FLOAT(53),
	`cat__SaleDate_1/15/2025` FLOAT(53),
	`cat__SaleDate_1/16/2025` FLOAT(53),
	`cat__SaleDate_1/19/2025` FLOAT(53),
	`cat__SaleDate_1/20/2025` FLOAT(53),
	`cat__SaleDate_1/21/2025` FLOAT(53),
	`cat__SaleDate_1/22/2025` FLOAT(53),
	`cat__SaleDate_1/23/2025` FLOAT(53),
	`cat__SaleDate_1/24/2025` FLOAT(53),
	`cat__SaleDate_1/5/2025` FLOAT(53),
	`cat__SaleDate_1/6/2025` FLOAT(53),
	`cat__SaleDate_1/7/2025` FLOAT(53),
	`cat__SaleDate_1/9/2025` FLOAT(53),
	`cat__SaleDate_10/10/2024` FLOAT(53),
	`cat__SaleDate_10/11/2024` FLOAT(53),
	`cat__SaleDate_10/12/2024` FLOAT(53),
	`cat__SaleDate_10/13/2024` FLOAT(53),
	`cat__SaleDate_10/14/2024` FLOAT(53),
	`cat__SaleDate_10/15/2024` FLOAT(53),
	`cat__SaleDate_10/17/2024` FLOAT(53),
	`cat__SaleDate_10/18/2024` FLOAT(53),
	`cat__SaleDate_10/19/2024` FLOAT(53),
	`cat__SaleDate_10/20/2024` FLOAT(53),
	`cat__SaleDate_10/21/2024` FLOAT(53),
	`cat__SaleDate_10/25/2024` FLOAT(53),
	`cat__SaleDate_10/26/2024` FLOAT(53),
	`cat__SaleDate_10/27/2024` FLOAT(53),
	`cat__SaleDate_10/4/2024` FLOAT(53),
	`cat__SaleDate_10/6/2024` FLOAT(53),
	`cat__SaleDate_10/8/2024` FLOAT(53),
	`cat__SaleDate_11/1/2024` FLOAT(53),
	`cat__SaleDate_11/10/2024` FLOAT(53),
	`cat__SaleDate_11/11/2024` FLOAT(53),
	`cat__SaleDate_11/13/2024` FLOAT(53),
	`cat__SaleDate_11/18/2024` FLOAT(53),
	`cat__SaleDate_11/19/2024` FLOAT(53),
	`cat__SaleDate_11/2/2024` FLOAT(53),
	`cat__SaleDate_11/22/2024` FLOAT(53),
	`cat__SaleDate_11/23/2024` FLOAT(53),
	`cat__SaleDate_11/24/2024` FLOAT(53),
	`cat__SaleDate_11/25/2024` FLOAT(53),
	`cat__SaleDate_11/26/2024` FLOAT(53),
	`cat__SaleDate_11/3/2024` FLOAT(53),
	`cat__SaleDate_11/30/2024` FLOAT(53),
	`cat__SaleDate_11/5/2024` FLOAT(53),
	`cat__SaleDate_11/6/2024` FLOAT(53),
	`cat__SaleDate_11/7/2024` FLOAT(53),
	`cat__SaleDate_11/8/2024` FLOAT(53),
	`cat__SaleDate_11/9/2024` FLOAT(53),
	`cat__SaleDate_12/1/2024` FLOAT(53),
	`cat__SaleDate_12/13/2024` FLOAT(53),
	`cat__SaleDate_12/15/2024` FLOAT(53),
	`cat__SaleDate_12/17/2024` FLOAT(53),
	`cat__SaleDate_12/18/2024` FLOAT(53),
	`cat__SaleDate_12/2/2024` FLOAT(53),
	`cat__SaleDate_12/20/2024` FLOAT(53),
	`cat__SaleDate_12/24/2024` FLOAT(53),
	`cat__SaleDate_12/25/2024` FLOAT(53),
	`cat__SaleDate_12/26/2024` FLOAT(53),
	`cat__SaleDate_12/27/2024` FLOAT(53),
	`cat__SaleDate_12/28/2024` FLOAT(53),
	`cat__SaleDate_12/29/2024` FLOAT(53),
	`cat__SaleDate_12/3/2024` FLOAT(53),
	`cat__SaleDate_12/31/2024` FLOAT(53),
	`cat__SaleDate_12/7/2024` FLOAT(53),
	`cat__SaleDate_12/9/2024` FLOAT(53),
	`cat__SaleDate_2/10/2025` FLOAT(53),
	`cat__SaleDate_2/11/2025` FLOAT(53),
	`cat__SaleDate_2/12/2025` FLOAT(53),
	`cat__SaleDate_2/17/2025` FLOAT(53),
	`cat__SaleDate_2/18/2025` FLOAT(53),
	`cat__SaleDate_2/19/2025` FLOAT(53),
	`cat__SaleDate_2/2/2025` FLOAT(53),
	`cat__SaleDate_2/20/2025` FLOAT(53),
	`cat__SaleDate_2/21/2025` FLOAT(53),
	`cat__SaleDate_2/22/2025` FLOAT(53),
	`cat__SaleDate_2/23/2025` FLOAT(53),
	`cat__SaleDate_2/24/2025` FLOAT(53),
	`cat__SaleDate_2/25/2025` FLOAT(53),
	`cat__SaleDate_2/3/2025` FLOAT(53),
	`cat__SaleDate_2/6/2025` FLOAT(53),
	`cat__SaleDate_2/7/2025` FLOAT(53),
	`cat__SaleDate_2/9/2025` FLOAT(53),
	`cat__SaleDate_3/12/2025` FLOAT(53),
	`cat__SaleDate_3/16/2025` FLOAT(53),
	`cat__SaleDate_3/17/2025` FLOAT(53),
	`cat__SaleDate_3/18/2025` FLOAT(53),
	`cat__SaleDate_3/20/2025` FLOAT(53),
	`cat__SaleDate_3/21/2025` FLOAT(53),
	`cat__SaleDate_3/22/2025` FLOAT(53),
	`cat__SaleDate_3/23/2025` FLOAT(53),
	`cat__SaleDate_3/24/2025` FLOAT(53),
	`cat__SaleDate_3/25/2025` FLOAT(53),
	`cat__SaleDate_3/27/2025` FLOAT(53),
	`cat__SaleDate_3/28/2025` FLOAT(53),
	`cat__SaleDate_3/3/2025` FLOAT(53),
	`cat__SaleDate_3/30/2025` FLOAT(53),
	`cat__SaleDate_3/31/2025` FLOAT(53),
	`cat__SaleDate_3/4/2025` FLOAT(53),
	`cat__SaleDate_3/5/2025` FLOAT(53),
	`cat__SaleDate_3/6/2025` FLOAT(53),
	`cat__SaleDate_3/7/2025` FLOAT(53),
	`cat__SaleDate_3/8/2025` FLOAT(53),
	`cat__SaleDate_3/9/2025` FLOAT(53),
	`cat__SaleDate_4/1/2025` FLOAT(53),
	`cat__SaleDate_4/11/2025` FLOAT(53),
	`cat__SaleDate_4/15/2025` FLOAT(53),
	`cat__SaleDate_4/16/2025` FLOAT(53),
	`cat__SaleDate_4/19/2025` FLOAT(53),
	`cat__SaleDate_4/22/2025` FLOAT(53),
	`cat__SaleDate_4/23/2025` FLOAT(53),
	`cat__SaleDate_4/27/2025` FLOAT(53),
	`cat__SaleDate_4/28/2025` FLOAT(53),
	`cat__SaleDate_4/3/2025` FLOAT(53),
	`cat__SaleDate_4/5/2025` FLOAT(53),
	`cat__SaleDate_4/7/2025` FLOAT(53),
	`cat__SaleDate_4/8/2025` FLOAT(53),
	`cat__SaleDate_4/9/2025` FLOAT(53),
	`cat__SaleDate_5/10/2025` FLOAT(53),
	`cat__SaleDate_5/11/2025` FLOAT(53),
	`cat__SaleDate_5/12/2025` FLOAT(53),
	`cat__SaleDate_5/13/2025` FLOAT(53),
	`cat__SaleDate_5/14/2025` FLOAT(53),
	`cat__SaleDate_5/15/2025` FLOAT(53),
	`cat__SaleDate_5/18/2025` FLOAT(53),
	`cat__SaleDate_5/22/2025` FLOAT(53),
	`cat__SaleDate_5/23/2025` FLOAT(53),
	`cat__SaleDate_5/24/2025` FLOAT(53),
	`cat__SaleDate_5/25/2024` FLOAT(53),
	`cat__SaleDate_5/25/2025` FLOAT(53),
	`cat__SaleDate_5/26/2024` FLOAT(53),
	`cat__SaleDate_5/28/2024` FLOAT(53),
	`cat__SaleDate_5/3/2025` FLOAT(53),
	`cat__SaleDate_5/31/2024` FLOAT(53),
	`cat__SaleDate_5/5/2025` FLOAT(53),
	`cat__SaleDate_5/7/2025` FLOAT(53),
	`cat__SaleDate_6/1/2024` FLOAT(53),
	`cat__SaleDate_6/11/2024` FLOAT(53),
	`cat__SaleDate_6/13/2024` FLOAT(53),
	`cat__SaleDate_6/14/2024` FLOAT(53),
	`cat__SaleDate_6/15/2024` FLOAT(53),
	`cat__SaleDate_6/16/2024` FLOAT(53),
	`cat__SaleDate_6/17/2024` FLOAT(53),
	`cat__SaleDate_6/18/2024` FLOAT(53),
	`cat__SaleDate_6/19/2024` FLOAT(53),
	`cat__SaleDate_6/22/2024` FLOAT(53),
	`cat__SaleDate_6/24/2024` FLOAT(53),
	`cat__SaleDate_6/27/2024` FLOAT(53),
	`cat__SaleDate_6/29/2024` FLOAT(53),
	`cat__SaleDate_6/30/2024` FLOAT(53),
	`cat__SaleDate_6/4/2024` FLOAT(53),
	`cat__SaleDate_6/5/2024` FLOAT(53),
	`cat__SaleDate_6/6/2024` FLOAT(53),
	`cat__SaleDate_6/7/2024` FLOAT(53),
	`cat__SaleDate_6/9/2024` FLOAT(53),
	`cat__SaleDate_7/13/2024` FLOAT(53),
	`cat__SaleDate_7/14/2024` FLOAT(53),
	`cat__SaleDate_7/15/2024` FLOAT(53),
	`cat__SaleDate_7/16/2024` FLOAT(53),
	`cat__SaleDate_7/17/2024` FLOAT(53),
	`cat__SaleDate_7/18/2024` FLOAT(53),
	`cat__SaleDate_7/20/2024` FLOAT(53),
	`cat__SaleDate_7/21/2024` FLOAT(53),
	`cat__SaleDate_7/26/2024` FLOAT(53),
	`cat__SaleDate_7/27/2024` FLOAT(53),
	`cat__SaleDate_7/28/2024` FLOAT(53),
	`cat__SaleDate_7/31/2024` FLOAT(53),
	`cat__SaleDate_7/4/2024` FLOAT(53),
	`cat__SaleDate_7/5/2024` FLOAT(53),
	`cat__SaleDate_7/7/2024` FLOAT(53),
	`cat__SaleDate_7/8/2024` FLOAT(53),
	`cat__SaleDate_7/9/2024` FLOAT(53),
	`cat__SaleDate_8/10/2024` FLOAT(53),
	`cat__SaleDate_8/11/2024` FLOAT(53),
	`cat__SaleDate_8/12/2024` FLOAT(53),
	`cat__SaleDate_8/15/2024` FLOAT(53),
	`cat__SaleDate_8/2/2024` FLOAT(53),
	`cat__SaleDate_8/20/2024` FLOAT(53),
	`cat__SaleDate_8/21/2024` FLOAT(53),
	`cat__SaleDate_8/22/2024` FLOAT(53),
	`cat__SaleDate_8/23/2024` FLOAT(53),
	`cat__SaleDate_8/24/2024` FLOAT(53),
	`cat__SaleDate_8/25/2024` FLOAT(53),
	`cat__SaleDate_8/29/2024` FLOAT(53),
	`cat__SaleDate_8/3/2024` FLOAT(53),
	`cat__SaleDate_8/31/2024` FLOAT(53),
	`cat__SaleDate_8/5/2024` FLOAT(53),
	`cat__SaleDate_8/7/2024` FLOAT(53),
	`cat__SaleDate_8/8/2024` FLOAT(53),
	`cat__SaleDate_9/1/2024` FLOAT(53),
	`cat__SaleDate_9/10/2024` FLOAT(53),
	`cat__SaleDate_9/15/2024` FLOAT(53),
	`cat__SaleDate_9/2/2024` FLOAT(53),
	`cat__SaleDate_9/20/2024` FLOAT(53),
	`cat__SaleDate_9/22/2024` FLOAT(53),
	`cat__SaleDate_9/25/2024` FLOAT(53),
	`cat__SaleDate_9/26/2024` FLOAT(53),
	`cat__SaleDate_9/27/2024` FLOAT(53),
	`cat__SaleDate_9/28/2024` FLOAT(53),
	`cat__SaleDate_9/29/2024` FLOAT(53),
	`cat__SaleDate_9/30/2024` FLOAT(53),
	`cat__SaleDate_9/5/2024` FLOAT(53),
	`cat__SaleDate_9/6/2024` FLOAT(53),
	`cat__SaleDate_9/8/2024` FLOAT(53),
	`cat__CurrencyType_OMR` FLOAT(53),
	`cat__CurrencyType_USD` FLOAT(53),
	`cat__CurrencyType_Usd` FLOAT(53),
	`cat__CurrencyType_usd` FLOAT(53),
	`cat__CustomerID_0104ec48-84a4-4638-9ed4-dad335d44c43` FLOAT(53),
	`cat__CustomerID_0403d558-166d-4616-9f3e-98d3d7414d35` FLOAT(53),
	`cat__CustomerID_0437bab5-0dae-422e-9d2d-719091ea2dd9` FLOAT(53),
	`cat__CustomerID_045081fa-0df3-4904-820b-067b4176fb85` FLOAT(53),
	`cat__CustomerID_051e499e-f4d0-4a1e-a595-21fc69b2db45` FLOAT(53),
	`cat__CustomerID_0534e616-cbd9-4eba-82bf-f3903ad76eb9` FLOAT(53),
	`cat__CustomerID_05d39b68-833c-45d0-9af3-c0b3bad43a5c` FLOAT(53),
	`cat__CustomerID_05d75424-135a-40ea-9f43-7297d527e0e0` FLOAT(53),
	`cat__CustomerID_07991be5-0500-4bdc-95bc-a3ee50f4d268` FLOAT(53),
	`cat__CustomerID_0822d2d7-9454-4aa3-95bc-b869d6957852` FLOAT(53),
	`cat__CustomerID_089f6dd7-f901-4521-a02c-eb1bf002c6c7` FLOAT(53),
	`cat__CustomerID_0957271b-9145-4838-a842-c40eddb6a2f6` FLOAT(53),
	`cat__CustomerID_0b4a7550-cb81-475b-b8f0-4d4e9668f7e8` FLOAT(53),
	`cat__CustomerID_0bbb7256-0ad2-4b07-a1b0-cba178732f64` FLOAT(53),
	`cat__CustomerID_0bffb839-d519-494d-8b15-9498de261bd6` FLOAT(53),
	`cat__CustomerID_0dadb5f8-e924-45a5-806b-681dd7aebdea` FLOAT(53),
	`cat__CustomerID_0e57e6c8-d5c5-43fa-919e-3640f6ebba01` FLOAT(53),
	`cat__CustomerID_0ead620f-7c7d-4908-bdda-c73282d77d87` FLOAT(53),
	`cat__CustomerID_0ec24f4e-0f17-4c4c-8b16-7b53519d7ce2` FLOAT(53),
	`cat__CustomerID_103bc58d-7df8-47ae-988b-8738b4b2b050` FLOAT(53),
	`cat__CustomerID_104d0c3e-ccfc-43a7-b3e7-e1c56e986cdd` FLOAT(53),
	`cat__CustomerID_10c8ed7e-bba0-4f05-99b7-c72d90c66aaf` FLOAT(53),
	`cat__CustomerID_10f25bba-5c31-4c70-b065-e050a9b6803a` FLOAT(53),
	`cat__CustomerID_11444ef2-a6c9-42e9-8015-6446784d11a7` FLOAT(53),
	`cat__CustomerID_124ea517-d2c8-4ce0-8b00-fcdcfecff89e` FLOAT(53),
	`cat__CustomerID_134fd311-9094-4aef-9068-78b44f308566` FLOAT(53),
	`cat__CustomerID_13c53f9f-0f5f-492c-8660-001021d8745e` FLOAT(53),
	`cat__CustomerID_14cd77f7-8505-47df-a916-b64aae66ebd2` FLOAT(53),
	`cat__CustomerID_15c37dcb-1c11-4482-b1fc-da11997f0d63` FLOAT(53),
	`cat__CustomerID_15fda73e-7b88-4ad7-85c9-d23d8187e574` FLOAT(53),
	`cat__CustomerID_174cb239-fa9b-49fc-88b8-052996b04e57` FLOAT(53),
	`cat__CustomerID_186c1f4d-5f57-49c0-98c6-e20b6fb281bf` FLOAT(53),
	`cat__CustomerID_1889ca5a-60c6-4da8-8289-4cd9af1f7152` FLOAT(53),
	`cat__CustomerID_1a26ed92-27bd-4be2-8386-45682bfc37f5` FLOAT(53),
	`cat__CustomerID_1a52951e-af95-4353-aed3-385ce0718034` FLOAT(53),
	`cat__CustomerID_1b35b6d8-800e-4972-879e-7235f8840cb3` FLOAT(53),
	`cat__CustomerID_1b626cad-36b0-4cd8-ad1a-5bae2dc27b61` FLOAT(53),
	`cat__CustomerID_1b96902d-270f-44ad-8e0c-b401104aaadb` FLOAT(53),
	`cat__CustomerID_1cc1e21a-c2e5-4616-a5cf-a544eb8a944e` FLOAT(53),
	`cat__CustomerID_1e871ef8-cdf7-4f1b-888f-18086f3dc030` FLOAT(53),
	`cat__CustomerID_1f3219ac-02a6-455b-af6a-87711e6653d1` FLOAT(53),
	`cat__CustomerID_1f696c4e-14d1-40b4-a151-52968f14a663` FLOAT(53),
	`cat__CustomerID_22974c53-2595-473f-bbd2-9f309d5e742f` FLOAT(53),
	`cat__CustomerID_232d1545-43b1-477b-ac22-4b1d25b9f81a` FLOAT(53),
	`cat__CustomerID_2398f009-a88e-4af1-b32e-e9eaf1c0409c` FLOAT(53),
	`cat__CustomerID_23eef71c-2019-4005-b8ac-c849cc15b25a` FLOAT(53),
	`cat__CustomerID_2520f9ed-572a-45a1-96af-3d25c78e1b98` FLOAT(53),
	`cat__CustomerID_259051fc-5e0b-49ed-b0a7-09140016fe70` FLOAT(53),
	`cat__CustomerID_25debb26-0ef4-4c61-a5bc-dc5d74696803` FLOAT(53),
	`cat__CustomerID_267f6422-e359-4bb5-98c9-300691a129bf` FLOAT(53),
	`cat__CustomerID_27055332-a7e4-4ed9-a629-240d59715f87` FLOAT(53),
	`cat__CustomerID_2763a02b-2940-4497-931c-db0ad39455be` FLOAT(53),
	`cat__CustomerID_276d23d2-aa88-4056-9480-acc4c7d6a499` FLOAT(53),
	`cat__CustomerID_27f9e498-f3d9-4c22-a051-8b1bd11e4fad` FLOAT(53),
	`cat__CustomerID_28db4b77-bf17-4d5e-8c81-aa62e84a1b6e` FLOAT(53),
	`cat__CustomerID_2a5e6434-a903-4944-ac8c-aedf06d19d05` FLOAT(53),
	`cat__CustomerID_2ac529aa-c34d-4dcd-9f91-ba34671c0e28` FLOAT(53),
	`cat__CustomerID_2b06b9cf-bfd9-4a6b-809c-ae5d5b4202e1` FLOAT(53),

In [30]:
df_final = df_final.fillna(0)

In [33]:
df_final = df_final.loc[:, ~df_final.columns.duplicated(keep='first')]
df_final.columns = df_final.columns.astype(str)

In [34]:
from collections import Counter

cols = pd.Index(df_final.columns)
counts = Counter(cols)

new_cols = []
seen = {}

for c in cols:
    if c not in seen:
        seen[c] = 0
        new_cols.append(c)
    else:
        seen[c] += 1
        new_cols.append(f"{c}_{seen[c]}")

df_final.columns = new_cols

In [35]:
with engine.connect() as conn:
    conn.execute("DROP TABLE IF EXISTS sales_processed")

ObjectNotExecutableError: Not an executable object: 'DROP TABLE IF EXISTS sales_processed'

In [36]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS sales_processed"))
    conn.commit()

In [37]:
df_final.to_sql(
    "sales_processed",
    con=engine,
    if_exists="replace",
    index=False
)

OperationalError: (pymysql.err.OperationalError) (1060, "Duplicate column name 'cat__CurrencyType_Usd'")
[SQL:
CREATE TABLE sales_processed (
	`num__Qty` FLOAT(53),
	`num__Unit_Price` FLOAT(53),
	`cat__ProductName_Actually` FLOAT(53),
	`cat__ProductName_Adams Brush` FLOAT(53),
	`cat__ProductName_Alexander Spray` FLOAT(53),
	`cat__ProductName_Allen Brush` FLOAT(53),
	`cat__ProductName_Allen Notebook` FLOAT(53),
	`cat__ProductName_Anderson Lamp` FLOAT(53),
	`cat__ProductName_Arnold Fork` FLOAT(53),
	`cat__ProductName_Arnold Speaker` FLOAT(53),
	`cat__ProductName_Arnold Stick` FLOAT(53),
	`cat__ProductName_Bailey Drill` FLOAT(53),
	`cat__ProductName_Baker Speaker` FLOAT(53),
	`cat__ProductName_Ball Notebook` FLOAT(53),
	`cat__ProductName_Banks Gloves` FLOAT(53),
	`cat__ProductName_Barker Book` FLOAT(53),
	`cat__ProductName_Barker Deodorant` FLOAT(53),
	`cat__ProductName_Barnes Belt` FLOAT(53),
	`cat__ProductName_Barrett Basket` FLOAT(53),
	`cat__ProductName_Bell Glove` FLOAT(53),
	`cat__ProductName_Bennett Lock` FLOAT(53),
	`cat__ProductName_Black` FLOAT(53),
	`cat__ProductName_Boone Balm` FLOAT(53),
	`cat__ProductName_Boone Polish` FLOAT(53),
	`cat__ProductName_Bowen Tire` FLOAT(53),
	`cat__ProductName_Brooks Cap` FLOAT(53),
	`cat__ProductName_Bryant Brush` FLOAT(53),
	`cat__ProductName_Butler Jacket` FLOAT(53),
	`cat__ProductName_Cameron Fan` FLOAT(53),
	`cat__ProductName_Carter Fan` FLOAT(53),
	`cat__ProductName_Case` FLOAT(53),
	`cat__ProductName_Chavez Printer` FLOAT(53),
	`cat__ProductName_Clark Glass` FLOAT(53),
	`cat__ProductName_Cole Disk` FLOAT(53),
	`cat__ProductName_Cole Polish` FLOAT(53),
	`cat__ProductName_Coleman Case` FLOAT(53),
	`cat__ProductName_Collins Rug` FLOAT(53),
	`cat__ProductName_Conner Gel` FLOAT(53),
	`cat__ProductName_Cook Ball` FLOAT(53),
	`cat__ProductName_Cook Tray` FLOAT(53),
	`cat__ProductName_Cooper Knife` FLOAT(53),
	`cat__ProductName_Cox Screw` FLOAT(53),
	`cat__ProductName_Cross Rack` FLOAT(53),
	`cat__ProductName_Daniels Coat` FLOAT(53),
	`cat__ProductName_Dean Screw` FLOAT(53),
	`cat__ProductName_Dean Shelf` FLOAT(53),
	`cat__ProductName_Dennis Mug` FLOAT(53),
	`cat__ProductName_Diaz Soap` FLOAT(53),
	`cat__ProductName_Dixon Marker` FLOAT(53),
	`cat__ProductName_Doyle Grip` FLOAT(53),
	`cat__ProductName_Doyle Powder` FLOAT(53),
	`cat__ProductName_Edwards Mixer` FLOAT(53),
	`cat__ProductName_Evans Tape` FLOAT(53),
	`cat__ProductName_Fisher Clip` FLOAT(53),
	`cat__ProductName_Fisher Cover` FLOAT(53),
	`cat__ProductName_Fleming Tray` FLOAT(53),
	`cat__ProductName_Flores Coat` FLOAT(53),
	`cat__ProductName_Flowers Thread` FLOAT(53),
	`cat__ProductName_Ford Gel` FLOAT(53),
	`cat__ProductName_Foster Hat` FLOAT(53),
	`cat__ProductName_Foster Hook` FLOAT(53),
	`cat__ProductName_Fox Calendar` FLOAT(53),
	`cat__ProductName_Franklin Bag` FLOAT(53),
	`cat__ProductName_Gardner Sheet` FLOAT(53),
	`cat__ProductName_Gibbs Cream` FLOAT(53),
	`cat__ProductName_Gibson Clock` FLOAT(53),
	`cat__ProductName_Gilbert Pad` FLOAT(53),
	`cat__ProductName_Gonzales Sock` FLOAT(53),
	`cat__ProductName_Graham Cleaner` FLOAT(53),
	`cat__ProductName_Gray Tool` FLOAT(53),
	`cat__ProductName_Green Folder` FLOAT(53),
	`cat__ProductName_Gregory Helmet` FLOAT(53),
	`cat__ProductName_Griffin Cream` FLOAT(53),
	`cat__ProductName_Hall Cup` FLOAT(53),
	`cat__ProductName_Hamilton Paste` FLOAT(53),
	`cat__ProductName_Hanson Flashlight` FLOAT(53),
	`cat__ProductName_Harmon Net` FLOAT(53),
	`cat__ProductName_Harper Phone` FLOAT(53),
	`cat__ProductName_Harris Pen` FLOAT(53),
	`cat__ProductName_Hayes Lotion` FLOAT(53),
	`cat__ProductName_Henderson Gear` FLOAT(53),
	`cat__ProductName_Hill Phone` FLOAT(53),
	`cat__ProductName_Holland Nail` FLOAT(53),
	`cat__ProductName_Holmes Book` FLOAT(53),
	`cat__ProductName_Holmes Hook` FLOAT(53),
	`cat__ProductName_Horton Cable` FLOAT(53),
	`cat__ProductName_Howard Can` FLOAT(53),
	`cat__ProductName_Hudson Lamp` FLOAT(53),
	`cat__ProductName_Hughes Strap` FLOAT(53),
	`cat__ProductName_Ingram Booklet` FLOAT(53),
	`cat__ProductName_Jackson Cable` FLOAT(53),
	`cat__ProductName_James Grip` FLOAT(53),
	`cat__ProductName_Jenkins Valve` FLOAT(53),
	`cat__ProductName_Johnson Mirror` FLOAT(53),
	`cat__ProductName_Johnson Screen` FLOAT(53),
	`cat__ProductName_Jordan Bleach` FLOAT(53),
	`cat__ProductName_Kelly String` FLOAT(53),
	`cat__ProductName_Lane Mug` FLOAT(53),
	`cat__ProductName_Larson Rack` FLOAT(53),
	`cat__ProductName_Lee Clock` FLOAT(53),
	`cat__ProductName_Lewis Ruler` FLOAT(53),
	`cat__ProductName_Line` FLOAT(53),
	`cat__ProductName_Lloyd Mixer` FLOAT(53),
	`cat__ProductName_Long Mat` FLOAT(53),
	`cat__ProductName_Marsh Jar` FLOAT(53),
	`cat__ProductName_Martin Charger` FLOAT(53),
	`cat__ProductName_Matthews Plate` FLOAT(53),
	`cat__ProductName_Mitchell Frame` FLOAT(53),
	`cat__ProductName_Moody Net` FLOAT(53),
	`cat__ProductName_Moore Chair` FLOAT(53),
	`cat__ProductName_Morgan Stick` FLOAT(53),
	`cat__ProductName_Morris Bottle` FLOAT(53),
	`cat__ProductName_Morris Tray` FLOAT(53),
	`cat__ProductName_Murphy Dish` FLOAT(53),
	`cat__ProductName_Myers Shampoo` FLOAT(53),
	`cat__ProductName_Nelson Knife` FLOAT(53),
	`cat__ProductName_Newman Rod` FLOAT(53),
	`cat__ProductName_On` FLOAT(53),
	`cat__ProductName_Owens Powder` FLOAT(53),
	`cat__ProductName_Owens Tape` FLOAT(53),
	`cat__ProductName_Page Pen` FLOAT(53),
	`cat__ProductName_Palmer Screen` FLOAT(53),
	`cat__ProductName_Parker Cable` FLOAT(53),
	`cat__ProductName_Patterson Filter` FLOAT(53),
	`cat__ProductName_Perez Board` FLOAT(53),
	`cat__ProductName_Perry Switch` FLOAT(53),
	`cat__ProductName_Peterson Sheet` FLOAT(53),
	`cat__ProductName_Phillips Hook` FLOAT(53),
	`cat__ProductName_Pierce File` FLOAT(53),
	`cat__ProductName_Pierce Plate` FLOAT(53),
	`cat__ProductName_Potter Shield` FLOAT(53),
	`cat__ProductName_Powell Tube` FLOAT(53),
	`cat__ProductName_Price Clip` FLOAT(53),
	`cat__ProductName_Ramirez Bar` FLOAT(53),
	`cat__ProductName_Reed Rack` FLOAT(53),
	`cat__ProductName_Reid Strap` FLOAT(53),
	`cat__ProductName_Richardson Nail` FLOAT(53),
	`cat__ProductName_Rivera Block` FLOAT(53),
	`cat__ProductName_Rivers Lid` FLOAT(53),
	`cat__ProductName_Roberts Ingredient` FLOAT(53),
	`cat__ProductName_Roberts Pen` FLOAT(53),
	`cat__ProductName_Robinson Shelf` FLOAT(53),
	`cat__ProductName_Rodriguez Keyboard` FLOAT(53),
	`cat__ProductName_Rogers Lid` FLOAT(53),
	`cat__ProductName_Ross Cover` FLOAT(53),
	`cat__ProductName_Russell Oil` FLOAT(53),
	`cat__ProductName_Sanchez Book` FLOAT(53),
	`cat__ProductName_Sanders Pin` FLOAT(53),
	`cat__ProductName_Sanderson Spray` FLOAT(53),
	`cat__ProductName_Scott Plate` FLOAT(53),
	`cat__ProductName_Simmons Shorts` FLOAT(53),
	`cat__ProductName_Sims Brush` FLOAT(53),
	`cat__ProductName_Skill` FLOAT(53),
	`cat__ProductName_Smith Bag` FLOAT(53),
	`cat__ProductName_Smith Paper` FLOAT(53),
	`cat__ProductName_Soon` FLOAT(53),
	`cat__ProductName_Spencer Frame` FLOAT(53),
	`cat__ProductName_Stevens Cap` FLOAT(53),
	`cat__ProductName_Stewart Mouse` FLOAT(53),
	`cat__ProductName_Sullivan Wax` FLOAT(53),
	`cat__ProductName_Swanson Bucket` FLOAT(53),
	`cat__ProductName_Taylor Table` FLOAT(53),
	`cat__ProductName_Torres Stand` FLOAT(53),
	`cat__ProductName_Torres Table` FLOAT(53),
	`cat__ProductName_Tucker Helmet` FLOAT(53),
	`cat__ProductName_Turner Pad` FLOAT(53),
	`cat__ProductName_Vang Charger` FLOAT(53),
	`cat__ProductName_Vasquez Bottle` FLOAT(53),
	`cat__ProductName_Wade Charger` FLOAT(53),
	`cat__ProductName_Walker Camera` FLOAT(53),
	`cat__ProductName_Wallace Polish` FLOAT(53),
	`cat__ProductName_Wallace Sheet` FLOAT(53),
	`cat__ProductName_Ward Plug` FLOAT(53),
	`cat__ProductName_Warren Lamp` FLOAT(53),
	`cat__ProductName_Washington Skirt` FLOAT(53),
	`cat__ProductName_Watson Chain` FLOAT(53),
	`cat__ProductName_Welch Mirror` FLOAT(53),
	`cat__ProductName_Welch Spray` FLOAT(53),
	`cat__ProductName_West Shine` FLOAT(53),
	`cat__ProductName_White Monitor` FLOAT(53),
	`cat__ProductName_Williams Bottle` FLOAT(53),
	`cat__ProductName_Wood Tire` FLOAT(53),
	`cat__ProductName_Woods Detergent` FLOAT(53),
	`cat__ProductName_Young Printer` FLOAT(53),
	`cat__SaleDate_1/1/2025` FLOAT(53),
	`cat__SaleDate_1/10/2025` FLOAT(53),
	`cat__SaleDate_1/11/2025` FLOAT(53),
	`cat__SaleDate_1/15/2025` FLOAT(53),
	`cat__SaleDate_1/16/2025` FLOAT(53),
	`cat__SaleDate_1/19/2025` FLOAT(53),
	`cat__SaleDate_1/20/2025` FLOAT(53),
	`cat__SaleDate_1/21/2025` FLOAT(53),
	`cat__SaleDate_1/22/2025` FLOAT(53),
	`cat__SaleDate_1/23/2025` FLOAT(53),
	`cat__SaleDate_1/24/2025` FLOAT(53),
	`cat__SaleDate_1/5/2025` FLOAT(53),
	`cat__SaleDate_1/6/2025` FLOAT(53),
	`cat__SaleDate_1/7/2025` FLOAT(53),
	`cat__SaleDate_1/9/2025` FLOAT(53),
	`cat__SaleDate_10/10/2024` FLOAT(53),
	`cat__SaleDate_10/11/2024` FLOAT(53),
	`cat__SaleDate_10/12/2024` FLOAT(53),
	`cat__SaleDate_10/13/2024` FLOAT(53),
	`cat__SaleDate_10/14/2024` FLOAT(53),
	`cat__SaleDate_10/15/2024` FLOAT(53),
	`cat__SaleDate_10/17/2024` FLOAT(53),
	`cat__SaleDate_10/18/2024` FLOAT(53),
	`cat__SaleDate_10/19/2024` FLOAT(53),
	`cat__SaleDate_10/20/2024` FLOAT(53),
	`cat__SaleDate_10/21/2024` FLOAT(53),
	`cat__SaleDate_10/25/2024` FLOAT(53),
	`cat__SaleDate_10/26/2024` FLOAT(53),
	`cat__SaleDate_10/27/2024` FLOAT(53),
	`cat__SaleDate_10/4/2024` FLOAT(53),
	`cat__SaleDate_10/6/2024` FLOAT(53),
	`cat__SaleDate_10/8/2024` FLOAT(53),
	`cat__SaleDate_11/1/2024` FLOAT(53),
	`cat__SaleDate_11/10/2024` FLOAT(53),
	`cat__SaleDate_11/11/2024` FLOAT(53),
	`cat__SaleDate_11/13/2024` FLOAT(53),
	`cat__SaleDate_11/18/2024` FLOAT(53),
	`cat__SaleDate_11/19/2024` FLOAT(53),
	`cat__SaleDate_11/2/2024` FLOAT(53),
	`cat__SaleDate_11/22/2024` FLOAT(53),
	`cat__SaleDate_11/23/2024` FLOAT(53),
	`cat__SaleDate_11/24/2024` FLOAT(53),
	`cat__SaleDate_11/25/2024` FLOAT(53),
	`cat__SaleDate_11/26/2024` FLOAT(53),
	`cat__SaleDate_11/3/2024` FLOAT(53),
	`cat__SaleDate_11/30/2024` FLOAT(53),
	`cat__SaleDate_11/5/2024` FLOAT(53),
	`cat__SaleDate_11/6/2024` FLOAT(53),
	`cat__SaleDate_11/7/2024` FLOAT(53),
	`cat__SaleDate_11/8/2024` FLOAT(53),
	`cat__SaleDate_11/9/2024` FLOAT(53),
	`cat__SaleDate_12/1/2024` FLOAT(53),
	`cat__SaleDate_12/13/2024` FLOAT(53),
	`cat__SaleDate_12/15/2024` FLOAT(53),
	`cat__SaleDate_12/17/2024` FLOAT(53),
	`cat__SaleDate_12/18/2024` FLOAT(53),
	`cat__SaleDate_12/2/2024` FLOAT(53),
	`cat__SaleDate_12/20/2024` FLOAT(53),
	`cat__SaleDate_12/24/2024` FLOAT(53),
	`cat__SaleDate_12/25/2024` FLOAT(53),
	`cat__SaleDate_12/26/2024` FLOAT(53),
	`cat__SaleDate_12/27/2024` FLOAT(53),
	`cat__SaleDate_12/28/2024` FLOAT(53),
	`cat__SaleDate_12/29/2024` FLOAT(53),
	`cat__SaleDate_12/3/2024` FLOAT(53),
	`cat__SaleDate_12/31/2024` FLOAT(53),
	`cat__SaleDate_12/7/2024` FLOAT(53),
	`cat__SaleDate_12/9/2024` FLOAT(53),
	`cat__SaleDate_2/10/2025` FLOAT(53),
	`cat__SaleDate_2/11/2025` FLOAT(53),
	`cat__SaleDate_2/12/2025` FLOAT(53),
	`cat__SaleDate_2/17/2025` FLOAT(53),
	`cat__SaleDate_2/18/2025` FLOAT(53),
	`cat__SaleDate_2/19/2025` FLOAT(53),
	`cat__SaleDate_2/2/2025` FLOAT(53),
	`cat__SaleDate_2/20/2025` FLOAT(53),
	`cat__SaleDate_2/21/2025` FLOAT(53),
	`cat__SaleDate_2/22/2025` FLOAT(53),
	`cat__SaleDate_2/23/2025` FLOAT(53),
	`cat__SaleDate_2/24/2025` FLOAT(53),
	`cat__SaleDate_2/25/2025` FLOAT(53),
	`cat__SaleDate_2/3/2025` FLOAT(53),
	`cat__SaleDate_2/6/2025` FLOAT(53),
	`cat__SaleDate_2/7/2025` FLOAT(53),
	`cat__SaleDate_2/9/2025` FLOAT(53),
	`cat__SaleDate_3/12/2025` FLOAT(53),
	`cat__SaleDate_3/16/2025` FLOAT(53),
	`cat__SaleDate_3/17/2025` FLOAT(53),
	`cat__SaleDate_3/18/2025` FLOAT(53),
	`cat__SaleDate_3/20/2025` FLOAT(53),
	`cat__SaleDate_3/21/2025` FLOAT(53),
	`cat__SaleDate_3/22/2025` FLOAT(53),
	`cat__SaleDate_3/23/2025` FLOAT(53),
	`cat__SaleDate_3/24/2025` FLOAT(53),
	`cat__SaleDate_3/25/2025` FLOAT(53),
	`cat__SaleDate_3/27/2025` FLOAT(53),
	`cat__SaleDate_3/28/2025` FLOAT(53),
	`cat__SaleDate_3/3/2025` FLOAT(53),
	`cat__SaleDate_3/30/2025` FLOAT(53),
	`cat__SaleDate_3/31/2025` FLOAT(53),
	`cat__SaleDate_3/4/2025` FLOAT(53),
	`cat__SaleDate_3/5/2025` FLOAT(53),
	`cat__SaleDate_3/6/2025` FLOAT(53),
	`cat__SaleDate_3/7/2025` FLOAT(53),
	`cat__SaleDate_3/8/2025` FLOAT(53),
	`cat__SaleDate_3/9/2025` FLOAT(53),
	`cat__SaleDate_4/1/2025` FLOAT(53),
	`cat__SaleDate_4/11/2025` FLOAT(53),
	`cat__SaleDate_4/15/2025` FLOAT(53),
	`cat__SaleDate_4/16/2025` FLOAT(53),
	`cat__SaleDate_4/19/2025` FLOAT(53),
	`cat__SaleDate_4/22/2025` FLOAT(53),
	`cat__SaleDate_4/23/2025` FLOAT(53),
	`cat__SaleDate_4/27/2025` FLOAT(53),
	`cat__SaleDate_4/28/2025` FLOAT(53),
	`cat__SaleDate_4/3/2025` FLOAT(53),
	`cat__SaleDate_4/5/2025` FLOAT(53),
	`cat__SaleDate_4/7/2025` FLOAT(53),
	`cat__SaleDate_4/8/2025` FLOAT(53),
	`cat__SaleDate_4/9/2025` FLOAT(53),
	`cat__SaleDate_5/10/2025` FLOAT(53),
	`cat__SaleDate_5/11/2025` FLOAT(53),
	`cat__SaleDate_5/12/2025` FLOAT(53),
	`cat__SaleDate_5/13/2025` FLOAT(53),
	`cat__SaleDate_5/14/2025` FLOAT(53),
	`cat__SaleDate_5/15/2025` FLOAT(53),
	`cat__SaleDate_5/18/2025` FLOAT(53),
	`cat__SaleDate_5/22/2025` FLOAT(53),
	`cat__SaleDate_5/23/2025` FLOAT(53),
	`cat__SaleDate_5/24/2025` FLOAT(53),
	`cat__SaleDate_5/25/2024` FLOAT(53),
	`cat__SaleDate_5/25/2025` FLOAT(53),
	`cat__SaleDate_5/26/2024` FLOAT(53),
	`cat__SaleDate_5/28/2024` FLOAT(53),
	`cat__SaleDate_5/3/2025` FLOAT(53),
	`cat__SaleDate_5/31/2024` FLOAT(53),
	`cat__SaleDate_5/5/2025` FLOAT(53),
	`cat__SaleDate_5/7/2025` FLOAT(53),
	`cat__SaleDate_6/1/2024` FLOAT(53),
	`cat__SaleDate_6/11/2024` FLOAT(53),
	`cat__SaleDate_6/13/2024` FLOAT(53),
	`cat__SaleDate_6/14/2024` FLOAT(53),
	`cat__SaleDate_6/15/2024` FLOAT(53),
	`cat__SaleDate_6/16/2024` FLOAT(53),
	`cat__SaleDate_6/17/2024` FLOAT(53),
	`cat__SaleDate_6/18/2024` FLOAT(53),
	`cat__SaleDate_6/19/2024` FLOAT(53),
	`cat__SaleDate_6/22/2024` FLOAT(53),
	`cat__SaleDate_6/24/2024` FLOAT(53),
	`cat__SaleDate_6/27/2024` FLOAT(53),
	`cat__SaleDate_6/29/2024` FLOAT(53),
	`cat__SaleDate_6/30/2024` FLOAT(53),
	`cat__SaleDate_6/4/2024` FLOAT(53),
	`cat__SaleDate_6/5/2024` FLOAT(53),
	`cat__SaleDate_6/6/2024` FLOAT(53),
	`cat__SaleDate_6/7/2024` FLOAT(53),
	`cat__SaleDate_6/9/2024` FLOAT(53),
	`cat__SaleDate_7/13/2024` FLOAT(53),
	`cat__SaleDate_7/14/2024` FLOAT(53),
	`cat__SaleDate_7/15/2024` FLOAT(53),
	`cat__SaleDate_7/16/2024` FLOAT(53),
	`cat__SaleDate_7/17/2024` FLOAT(53),
	`cat__SaleDate_7/18/2024` FLOAT(53),
	`cat__SaleDate_7/20/2024` FLOAT(53),
	`cat__SaleDate_7/21/2024` FLOAT(53),
	`cat__SaleDate_7/26/2024` FLOAT(53),
	`cat__SaleDate_7/27/2024` FLOAT(53),
	`cat__SaleDate_7/28/2024` FLOAT(53),
	`cat__SaleDate_7/31/2024` FLOAT(53),
	`cat__SaleDate_7/4/2024` FLOAT(53),
	`cat__SaleDate_7/5/2024` FLOAT(53),
	`cat__SaleDate_7/7/2024` FLOAT(53),
	`cat__SaleDate_7/8/2024` FLOAT(53),
	`cat__SaleDate_7/9/2024` FLOAT(53),
	`cat__SaleDate_8/10/2024` FLOAT(53),
	`cat__SaleDate_8/11/2024` FLOAT(53),
	`cat__SaleDate_8/12/2024` FLOAT(53),
	`cat__SaleDate_8/15/2024` FLOAT(53),
	`cat__SaleDate_8/2/2024` FLOAT(53),
	`cat__SaleDate_8/20/2024` FLOAT(53),
	`cat__SaleDate_8/21/2024` FLOAT(53),
	`cat__SaleDate_8/22/2024` FLOAT(53),
	`cat__SaleDate_8/23/2024` FLOAT(53),
	`cat__SaleDate_8/24/2024` FLOAT(53),
	`cat__SaleDate_8/25/2024` FLOAT(53),
	`cat__SaleDate_8/29/2024` FLOAT(53),
	`cat__SaleDate_8/3/2024` FLOAT(53),
	`cat__SaleDate_8/31/2024` FLOAT(53),
	`cat__SaleDate_8/5/2024` FLOAT(53),
	`cat__SaleDate_8/7/2024` FLOAT(53),
	`cat__SaleDate_8/8/2024` FLOAT(53),
	`cat__SaleDate_9/1/2024` FLOAT(53),
	`cat__SaleDate_9/10/2024` FLOAT(53),
	`cat__SaleDate_9/15/2024` FLOAT(53),
	`cat__SaleDate_9/2/2024` FLOAT(53),
	`cat__SaleDate_9/20/2024` FLOAT(53),
	`cat__SaleDate_9/22/2024` FLOAT(53),
	`cat__SaleDate_9/25/2024` FLOAT(53),
	`cat__SaleDate_9/26/2024` FLOAT(53),
	`cat__SaleDate_9/27/2024` FLOAT(53),
	`cat__SaleDate_9/28/2024` FLOAT(53),
	`cat__SaleDate_9/29/2024` FLOAT(53),
	`cat__SaleDate_9/30/2024` FLOAT(53),
	`cat__SaleDate_9/5/2024` FLOAT(53),
	`cat__SaleDate_9/6/2024` FLOAT(53),
	`cat__SaleDate_9/8/2024` FLOAT(53),
	`cat__CurrencyType_OMR` FLOAT(53),
	`cat__CurrencyType_USD` FLOAT(53),
	`cat__CurrencyType_Usd` FLOAT(53),
	`cat__CurrencyType_usd` FLOAT(53),
	`cat__CustomerID_0104ec48-84a4-4638-9ed4-dad335d44c43` FLOAT(53),
	`cat__CustomerID_0403d558-166d-4616-9f3e-98d3d7414d35` FLOAT(53),
	`cat__CustomerID_0437bab5-0dae-422e-9d2d-719091ea2dd9` FLOAT(53),
	`cat__CustomerID_045081fa-0df3-4904-820b-067b4176fb85` FLOAT(53),
	`cat__CustomerID_051e499e-f4d0-4a1e-a595-21fc69b2db45` FLOAT(53),
	`cat__CustomerID_0534e616-cbd9-4eba-82bf-f3903ad76eb9` FLOAT(53),
	`cat__CustomerID_05d39b68-833c-45d0-9af3-c0b3bad43a5c` FLOAT(53),
	`cat__CustomerID_05d75424-135a-40ea-9f43-7297d527e0e0` FLOAT(53),
	`cat__CustomerID_07991be5-0500-4bdc-95bc-a3ee50f4d268` FLOAT(53),
	`cat__CustomerID_0822d2d7-9454-4aa3-95bc-b869d6957852` FLOAT(53),
	`cat__CustomerID_089f6dd7-f901-4521-a02c-eb1bf002c6c7` FLOAT(53),
	`cat__CustomerID_0957271b-9145-4838-a842-c40eddb6a2f6` FLOAT(53),
	`cat__CustomerID_0b4a7550-cb81-475b-b8f0-4d4e9668f7e8` FLOAT(53),
	`cat__CustomerID_0bbb7256-0ad2-4b07-a1b0-cba178732f64` FLOAT(53),
	`cat__CustomerID_0bffb839-d519-494d-8b15-9498de261bd6` FLOAT(53),
	`cat__CustomerID_0dadb5f8-e924-45a5-806b-681dd7aebdea` FLOAT(53),
	`cat__CustomerID_0e57e6c8-d5c5-43fa-919e-3640f6ebba01` FLOAT(53),
	`cat__CustomerID_0ead620f-7c7d-4908-bdda-c73282d77d87` FLOAT(53),
	`cat__CustomerID_0ec24f4e-0f17-4c4c-8b16-7b53519d7ce2` FLOAT(53),
	`cat__CustomerID_103bc58d-7df8-47ae-988b-8738b4b2b050` FLOAT(53),
	`cat__CustomerID_104d0c3e-ccfc-43a7-b3e7-e1c56e986cdd` FLOAT(53),
	`cat__CustomerID_10c8ed7e-bba0-4f05-99b7-c72d90c66aaf` FLOAT(53),
	`cat__CustomerID_10f25bba-5c31-4c70-b065-e050a9b6803a` FLOAT(53),
	`cat__CustomerID_11444ef2-a6c9-42e9-8015-6446784d11a7` FLOAT(53),
	`cat__CustomerID_124ea517-d2c8-4ce0-8b00-fcdcfecff89e` FLOAT(53),
	`cat__CustomerID_134fd311-9094-4aef-9068-78b44f308566` FLOAT(53),
	`cat__CustomerID_13c53f9f-0f5f-492c-8660-001021d8745e` FLOAT(53),
	`cat__CustomerID_14cd77f7-8505-47df-a916-b64aae66ebd2` FLOAT(53),
	`cat__CustomerID_15c37dcb-1c11-4482-b1fc-da11997f0d63` FLOAT(53),
	`cat__CustomerID_15fda73e-7b88-4ad7-85c9-d23d8187e574` FLOAT(53),
	`cat__CustomerID_174cb239-fa9b-49fc-88b8-052996b04e57` FLOAT(53),
	`cat__CustomerID_186c1f4d-5f57-49c0-98c6-e20b6fb281bf` FLOAT(53),
	`cat__CustomerID_1889ca5a-60c6-4da8-8289-4cd9af1f7152` FLOAT(53),
	`cat__CustomerID_1a26ed92-27bd-4be2-8386-45682bfc37f5` FLOAT(53),
	`cat__CustomerID_1a52951e-af95-4353-aed3-385ce0718034` FLOAT(53),
	`cat__CustomerID_1b35b6d8-800e-4972-879e-7235f8840cb3` FLOAT(53),
	`cat__CustomerID_1b626cad-36b0-4cd8-ad1a-5bae2dc27b61` FLOAT(53),
	`cat__CustomerID_1b96902d-270f-44ad-8e0c-b401104aaadb` FLOAT(53),
	`cat__CustomerID_1cc1e21a-c2e5-4616-a5cf-a544eb8a944e` FLOAT(53),
	`cat__CustomerID_1e871ef8-cdf7-4f1b-888f-18086f3dc030` FLOAT(53),
	`cat__CustomerID_1f3219ac-02a6-455b-af6a-87711e6653d1` FLOAT(53),
	`cat__CustomerID_1f696c4e-14d1-40b4-a151-52968f14a663` FLOAT(53),
	`cat__CustomerID_22974c53-2595-473f-bbd2-9f309d5e742f` FLOAT(53),
	`cat__CustomerID_232d1545-43b1-477b-ac22-4b1d25b9f81a` FLOAT(53),
	`cat__CustomerID_2398f009-a88e-4af1-b32e-e9eaf1c0409c` FLOAT(53),
	`cat__CustomerID_23eef71c-2019-4005-b8ac-c849cc15b25a` FLOAT(53),
	`cat__CustomerID_2520f9ed-572a-45a1-96af-3d25c78e1b98` FLOAT(53),
	`cat__CustomerID_259051fc-5e0b-49ed-b0a7-09140016fe70` FLOAT(53),
	`cat__CustomerID_25debb26-0ef4-4c61-a5bc-dc5d74696803` FLOAT(53),
	`cat__CustomerID_267f6422-e359-4bb5-98c9-300691a129bf` FLOAT(53),
	`cat__CustomerID_27055332-a7e4-4ed9-a629-240d59715f87` FLOAT(53),
	`cat__CustomerID_2763a02b-2940-4497-931c-db0ad39455be` FLOAT(53),
	`cat__CustomerID_276d23d2-aa88-4056-9480-acc4c7d6a499` FLOAT(53),
	`cat__CustomerID_27f9e498-f3d9-4c22-a051-8b1bd11e4fad` FLOAT(53),
	`cat__CustomerID_28db4b77-bf17-4d5e-8c81-aa62e84a1b6e` FLOAT(53),
	`cat__CustomerID_2a5e6434-a903-4944-ac8c-aedf06d19d05` FLOAT(53),
	`cat__CustomerID_2ac529aa-c34d-4dcd-9f91-ba34671c0e28` FLOAT(53),
	`cat__CustomerID_2b06b9cf-bfd9-4a6b-809c-ae5d5b4202e1` FLOAT(53),

In [38]:
# 1. إزالة الأعمدة المكررة
df_final = df_final.loc[:, ~df_final.columns.duplicated(keep='first')].copy()

# 2. التأكد من أسماء الأعمدة
df_final.columns = df_final.columns.astype(str)

# 3. رفع الجدول
df_final.to_sql(
    "sales_processed",
    con=engine,
    if_exists="replace",
    index=False
)

OperationalError: (pymysql.err.OperationalError) (1060, "Duplicate column name 'cat__CurrencyType_Usd'")
[SQL:
CREATE TABLE sales_processed (
	`num__Qty` FLOAT(53),
	`num__Unit_Price` FLOAT(53),
	`cat__ProductName_Actually` FLOAT(53),
	`cat__ProductName_Adams Brush` FLOAT(53),
	`cat__ProductName_Alexander Spray` FLOAT(53),
	`cat__ProductName_Allen Brush` FLOAT(53),
	`cat__ProductName_Allen Notebook` FLOAT(53),
	`cat__ProductName_Anderson Lamp` FLOAT(53),
	`cat__ProductName_Arnold Fork` FLOAT(53),
	`cat__ProductName_Arnold Speaker` FLOAT(53),
	`cat__ProductName_Arnold Stick` FLOAT(53),
	`cat__ProductName_Bailey Drill` FLOAT(53),
	`cat__ProductName_Baker Speaker` FLOAT(53),
	`cat__ProductName_Ball Notebook` FLOAT(53),
	`cat__ProductName_Banks Gloves` FLOAT(53),
	`cat__ProductName_Barker Book` FLOAT(53),
	`cat__ProductName_Barker Deodorant` FLOAT(53),
	`cat__ProductName_Barnes Belt` FLOAT(53),
	`cat__ProductName_Barrett Basket` FLOAT(53),
	`cat__ProductName_Bell Glove` FLOAT(53),
	`cat__ProductName_Bennett Lock` FLOAT(53),
	`cat__ProductName_Black` FLOAT(53),
	`cat__ProductName_Boone Balm` FLOAT(53),
	`cat__ProductName_Boone Polish` FLOAT(53),
	`cat__ProductName_Bowen Tire` FLOAT(53),
	`cat__ProductName_Brooks Cap` FLOAT(53),
	`cat__ProductName_Bryant Brush` FLOAT(53),
	`cat__ProductName_Butler Jacket` FLOAT(53),
	`cat__ProductName_Cameron Fan` FLOAT(53),
	`cat__ProductName_Carter Fan` FLOAT(53),
	`cat__ProductName_Case` FLOAT(53),
	`cat__ProductName_Chavez Printer` FLOAT(53),
	`cat__ProductName_Clark Glass` FLOAT(53),
	`cat__ProductName_Cole Disk` FLOAT(53),
	`cat__ProductName_Cole Polish` FLOAT(53),
	`cat__ProductName_Coleman Case` FLOAT(53),
	`cat__ProductName_Collins Rug` FLOAT(53),
	`cat__ProductName_Conner Gel` FLOAT(53),
	`cat__ProductName_Cook Ball` FLOAT(53),
	`cat__ProductName_Cook Tray` FLOAT(53),
	`cat__ProductName_Cooper Knife` FLOAT(53),
	`cat__ProductName_Cox Screw` FLOAT(53),
	`cat__ProductName_Cross Rack` FLOAT(53),
	`cat__ProductName_Daniels Coat` FLOAT(53),
	`cat__ProductName_Dean Screw` FLOAT(53),
	`cat__ProductName_Dean Shelf` FLOAT(53),
	`cat__ProductName_Dennis Mug` FLOAT(53),
	`cat__ProductName_Diaz Soap` FLOAT(53),
	`cat__ProductName_Dixon Marker` FLOAT(53),
	`cat__ProductName_Doyle Grip` FLOAT(53),
	`cat__ProductName_Doyle Powder` FLOAT(53),
	`cat__ProductName_Edwards Mixer` FLOAT(53),
	`cat__ProductName_Evans Tape` FLOAT(53),
	`cat__ProductName_Fisher Clip` FLOAT(53),
	`cat__ProductName_Fisher Cover` FLOAT(53),
	`cat__ProductName_Fleming Tray` FLOAT(53),
	`cat__ProductName_Flores Coat` FLOAT(53),
	`cat__ProductName_Flowers Thread` FLOAT(53),
	`cat__ProductName_Ford Gel` FLOAT(53),
	`cat__ProductName_Foster Hat` FLOAT(53),
	`cat__ProductName_Foster Hook` FLOAT(53),
	`cat__ProductName_Fox Calendar` FLOAT(53),
	`cat__ProductName_Franklin Bag` FLOAT(53),
	`cat__ProductName_Gardner Sheet` FLOAT(53),
	`cat__ProductName_Gibbs Cream` FLOAT(53),
	`cat__ProductName_Gibson Clock` FLOAT(53),
	`cat__ProductName_Gilbert Pad` FLOAT(53),
	`cat__ProductName_Gonzales Sock` FLOAT(53),
	`cat__ProductName_Graham Cleaner` FLOAT(53),
	`cat__ProductName_Gray Tool` FLOAT(53),
	`cat__ProductName_Green Folder` FLOAT(53),
	`cat__ProductName_Gregory Helmet` FLOAT(53),
	`cat__ProductName_Griffin Cream` FLOAT(53),
	`cat__ProductName_Hall Cup` FLOAT(53),
	`cat__ProductName_Hamilton Paste` FLOAT(53),
	`cat__ProductName_Hanson Flashlight` FLOAT(53),
	`cat__ProductName_Harmon Net` FLOAT(53),
	`cat__ProductName_Harper Phone` FLOAT(53),
	`cat__ProductName_Harris Pen` FLOAT(53),
	`cat__ProductName_Hayes Lotion` FLOAT(53),
	`cat__ProductName_Henderson Gear` FLOAT(53),
	`cat__ProductName_Hill Phone` FLOAT(53),
	`cat__ProductName_Holland Nail` FLOAT(53),
	`cat__ProductName_Holmes Book` FLOAT(53),
	`cat__ProductName_Holmes Hook` FLOAT(53),
	`cat__ProductName_Horton Cable` FLOAT(53),
	`cat__ProductName_Howard Can` FLOAT(53),
	`cat__ProductName_Hudson Lamp` FLOAT(53),
	`cat__ProductName_Hughes Strap` FLOAT(53),
	`cat__ProductName_Ingram Booklet` FLOAT(53),
	`cat__ProductName_Jackson Cable` FLOAT(53),
	`cat__ProductName_James Grip` FLOAT(53),
	`cat__ProductName_Jenkins Valve` FLOAT(53),
	`cat__ProductName_Johnson Mirror` FLOAT(53),
	`cat__ProductName_Johnson Screen` FLOAT(53),
	`cat__ProductName_Jordan Bleach` FLOAT(53),
	`cat__ProductName_Kelly String` FLOAT(53),
	`cat__ProductName_Lane Mug` FLOAT(53),
	`cat__ProductName_Larson Rack` FLOAT(53),
	`cat__ProductName_Lee Clock` FLOAT(53),
	`cat__ProductName_Lewis Ruler` FLOAT(53),
	`cat__ProductName_Line` FLOAT(53),
	`cat__ProductName_Lloyd Mixer` FLOAT(53),
	`cat__ProductName_Long Mat` FLOAT(53),
	`cat__ProductName_Marsh Jar` FLOAT(53),
	`cat__ProductName_Martin Charger` FLOAT(53),
	`cat__ProductName_Matthews Plate` FLOAT(53),
	`cat__ProductName_Mitchell Frame` FLOAT(53),
	`cat__ProductName_Moody Net` FLOAT(53),
	`cat__ProductName_Moore Chair` FLOAT(53),
	`cat__ProductName_Morgan Stick` FLOAT(53),
	`cat__ProductName_Morris Bottle` FLOAT(53),
	`cat__ProductName_Morris Tray` FLOAT(53),
	`cat__ProductName_Murphy Dish` FLOAT(53),
	`cat__ProductName_Myers Shampoo` FLOAT(53),
	`cat__ProductName_Nelson Knife` FLOAT(53),
	`cat__ProductName_Newman Rod` FLOAT(53),
	`cat__ProductName_On` FLOAT(53),
	`cat__ProductName_Owens Powder` FLOAT(53),
	`cat__ProductName_Owens Tape` FLOAT(53),
	`cat__ProductName_Page Pen` FLOAT(53),
	`cat__ProductName_Palmer Screen` FLOAT(53),
	`cat__ProductName_Parker Cable` FLOAT(53),
	`cat__ProductName_Patterson Filter` FLOAT(53),
	`cat__ProductName_Perez Board` FLOAT(53),
	`cat__ProductName_Perry Switch` FLOAT(53),
	`cat__ProductName_Peterson Sheet` FLOAT(53),
	`cat__ProductName_Phillips Hook` FLOAT(53),
	`cat__ProductName_Pierce File` FLOAT(53),
	`cat__ProductName_Pierce Plate` FLOAT(53),
	`cat__ProductName_Potter Shield` FLOAT(53),
	`cat__ProductName_Powell Tube` FLOAT(53),
	`cat__ProductName_Price Clip` FLOAT(53),
	`cat__ProductName_Ramirez Bar` FLOAT(53),
	`cat__ProductName_Reed Rack` FLOAT(53),
	`cat__ProductName_Reid Strap` FLOAT(53),
	`cat__ProductName_Richardson Nail` FLOAT(53),
	`cat__ProductName_Rivera Block` FLOAT(53),
	`cat__ProductName_Rivers Lid` FLOAT(53),
	`cat__ProductName_Roberts Ingredient` FLOAT(53),
	`cat__ProductName_Roberts Pen` FLOAT(53),
	`cat__ProductName_Robinson Shelf` FLOAT(53),
	`cat__ProductName_Rodriguez Keyboard` FLOAT(53),
	`cat__ProductName_Rogers Lid` FLOAT(53),
	`cat__ProductName_Ross Cover` FLOAT(53),
	`cat__ProductName_Russell Oil` FLOAT(53),
	`cat__ProductName_Sanchez Book` FLOAT(53),
	`cat__ProductName_Sanders Pin` FLOAT(53),
	`cat__ProductName_Sanderson Spray` FLOAT(53),
	`cat__ProductName_Scott Plate` FLOAT(53),
	`cat__ProductName_Simmons Shorts` FLOAT(53),
	`cat__ProductName_Sims Brush` FLOAT(53),
	`cat__ProductName_Skill` FLOAT(53),
	`cat__ProductName_Smith Bag` FLOAT(53),
	`cat__ProductName_Smith Paper` FLOAT(53),
	`cat__ProductName_Soon` FLOAT(53),
	`cat__ProductName_Spencer Frame` FLOAT(53),
	`cat__ProductName_Stevens Cap` FLOAT(53),
	`cat__ProductName_Stewart Mouse` FLOAT(53),
	`cat__ProductName_Sullivan Wax` FLOAT(53),
	`cat__ProductName_Swanson Bucket` FLOAT(53),
	`cat__ProductName_Taylor Table` FLOAT(53),
	`cat__ProductName_Torres Stand` FLOAT(53),
	`cat__ProductName_Torres Table` FLOAT(53),
	`cat__ProductName_Tucker Helmet` FLOAT(53),
	`cat__ProductName_Turner Pad` FLOAT(53),
	`cat__ProductName_Vang Charger` FLOAT(53),
	`cat__ProductName_Vasquez Bottle` FLOAT(53),
	`cat__ProductName_Wade Charger` FLOAT(53),
	`cat__ProductName_Walker Camera` FLOAT(53),
	`cat__ProductName_Wallace Polish` FLOAT(53),
	`cat__ProductName_Wallace Sheet` FLOAT(53),
	`cat__ProductName_Ward Plug` FLOAT(53),
	`cat__ProductName_Warren Lamp` FLOAT(53),
	`cat__ProductName_Washington Skirt` FLOAT(53),
	`cat__ProductName_Watson Chain` FLOAT(53),
	`cat__ProductName_Welch Mirror` FLOAT(53),
	`cat__ProductName_Welch Spray` FLOAT(53),
	`cat__ProductName_West Shine` FLOAT(53),
	`cat__ProductName_White Monitor` FLOAT(53),
	`cat__ProductName_Williams Bottle` FLOAT(53),
	`cat__ProductName_Wood Tire` FLOAT(53),
	`cat__ProductName_Woods Detergent` FLOAT(53),
	`cat__ProductName_Young Printer` FLOAT(53),
	`cat__SaleDate_1/1/2025` FLOAT(53),
	`cat__SaleDate_1/10/2025` FLOAT(53),
	`cat__SaleDate_1/11/2025` FLOAT(53),
	`cat__SaleDate_1/15/2025` FLOAT(53),
	`cat__SaleDate_1/16/2025` FLOAT(53),
	`cat__SaleDate_1/19/2025` FLOAT(53),
	`cat__SaleDate_1/20/2025` FLOAT(53),
	`cat__SaleDate_1/21/2025` FLOAT(53),
	`cat__SaleDate_1/22/2025` FLOAT(53),
	`cat__SaleDate_1/23/2025` FLOAT(53),
	`cat__SaleDate_1/24/2025` FLOAT(53),
	`cat__SaleDate_1/5/2025` FLOAT(53),
	`cat__SaleDate_1/6/2025` FLOAT(53),
	`cat__SaleDate_1/7/2025` FLOAT(53),
	`cat__SaleDate_1/9/2025` FLOAT(53),
	`cat__SaleDate_10/10/2024` FLOAT(53),
	`cat__SaleDate_10/11/2024` FLOAT(53),
	`cat__SaleDate_10/12/2024` FLOAT(53),
	`cat__SaleDate_10/13/2024` FLOAT(53),
	`cat__SaleDate_10/14/2024` FLOAT(53),
	`cat__SaleDate_10/15/2024` FLOAT(53),
	`cat__SaleDate_10/17/2024` FLOAT(53),
	`cat__SaleDate_10/18/2024` FLOAT(53),
	`cat__SaleDate_10/19/2024` FLOAT(53),
	`cat__SaleDate_10/20/2024` FLOAT(53),
	`cat__SaleDate_10/21/2024` FLOAT(53),
	`cat__SaleDate_10/25/2024` FLOAT(53),
	`cat__SaleDate_10/26/2024` FLOAT(53),
	`cat__SaleDate_10/27/2024` FLOAT(53),
	`cat__SaleDate_10/4/2024` FLOAT(53),
	`cat__SaleDate_10/6/2024` FLOAT(53),
	`cat__SaleDate_10/8/2024` FLOAT(53),
	`cat__SaleDate_11/1/2024` FLOAT(53),
	`cat__SaleDate_11/10/2024` FLOAT(53),
	`cat__SaleDate_11/11/2024` FLOAT(53),
	`cat__SaleDate_11/13/2024` FLOAT(53),
	`cat__SaleDate_11/18/2024` FLOAT(53),
	`cat__SaleDate_11/19/2024` FLOAT(53),
	`cat__SaleDate_11/2/2024` FLOAT(53),
	`cat__SaleDate_11/22/2024` FLOAT(53),
	`cat__SaleDate_11/23/2024` FLOAT(53),
	`cat__SaleDate_11/24/2024` FLOAT(53),
	`cat__SaleDate_11/25/2024` FLOAT(53),
	`cat__SaleDate_11/26/2024` FLOAT(53),
	`cat__SaleDate_11/3/2024` FLOAT(53),
	`cat__SaleDate_11/30/2024` FLOAT(53),
	`cat__SaleDate_11/5/2024` FLOAT(53),
	`cat__SaleDate_11/6/2024` FLOAT(53),
	`cat__SaleDate_11/7/2024` FLOAT(53),
	`cat__SaleDate_11/8/2024` FLOAT(53),
	`cat__SaleDate_11/9/2024` FLOAT(53),
	`cat__SaleDate_12/1/2024` FLOAT(53),
	`cat__SaleDate_12/13/2024` FLOAT(53),
	`cat__SaleDate_12/15/2024` FLOAT(53),
	`cat__SaleDate_12/17/2024` FLOAT(53),
	`cat__SaleDate_12/18/2024` FLOAT(53),
	`cat__SaleDate_12/2/2024` FLOAT(53),
	`cat__SaleDate_12/20/2024` FLOAT(53),
	`cat__SaleDate_12/24/2024` FLOAT(53),
	`cat__SaleDate_12/25/2024` FLOAT(53),
	`cat__SaleDate_12/26/2024` FLOAT(53),
	`cat__SaleDate_12/27/2024` FLOAT(53),
	`cat__SaleDate_12/28/2024` FLOAT(53),
	`cat__SaleDate_12/29/2024` FLOAT(53),
	`cat__SaleDate_12/3/2024` FLOAT(53),
	`cat__SaleDate_12/31/2024` FLOAT(53),
	`cat__SaleDate_12/7/2024` FLOAT(53),
	`cat__SaleDate_12/9/2024` FLOAT(53),
	`cat__SaleDate_2/10/2025` FLOAT(53),
	`cat__SaleDate_2/11/2025` FLOAT(53),
	`cat__SaleDate_2/12/2025` FLOAT(53),
	`cat__SaleDate_2/17/2025` FLOAT(53),
	`cat__SaleDate_2/18/2025` FLOAT(53),
	`cat__SaleDate_2/19/2025` FLOAT(53),
	`cat__SaleDate_2/2/2025` FLOAT(53),
	`cat__SaleDate_2/20/2025` FLOAT(53),
	`cat__SaleDate_2/21/2025` FLOAT(53),
	`cat__SaleDate_2/22/2025` FLOAT(53),
	`cat__SaleDate_2/23/2025` FLOAT(53),
	`cat__SaleDate_2/24/2025` FLOAT(53),
	`cat__SaleDate_2/25/2025` FLOAT(53),
	`cat__SaleDate_2/3/2025` FLOAT(53),
	`cat__SaleDate_2/6/2025` FLOAT(53),
	`cat__SaleDate_2/7/2025` FLOAT(53),
	`cat__SaleDate_2/9/2025` FLOAT(53),
	`cat__SaleDate_3/12/2025` FLOAT(53),
	`cat__SaleDate_3/16/2025` FLOAT(53),
	`cat__SaleDate_3/17/2025` FLOAT(53),
	`cat__SaleDate_3/18/2025` FLOAT(53),
	`cat__SaleDate_3/20/2025` FLOAT(53),
	`cat__SaleDate_3/21/2025` FLOAT(53),
	`cat__SaleDate_3/22/2025` FLOAT(53),
	`cat__SaleDate_3/23/2025` FLOAT(53),
	`cat__SaleDate_3/24/2025` FLOAT(53),
	`cat__SaleDate_3/25/2025` FLOAT(53),
	`cat__SaleDate_3/27/2025` FLOAT(53),
	`cat__SaleDate_3/28/2025` FLOAT(53),
	`cat__SaleDate_3/3/2025` FLOAT(53),
	`cat__SaleDate_3/30/2025` FLOAT(53),
	`cat__SaleDate_3/31/2025` FLOAT(53),
	`cat__SaleDate_3/4/2025` FLOAT(53),
	`cat__SaleDate_3/5/2025` FLOAT(53),
	`cat__SaleDate_3/6/2025` FLOAT(53),
	`cat__SaleDate_3/7/2025` FLOAT(53),
	`cat__SaleDate_3/8/2025` FLOAT(53),
	`cat__SaleDate_3/9/2025` FLOAT(53),
	`cat__SaleDate_4/1/2025` FLOAT(53),
	`cat__SaleDate_4/11/2025` FLOAT(53),
	`cat__SaleDate_4/15/2025` FLOAT(53),
	`cat__SaleDate_4/16/2025` FLOAT(53),
	`cat__SaleDate_4/19/2025` FLOAT(53),
	`cat__SaleDate_4/22/2025` FLOAT(53),
	`cat__SaleDate_4/23/2025` FLOAT(53),
	`cat__SaleDate_4/27/2025` FLOAT(53),
	`cat__SaleDate_4/28/2025` FLOAT(53),
	`cat__SaleDate_4/3/2025` FLOAT(53),
	`cat__SaleDate_4/5/2025` FLOAT(53),
	`cat__SaleDate_4/7/2025` FLOAT(53),
	`cat__SaleDate_4/8/2025` FLOAT(53),
	`cat__SaleDate_4/9/2025` FLOAT(53),
	`cat__SaleDate_5/10/2025` FLOAT(53),
	`cat__SaleDate_5/11/2025` FLOAT(53),
	`cat__SaleDate_5/12/2025` FLOAT(53),
	`cat__SaleDate_5/13/2025` FLOAT(53),
	`cat__SaleDate_5/14/2025` FLOAT(53),
	`cat__SaleDate_5/15/2025` FLOAT(53),
	`cat__SaleDate_5/18/2025` FLOAT(53),
	`cat__SaleDate_5/22/2025` FLOAT(53),
	`cat__SaleDate_5/23/2025` FLOAT(53),
	`cat__SaleDate_5/24/2025` FLOAT(53),
	`cat__SaleDate_5/25/2024` FLOAT(53),
	`cat__SaleDate_5/25/2025` FLOAT(53),
	`cat__SaleDate_5/26/2024` FLOAT(53),
	`cat__SaleDate_5/28/2024` FLOAT(53),
	`cat__SaleDate_5/3/2025` FLOAT(53),
	`cat__SaleDate_5/31/2024` FLOAT(53),
	`cat__SaleDate_5/5/2025` FLOAT(53),
	`cat__SaleDate_5/7/2025` FLOAT(53),
	`cat__SaleDate_6/1/2024` FLOAT(53),
	`cat__SaleDate_6/11/2024` FLOAT(53),
	`cat__SaleDate_6/13/2024` FLOAT(53),
	`cat__SaleDate_6/14/2024` FLOAT(53),
	`cat__SaleDate_6/15/2024` FLOAT(53),
	`cat__SaleDate_6/16/2024` FLOAT(53),
	`cat__SaleDate_6/17/2024` FLOAT(53),
	`cat__SaleDate_6/18/2024` FLOAT(53),
	`cat__SaleDate_6/19/2024` FLOAT(53),
	`cat__SaleDate_6/22/2024` FLOAT(53),
	`cat__SaleDate_6/24/2024` FLOAT(53),
	`cat__SaleDate_6/27/2024` FLOAT(53),
	`cat__SaleDate_6/29/2024` FLOAT(53),
	`cat__SaleDate_6/30/2024` FLOAT(53),
	`cat__SaleDate_6/4/2024` FLOAT(53),
	`cat__SaleDate_6/5/2024` FLOAT(53),
	`cat__SaleDate_6/6/2024` FLOAT(53),
	`cat__SaleDate_6/7/2024` FLOAT(53),
	`cat__SaleDate_6/9/2024` FLOAT(53),
	`cat__SaleDate_7/13/2024` FLOAT(53),
	`cat__SaleDate_7/14/2024` FLOAT(53),
	`cat__SaleDate_7/15/2024` FLOAT(53),
	`cat__SaleDate_7/16/2024` FLOAT(53),
	`cat__SaleDate_7/17/2024` FLOAT(53),
	`cat__SaleDate_7/18/2024` FLOAT(53),
	`cat__SaleDate_7/20/2024` FLOAT(53),
	`cat__SaleDate_7/21/2024` FLOAT(53),
	`cat__SaleDate_7/26/2024` FLOAT(53),
	`cat__SaleDate_7/27/2024` FLOAT(53),
	`cat__SaleDate_7/28/2024` FLOAT(53),
	`cat__SaleDate_7/31/2024` FLOAT(53),
	`cat__SaleDate_7/4/2024` FLOAT(53),
	`cat__SaleDate_7/5/2024` FLOAT(53),
	`cat__SaleDate_7/7/2024` FLOAT(53),
	`cat__SaleDate_7/8/2024` FLOAT(53),
	`cat__SaleDate_7/9/2024` FLOAT(53),
	`cat__SaleDate_8/10/2024` FLOAT(53),
	`cat__SaleDate_8/11/2024` FLOAT(53),
	`cat__SaleDate_8/12/2024` FLOAT(53),
	`cat__SaleDate_8/15/2024` FLOAT(53),
	`cat__SaleDate_8/2/2024` FLOAT(53),
	`cat__SaleDate_8/20/2024` FLOAT(53),
	`cat__SaleDate_8/21/2024` FLOAT(53),
	`cat__SaleDate_8/22/2024` FLOAT(53),
	`cat__SaleDate_8/23/2024` FLOAT(53),
	`cat__SaleDate_8/24/2024` FLOAT(53),
	`cat__SaleDate_8/25/2024` FLOAT(53),
	`cat__SaleDate_8/29/2024` FLOAT(53),
	`cat__SaleDate_8/3/2024` FLOAT(53),
	`cat__SaleDate_8/31/2024` FLOAT(53),
	`cat__SaleDate_8/5/2024` FLOAT(53),
	`cat__SaleDate_8/7/2024` FLOAT(53),
	`cat__SaleDate_8/8/2024` FLOAT(53),
	`cat__SaleDate_9/1/2024` FLOAT(53),
	`cat__SaleDate_9/10/2024` FLOAT(53),
	`cat__SaleDate_9/15/2024` FLOAT(53),
	`cat__SaleDate_9/2/2024` FLOAT(53),
	`cat__SaleDate_9/20/2024` FLOAT(53),
	`cat__SaleDate_9/22/2024` FLOAT(53),
	`cat__SaleDate_9/25/2024` FLOAT(53),
	`cat__SaleDate_9/26/2024` FLOAT(53),
	`cat__SaleDate_9/27/2024` FLOAT(53),
	`cat__SaleDate_9/28/2024` FLOAT(53),
	`cat__SaleDate_9/29/2024` FLOAT(53),
	`cat__SaleDate_9/30/2024` FLOAT(53),
	`cat__SaleDate_9/5/2024` FLOAT(53),
	`cat__SaleDate_9/6/2024` FLOAT(53),
	`cat__SaleDate_9/8/2024` FLOAT(53),
	`cat__CurrencyType_OMR` FLOAT(53),
	`cat__CurrencyType_USD` FLOAT(53),
	`cat__CurrencyType_Usd` FLOAT(53),
	`cat__CurrencyType_usd` FLOAT(53),
	`cat__CustomerID_0104ec48-84a4-4638-9ed4-dad335d44c43` FLOAT(53),
	`cat__CustomerID_0403d558-166d-4616-9f3e-98d3d7414d35` FLOAT(53),
	`cat__CustomerID_0437bab5-0dae-422e-9d2d-719091ea2dd9` FLOAT(53),
	`cat__CustomerID_045081fa-0df3-4904-820b-067b4176fb85` FLOAT(53),
	`cat__CustomerID_051e499e-f4d0-4a1e-a595-21fc69b2db45` FLOAT(53),
	`cat__CustomerID_0534e616-cbd9-4eba-82bf-f3903ad76eb9` FLOAT(53),
	`cat__CustomerID_05d39b68-833c-45d0-9af3-c0b3bad43a5c` FLOAT(53),
	`cat__CustomerID_05d75424-135a-40ea-9f43-7297d527e0e0` FLOAT(53),
	`cat__CustomerID_07991be5-0500-4bdc-95bc-a3ee50f4d268` FLOAT(53),
	`cat__CustomerID_0822d2d7-9454-4aa3-95bc-b869d6957852` FLOAT(53),
	`cat__CustomerID_089f6dd7-f901-4521-a02c-eb1bf002c6c7` FLOAT(53),
	`cat__CustomerID_0957271b-9145-4838-a842-c40eddb6a2f6` FLOAT(53),
	`cat__CustomerID_0b4a7550-cb81-475b-b8f0-4d4e9668f7e8` FLOAT(53),
	`cat__CustomerID_0bbb7256-0ad2-4b07-a1b0-cba178732f64` FLOAT(53),
	`cat__CustomerID_0bffb839-d519-494d-8b15-9498de261bd6` FLOAT(53),
	`cat__CustomerID_0dadb5f8-e924-45a5-806b-681dd7aebdea` FLOAT(53),
	`cat__CustomerID_0e57e6c8-d5c5-43fa-919e-3640f6ebba01` FLOAT(53),
	`cat__CustomerID_0ead620f-7c7d-4908-bdda-c73282d77d87` FLOAT(53),
	`cat__CustomerID_0ec24f4e-0f17-4c4c-8b16-7b53519d7ce2` FLOAT(53),
	`cat__CustomerID_103bc58d-7df8-47ae-988b-8738b4b2b050` FLOAT(53),
	`cat__CustomerID_104d0c3e-ccfc-43a7-b3e7-e1c56e986cdd` FLOAT(53),
	`cat__CustomerID_10c8ed7e-bba0-4f05-99b7-c72d90c66aaf` FLOAT(53),
	`cat__CustomerID_10f25bba-5c31-4c70-b065-e050a9b6803a` FLOAT(53),
	`cat__CustomerID_11444ef2-a6c9-42e9-8015-6446784d11a7` FLOAT(53),
	`cat__CustomerID_124ea517-d2c8-4ce0-8b00-fcdcfecff89e` FLOAT(53),
	`cat__CustomerID_134fd311-9094-4aef-9068-78b44f308566` FLOAT(53),
	`cat__CustomerID_13c53f9f-0f5f-492c-8660-001021d8745e` FLOAT(53),
	`cat__CustomerID_14cd77f7-8505-47df-a916-b64aae66ebd2` FLOAT(53),
	`cat__CustomerID_15c37dcb-1c11-4482-b1fc-da11997f0d63` FLOAT(53),
	`cat__CustomerID_15fda73e-7b88-4ad7-85c9-d23d8187e574` FLOAT(53),
	`cat__CustomerID_174cb239-fa9b-49fc-88b8-052996b04e57` FLOAT(53),
	`cat__CustomerID_186c1f4d-5f57-49c0-98c6-e20b6fb281bf` FLOAT(53),
	`cat__CustomerID_1889ca5a-60c6-4da8-8289-4cd9af1f7152` FLOAT(53),
	`cat__CustomerID_1a26ed92-27bd-4be2-8386-45682bfc37f5` FLOAT(53),
	`cat__CustomerID_1a52951e-af95-4353-aed3-385ce0718034` FLOAT(53),
	`cat__CustomerID_1b35b6d8-800e-4972-879e-7235f8840cb3` FLOAT(53),
	`cat__CustomerID_1b626cad-36b0-4cd8-ad1a-5bae2dc27b61` FLOAT(53),
	`cat__CustomerID_1b96902d-270f-44ad-8e0c-b401104aaadb` FLOAT(53),
	`cat__CustomerID_1cc1e21a-c2e5-4616-a5cf-a544eb8a944e` FLOAT(53),
	`cat__CustomerID_1e871ef8-cdf7-4f1b-888f-18086f3dc030` FLOAT(53),
	`cat__CustomerID_1f3219ac-02a6-455b-af6a-87711e6653d1` FLOAT(53),
	`cat__CustomerID_1f696c4e-14d1-40b4-a151-52968f14a663` FLOAT(53),
	`cat__CustomerID_22974c53-2595-473f-bbd2-9f309d5e742f` FLOAT(53),
	`cat__CustomerID_232d1545-43b1-477b-ac22-4b1d25b9f81a` FLOAT(53),
	`cat__CustomerID_2398f009-a88e-4af1-b32e-e9eaf1c0409c` FLOAT(53),
	`cat__CustomerID_23eef71c-2019-4005-b8ac-c849cc15b25a` FLOAT(53),
	`cat__CustomerID_2520f9ed-572a-45a1-96af-3d25c78e1b98` FLOAT(53),
	`cat__CustomerID_259051fc-5e0b-49ed-b0a7-09140016fe70` FLOAT(53),
	`cat__CustomerID_25debb26-0ef4-4c61-a5bc-dc5d74696803` FLOAT(53),
	`cat__CustomerID_267f6422-e359-4bb5-98c9-300691a129bf` FLOAT(53),
	`cat__CustomerID_27055332-a7e4-4ed9-a629-240d59715f87` FLOAT(53),
	`cat__CustomerID_2763a02b-2940-4497-931c-db0ad39455be` FLOAT(53),
	`cat__CustomerID_276d23d2-aa88-4056-9480-acc4c7d6a499` FLOAT(53),
	`cat__CustomerID_27f9e498-f3d9-4c22-a051-8b1bd11e4fad` FLOAT(53),
	`cat__CustomerID_28db4b77-bf17-4d5e-8c81-aa62e84a1b6e` FLOAT(53),
	`cat__CustomerID_2a5e6434-a903-4944-ac8c-aedf06d19d05` FLOAT(53),
	`cat__CustomerID_2ac529aa-c34d-4dcd-9f91-ba34671c0e28` FLOAT(53),
	`cat__CustomerID_2b06b9cf-bfd9-4a6b-809c-ae5d5b4202e1` FLOAT(53),

In [39]:
print(df_final.columns[df_final.columns.duplicated()])

Index([], dtype='str')

In [40]:
df_final.columns = df_final.columns.str.strip()

In [41]:
df_final = df_final.loc[:, ~df_final.columns.duplicated(keep='first')]

In [42]:
print(df_final.columns.duplicated().sum())

0

In [43]:
df_final.columns = df_final.columns.astype(str)
df_final.columns = [col.replace(" ", "_") for col in df_final.columns]

In [44]:
df_final.to_sql(
    "sales_processed",
    con=engine,
    if_exists="replace",
    index=False
)

OperationalError: (pymysql.err.OperationalError) (1060, "Duplicate column name 'cat__CurrencyType_Usd'")
[SQL:
CREATE TABLE sales_processed (
	`num__Qty` FLOAT(53),
	`num__Unit_Price` FLOAT(53),
	`cat__ProductName_Actually` FLOAT(53),
	`cat__ProductName_Adams_Brush` FLOAT(53),
	`cat__ProductName_Alexander_Spray` FLOAT(53),
	`cat__ProductName_Allen_Brush` FLOAT(53),
	`cat__ProductName_Allen_Notebook` FLOAT(53),
	`cat__ProductName_Anderson_Lamp` FLOAT(53),
	`cat__ProductName_Arnold_Fork` FLOAT(53),
	`cat__ProductName_Arnold_Speaker` FLOAT(53),
	`cat__ProductName_Arnold_Stick` FLOAT(53),
	`cat__ProductName_Bailey_Drill` FLOAT(53),
	`cat__ProductName_Baker_Speaker` FLOAT(53),
	`cat__ProductName_Ball_Notebook` FLOAT(53),
	`cat__ProductName_Banks_Gloves` FLOAT(53),
	`cat__ProductName_Barker_Book` FLOAT(53),
	`cat__ProductName_Barker_Deodorant` FLOAT(53),
	`cat__ProductName_Barnes_Belt` FLOAT(53),
	`cat__ProductName_Barrett_Basket` FLOAT(53),
	`cat__ProductName_Bell_Glove` FLOAT(53),
	`cat__ProductName_Bennett_Lock` FLOAT(53),
	`cat__ProductName_Black` FLOAT(53),
	`cat__ProductName_Boone_Balm` FLOAT(53),
	`cat__ProductName_Boone_Polish` FLOAT(53),
	`cat__ProductName_Bowen_Tire` FLOAT(53),
	`cat__ProductName_Brooks_Cap` FLOAT(53),
	`cat__ProductName_Bryant_Brush` FLOAT(53),
	`cat__ProductName_Butler_Jacket` FLOAT(53),
	`cat__ProductName_Cameron_Fan` FLOAT(53),
	`cat__ProductName_Carter_Fan` FLOAT(53),
	`cat__ProductName_Case` FLOAT(53),
	`cat__ProductName_Chavez_Printer` FLOAT(53),
	`cat__ProductName_Clark_Glass` FLOAT(53),
	`cat__ProductName_Cole_Disk` FLOAT(53),
	`cat__ProductName_Cole_Polish` FLOAT(53),
	`cat__ProductName_Coleman_Case` FLOAT(53),
	`cat__ProductName_Collins_Rug` FLOAT(53),
	`cat__ProductName_Conner_Gel` FLOAT(53),
	`cat__ProductName_Cook_Ball` FLOAT(53),
	`cat__ProductName_Cook_Tray` FLOAT(53),
	`cat__ProductName_Cooper_Knife` FLOAT(53),
	`cat__ProductName_Cox_Screw` FLOAT(53),
	`cat__ProductName_Cross_Rack` FLOAT(53),
	`cat__ProductName_Daniels_Coat` FLOAT(53),
	`cat__ProductName_Dean_Screw` FLOAT(53),
	`cat__ProductName_Dean_Shelf` FLOAT(53),
	`cat__ProductName_Dennis_Mug` FLOAT(53),
	`cat__ProductName_Diaz_Soap` FLOAT(53),
	`cat__ProductName_Dixon_Marker` FLOAT(53),
	`cat__ProductName_Doyle_Grip` FLOAT(53),
	`cat__ProductName_Doyle_Powder` FLOAT(53),
	`cat__ProductName_Edwards_Mixer` FLOAT(53),
	`cat__ProductName_Evans_Tape` FLOAT(53),
	`cat__ProductName_Fisher_Clip` FLOAT(53),
	`cat__ProductName_Fisher_Cover` FLOAT(53),
	`cat__ProductName_Fleming_Tray` FLOAT(53),
	`cat__ProductName_Flores_Coat` FLOAT(53),
	`cat__ProductName_Flowers_Thread` FLOAT(53),
	`cat__ProductName_Ford_Gel` FLOAT(53),
	`cat__ProductName_Foster_Hat` FLOAT(53),
	`cat__ProductName_Foster_Hook` FLOAT(53),
	`cat__ProductName_Fox_Calendar` FLOAT(53),
	`cat__ProductName_Franklin_Bag` FLOAT(53),
	`cat__ProductName_Gardner_Sheet` FLOAT(53),
	`cat__ProductName_Gibbs_Cream` FLOAT(53),
	`cat__ProductName_Gibson_Clock` FLOAT(53),
	`cat__ProductName_Gilbert_Pad` FLOAT(53),
	`cat__ProductName_Gonzales_Sock` FLOAT(53),
	`cat__ProductName_Graham_Cleaner` FLOAT(53),
	`cat__ProductName_Gray_Tool` FLOAT(53),
	`cat__ProductName_Green_Folder` FLOAT(53),
	`cat__ProductName_Gregory_Helmet` FLOAT(53),
	`cat__ProductName_Griffin_Cream` FLOAT(53),
	`cat__ProductName_Hall_Cup` FLOAT(53),
	`cat__ProductName_Hamilton_Paste` FLOAT(53),
	`cat__ProductName_Hanson_Flashlight` FLOAT(53),
	`cat__ProductName_Harmon_Net` FLOAT(53),
	`cat__ProductName_Harper_Phone` FLOAT(53),
	`cat__ProductName_Harris_Pen` FLOAT(53),
	`cat__ProductName_Hayes_Lotion` FLOAT(53),
	`cat__ProductName_Henderson_Gear` FLOAT(53),
	`cat__ProductName_Hill_Phone` FLOAT(53),
	`cat__ProductName_Holland_Nail` FLOAT(53),
	`cat__ProductName_Holmes_Book` FLOAT(53),
	`cat__ProductName_Holmes_Hook` FLOAT(53),
	`cat__ProductName_Horton_Cable` FLOAT(53),
	`cat__ProductName_Howard_Can` FLOAT(53),
	`cat__ProductName_Hudson_Lamp` FLOAT(53),
	`cat__ProductName_Hughes_Strap` FLOAT(53),
	`cat__ProductName_Ingram_Booklet` FLOAT(53),
	`cat__ProductName_Jackson_Cable` FLOAT(53),
	`cat__ProductName_James_Grip` FLOAT(53),
	`cat__ProductName_Jenkins_Valve` FLOAT(53),
	`cat__ProductName_Johnson_Mirror` FLOAT(53),
	`cat__ProductName_Johnson_Screen` FLOAT(53),
	`cat__ProductName_Jordan_Bleach` FLOAT(53),
	`cat__ProductName_Kelly_String` FLOAT(53),
	`cat__ProductName_Lane_Mug` FLOAT(53),
	`cat__ProductName_Larson_Rack` FLOAT(53),
	`cat__ProductName_Lee_Clock` FLOAT(53),
	`cat__ProductName_Lewis_Ruler` FLOAT(53),
	`cat__ProductName_Line` FLOAT(53),
	`cat__ProductName_Lloyd_Mixer` FLOAT(53),
	`cat__ProductName_Long_Mat` FLOAT(53),
	`cat__ProductName_Marsh_Jar` FLOAT(53),
	`cat__ProductName_Martin_Charger` FLOAT(53),
	`cat__ProductName_Matthews_Plate` FLOAT(53),
	`cat__ProductName_Mitchell_Frame` FLOAT(53),
	`cat__ProductName_Moody_Net` FLOAT(53),
	`cat__ProductName_Moore_Chair` FLOAT(53),
	`cat__ProductName_Morgan_Stick` FLOAT(53),
	`cat__ProductName_Morris_Bottle` FLOAT(53),
	`cat__ProductName_Morris_Tray` FLOAT(53),
	`cat__ProductName_Murphy_Dish` FLOAT(53),
	`cat__ProductName_Myers_Shampoo` FLOAT(53),
	`cat__ProductName_Nelson_Knife` FLOAT(53),
	`cat__ProductName_Newman_Rod` FLOAT(53),
	`cat__ProductName_On` FLOAT(53),
	`cat__ProductName_Owens_Powder` FLOAT(53),
	`cat__ProductName_Owens_Tape` FLOAT(53),
	`cat__ProductName_Page_Pen` FLOAT(53),
	`cat__ProductName_Palmer_Screen` FLOAT(53),
	`cat__ProductName_Parker_Cable` FLOAT(53),
	`cat__ProductName_Patterson_Filter` FLOAT(53),
	`cat__ProductName_Perez_Board` FLOAT(53),
	`cat__ProductName_Perry_Switch` FLOAT(53),
	`cat__ProductName_Peterson_Sheet` FLOAT(53),
	`cat__ProductName_Phillips_Hook` FLOAT(53),
	`cat__ProductName_Pierce_File` FLOAT(53),
	`cat__ProductName_Pierce_Plate` FLOAT(53),
	`cat__ProductName_Potter_Shield` FLOAT(53),
	`cat__ProductName_Powell_Tube` FLOAT(53),
	`cat__ProductName_Price_Clip` FLOAT(53),
	`cat__ProductName_Ramirez_Bar` FLOAT(53),
	`cat__ProductName_Reed_Rack` FLOAT(53),
	`cat__ProductName_Reid_Strap` FLOAT(53),
	`cat__ProductName_Richardson_Nail` FLOAT(53),
	`cat__ProductName_Rivera_Block` FLOAT(53),
	`cat__ProductName_Rivers_Lid` FLOAT(53),
	`cat__ProductName_Roberts_Ingredient` FLOAT(53),
	`cat__ProductName_Roberts_Pen` FLOAT(53),
	`cat__ProductName_Robinson_Shelf` FLOAT(53),
	`cat__ProductName_Rodriguez_Keyboard` FLOAT(53),
	`cat__ProductName_Rogers_Lid` FLOAT(53),
	`cat__ProductName_Ross_Cover` FLOAT(53),
	`cat__ProductName_Russell_Oil` FLOAT(53),
	`cat__ProductName_Sanchez_Book` FLOAT(53),
	`cat__ProductName_Sanders_Pin` FLOAT(53),
	`cat__ProductName_Sanderson_Spray` FLOAT(53),
	`cat__ProductName_Scott_Plate` FLOAT(53),
	`cat__ProductName_Simmons_Shorts` FLOAT(53),
	`cat__ProductName_Sims_Brush` FLOAT(53),
	`cat__ProductName_Skill` FLOAT(53),
	`cat__ProductName_Smith_Bag` FLOAT(53),
	`cat__ProductName_Smith_Paper` FLOAT(53),
	`cat__ProductName_Soon` FLOAT(53),
	`cat__ProductName_Spencer_Frame` FLOAT(53),
	`cat__ProductName_Stevens_Cap` FLOAT(53),
	`cat__ProductName_Stewart_Mouse` FLOAT(53),
	`cat__ProductName_Sullivan_Wax` FLOAT(53),
	`cat__ProductName_Swanson_Bucket` FLOAT(53),
	`cat__ProductName_Taylor_Table` FLOAT(53),
	`cat__ProductName_Torres_Stand` FLOAT(53),
	`cat__ProductName_Torres_Table` FLOAT(53),
	`cat__ProductName_Tucker_Helmet` FLOAT(53),
	`cat__ProductName_Turner_Pad` FLOAT(53),
	`cat__ProductName_Vang_Charger` FLOAT(53),
	`cat__ProductName_Vasquez_Bottle` FLOAT(53),
	`cat__ProductName_Wade_Charger` FLOAT(53),
	`cat__ProductName_Walker_Camera` FLOAT(53),
	`cat__ProductName_Wallace_Polish` FLOAT(53),
	`cat__ProductName_Wallace_Sheet` FLOAT(53),
	`cat__ProductName_Ward_Plug` FLOAT(53),
	`cat__ProductName_Warren_Lamp` FLOAT(53),
	`cat__ProductName_Washington_Skirt` FLOAT(53),
	`cat__ProductName_Watson_Chain` FLOAT(53),
	`cat__ProductName_Welch_Mirror` FLOAT(53),
	`cat__ProductName_Welch_Spray` FLOAT(53),
	`cat__ProductName_West_Shine` FLOAT(53),
	`cat__ProductName_White_Monitor` FLOAT(53),
	`cat__ProductName_Williams_Bottle` FLOAT(53),
	`cat__ProductName_Wood_Tire` FLOAT(53),
	`cat__ProductName_Woods_Detergent` FLOAT(53),
	`cat__ProductName_Young_Printer` FLOAT(53),
	`cat__SaleDate_1/1/2025` FLOAT(53),
	`cat__SaleDate_1/10/2025` FLOAT(53),
	`cat__SaleDate_1/11/2025` FLOAT(53),
	`cat__SaleDate_1/15/2025` FLOAT(53),
	`cat__SaleDate_1/16/2025` FLOAT(53),
	`cat__SaleDate_1/19/2025` FLOAT(53),
	`cat__SaleDate_1/20/2025` FLOAT(53),
	`cat__SaleDate_1/21/2025` FLOAT(53),
	`cat__SaleDate_1/22/2025` FLOAT(53),
	`cat__SaleDate_1/23/2025` FLOAT(53),
	`cat__SaleDate_1/24/2025` FLOAT(53),
	`cat__SaleDate_1/5/2025` FLOAT(53),
	`cat__SaleDate_1/6/2025` FLOAT(53),
	`cat__SaleDate_1/7/2025` FLOAT(53),
	`cat__SaleDate_1/9/2025` FLOAT(53),
	`cat__SaleDate_10/10/2024` FLOAT(53),
	`cat__SaleDate_10/11/2024` FLOAT(53),
	`cat__SaleDate_10/12/2024` FLOAT(53),
	`cat__SaleDate_10/13/2024` FLOAT(53),
	`cat__SaleDate_10/14/2024` FLOAT(53),
	`cat__SaleDate_10/15/2024` FLOAT(53),
	`cat__SaleDate_10/17/2024` FLOAT(53),
	`cat__SaleDate_10/18/2024` FLOAT(53),
	`cat__SaleDate_10/19/2024` FLOAT(53),
	`cat__SaleDate_10/20/2024` FLOAT(53),
	`cat__SaleDate_10/21/2024` FLOAT(53),
	`cat__SaleDate_10/25/2024` FLOAT(53),
	`cat__SaleDate_10/26/2024` FLOAT(53),
	`cat__SaleDate_10/27/2024` FLOAT(53),
	`cat__SaleDate_10/4/2024` FLOAT(53),
	`cat__SaleDate_10/6/2024` FLOAT(53),
	`cat__SaleDate_10/8/2024` FLOAT(53),
	`cat__SaleDate_11/1/2024` FLOAT(53),
	`cat__SaleDate_11/10/2024` FLOAT(53),
	`cat__SaleDate_11/11/2024` FLOAT(53),
	`cat__SaleDate_11/13/2024` FLOAT(53),
	`cat__SaleDate_11/18/2024` FLOAT(53),
	`cat__SaleDate_11/19/2024` FLOAT(53),
	`cat__SaleDate_11/2/2024` FLOAT(53),
	`cat__SaleDate_11/22/2024` FLOAT(53),
	`cat__SaleDate_11/23/2024` FLOAT(53),
	`cat__SaleDate_11/24/2024` FLOAT(53),
	`cat__SaleDate_11/25/2024` FLOAT(53),
	`cat__SaleDate_11/26/2024` FLOAT(53),
	`cat__SaleDate_11/3/2024` FLOAT(53),
	`cat__SaleDate_11/30/2024` FLOAT(53),
	`cat__SaleDate_11/5/2024` FLOAT(53),
	`cat__SaleDate_11/6/2024` FLOAT(53),
	`cat__SaleDate_11/7/2024` FLOAT(53),
	`cat__SaleDate_11/8/2024` FLOAT(53),
	`cat__SaleDate_11/9/2024` FLOAT(53),
	`cat__SaleDate_12/1/2024` FLOAT(53),
	`cat__SaleDate_12/13/2024` FLOAT(53),
	`cat__SaleDate_12/15/2024` FLOAT(53),
	`cat__SaleDate_12/17/2024` FLOAT(53),
	`cat__SaleDate_12/18/2024` FLOAT(53),
	`cat__SaleDate_12/2/2024` FLOAT(53),
	`cat__SaleDate_12/20/2024` FLOAT(53),
	`cat__SaleDate_12/24/2024` FLOAT(53),
	`cat__SaleDate_12/25/2024` FLOAT(53),
	`cat__SaleDate_12/26/2024` FLOAT(53),
	`cat__SaleDate_12/27/2024` FLOAT(53),
	`cat__SaleDate_12/28/2024` FLOAT(53),
	`cat__SaleDate_12/29/2024` FLOAT(53),
	`cat__SaleDate_12/3/2024` FLOAT(53),
	`cat__SaleDate_12/31/2024` FLOAT(53),
	`cat__SaleDate_12/7/2024` FLOAT(53),
	`cat__SaleDate_12/9/2024` FLOAT(53),
	`cat__SaleDate_2/10/2025` FLOAT(53),
	`cat__SaleDate_2/11/2025` FLOAT(53),
	`cat__SaleDate_2/12/2025` FLOAT(53),
	`cat__SaleDate_2/17/2025` FLOAT(53),
	`cat__SaleDate_2/18/2025` FLOAT(53),
	`cat__SaleDate_2/19/2025` FLOAT(53),
	`cat__SaleDate_2/2/2025` FLOAT(53),
	`cat__SaleDate_2/20/2025` FLOAT(53),
	`cat__SaleDate_2/21/2025` FLOAT(53),
	`cat__SaleDate_2/22/2025` FLOAT(53),
	`cat__SaleDate_2/23/2025` FLOAT(53),
	`cat__SaleDate_2/24/2025` FLOAT(53),
	`cat__SaleDate_2/25/2025` FLOAT(53),
	`cat__SaleDate_2/3/2025` FLOAT(53),
	`cat__SaleDate_2/6/2025` FLOAT(53),
	`cat__SaleDate_2/7/2025` FLOAT(53),
	`cat__SaleDate_2/9/2025` FLOAT(53),
	`cat__SaleDate_3/12/2025` FLOAT(53),
	`cat__SaleDate_3/16/2025` FLOAT(53),
	`cat__SaleDate_3/17/2025` FLOAT(53),
	`cat__SaleDate_3/18/2025` FLOAT(53),
	`cat__SaleDate_3/20/2025` FLOAT(53),
	`cat__SaleDate_3/21/2025` FLOAT(53),
	`cat__SaleDate_3/22/2025` FLOAT(53),
	`cat__SaleDate_3/23/2025` FLOAT(53),
	`cat__SaleDate_3/24/2025` FLOAT(53),
	`cat__SaleDate_3/25/2025` FLOAT(53),
	`cat__SaleDate_3/27/2025` FLOAT(53),
	`cat__SaleDate_3/28/2025` FLOAT(53),
	`cat__SaleDate_3/3/2025` FLOAT(53),
	`cat__SaleDate_3/30/2025` FLOAT(53),
	`cat__SaleDate_3/31/2025` FLOAT(53),
	`cat__SaleDate_3/4/2025` FLOAT(53),
	`cat__SaleDate_3/5/2025` FLOAT(53),
	`cat__SaleDate_3/6/2025` FLOAT(53),
	`cat__SaleDate_3/7/2025` FLOAT(53),
	`cat__SaleDate_3/8/2025` FLOAT(53),
	`cat__SaleDate_3/9/2025` FLOAT(53),
	`cat__SaleDate_4/1/2025` FLOAT(53),
	`cat__SaleDate_4/11/2025` FLOAT(53),
	`cat__SaleDate_4/15/2025` FLOAT(53),
	`cat__SaleDate_4/16/2025` FLOAT(53),
	`cat__SaleDate_4/19/2025` FLOAT(53),
	`cat__SaleDate_4/22/2025` FLOAT(53),
	`cat__SaleDate_4/23/2025` FLOAT(53),
	`cat__SaleDate_4/27/2025` FLOAT(53),
	`cat__SaleDate_4/28/2025` FLOAT(53),
	`cat__SaleDate_4/3/2025` FLOAT(53),
	`cat__SaleDate_4/5/2025` FLOAT(53),
	`cat__SaleDate_4/7/2025` FLOAT(53),
	`cat__SaleDate_4/8/2025` FLOAT(53),
	`cat__SaleDate_4/9/2025` FLOAT(53),
	`cat__SaleDate_5/10/2025` FLOAT(53),
	`cat__SaleDate_5/11/2025` FLOAT(53),
	`cat__SaleDate_5/12/2025` FLOAT(53),
	`cat__SaleDate_5/13/2025` FLOAT(53),
	`cat__SaleDate_5/14/2025` FLOAT(53),
	`cat__SaleDate_5/15/2025` FLOAT(53),
	`cat__SaleDate_5/18/2025` FLOAT(53),
	`cat__SaleDate_5/22/2025` FLOAT(53),
	`cat__SaleDate_5/23/2025` FLOAT(53),
	`cat__SaleDate_5/24/2025` FLOAT(53),
	`cat__SaleDate_5/25/2024` FLOAT(53),
	`cat__SaleDate_5/25/2025` FLOAT(53),
	`cat__SaleDate_5/26/2024` FLOAT(53),
	`cat__SaleDate_5/28/2024` FLOAT(53),
	`cat__SaleDate_5/3/2025` FLOAT(53),
	`cat__SaleDate_5/31/2024` FLOAT(53),
	`cat__SaleDate_5/5/2025` FLOAT(53),
	`cat__SaleDate_5/7/2025` FLOAT(53),
	`cat__SaleDate_6/1/2024` FLOAT(53),
	`cat__SaleDate_6/11/2024` FLOAT(53),
	`cat__SaleDate_6/13/2024` FLOAT(53),
	`cat__SaleDate_6/14/2024` FLOAT(53),
	`cat__SaleDate_6/15/2024` FLOAT(53),
	`cat__SaleDate_6/16/2024` FLOAT(53),
	`cat__SaleDate_6/17/2024` FLOAT(53),
	`cat__SaleDate_6/18/2024` FLOAT(53),
	`cat__SaleDate_6/19/2024` FLOAT(53),
	`cat__SaleDate_6/22/2024` FLOAT(53),
	`cat__SaleDate_6/24/2024` FLOAT(53),
	`cat__SaleDate_6/27/2024` FLOAT(53),
	`cat__SaleDate_6/29/2024` FLOAT(53),
	`cat__SaleDate_6/30/2024` FLOAT(53),
	`cat__SaleDate_6/4/2024` FLOAT(53),
	`cat__SaleDate_6/5/2024` FLOAT(53),
	`cat__SaleDate_6/6/2024` FLOAT(53),
	`cat__SaleDate_6/7/2024` FLOAT(53),
	`cat__SaleDate_6/9/2024` FLOAT(53),
	`cat__SaleDate_7/13/2024` FLOAT(53),
	`cat__SaleDate_7/14/2024` FLOAT(53),
	`cat__SaleDate_7/15/2024` FLOAT(53),
	`cat__SaleDate_7/16/2024` FLOAT(53),
	`cat__SaleDate_7/17/2024` FLOAT(53),
	`cat__SaleDate_7/18/2024` FLOAT(53),
	`cat__SaleDate_7/20/2024` FLOAT(53),
	`cat__SaleDate_7/21/2024` FLOAT(53),
	`cat__SaleDate_7/26/2024` FLOAT(53),
	`cat__SaleDate_7/27/2024` FLOAT(53),
	`cat__SaleDate_7/28/2024` FLOAT(53),
	`cat__SaleDate_7/31/2024` FLOAT(53),
	`cat__SaleDate_7/4/2024` FLOAT(53),
	`cat__SaleDate_7/5/2024` FLOAT(53),
	`cat__SaleDate_7/7/2024` FLOAT(53),
	`cat__SaleDate_7/8/2024` FLOAT(53),
	`cat__SaleDate_7/9/2024` FLOAT(53),
	`cat__SaleDate_8/10/2024` FLOAT(53),
	`cat__SaleDate_8/11/2024` FLOAT(53),
	`cat__SaleDate_8/12/2024` FLOAT(53),
	`cat__SaleDate_8/15/2024` FLOAT(53),
	`cat__SaleDate_8/2/2024` FLOAT(53),
	`cat__SaleDate_8/20/2024` FLOAT(53),
	`cat__SaleDate_8/21/2024` FLOAT(53),
	`cat__SaleDate_8/22/2024` FLOAT(53),
	`cat__SaleDate_8/23/2024` FLOAT(53),
	`cat__SaleDate_8/24/2024` FLOAT(53),
	`cat__SaleDate_8/25/2024` FLOAT(53),
	`cat__SaleDate_8/29/2024` FLOAT(53),
	`cat__SaleDate_8/3/2024` FLOAT(53),
	`cat__SaleDate_8/31/2024` FLOAT(53),
	`cat__SaleDate_8/5/2024` FLOAT(53),
	`cat__SaleDate_8/7/2024` FLOAT(53),
	`cat__SaleDate_8/8/2024` FLOAT(53),
	`cat__SaleDate_9/1/2024` FLOAT(53),
	`cat__SaleDate_9/10/2024` FLOAT(53),
	`cat__SaleDate_9/15/2024` FLOAT(53),
	`cat__SaleDate_9/2/2024` FLOAT(53),
	`cat__SaleDate_9/20/2024` FLOAT(53),
	`cat__SaleDate_9/22/2024` FLOAT(53),
	`cat__SaleDate_9/25/2024` FLOAT(53),
	`cat__SaleDate_9/26/2024` FLOAT(53),
	`cat__SaleDate_9/27/2024` FLOAT(53),
	`cat__SaleDate_9/28/2024` FLOAT(53),
	`cat__SaleDate_9/29/2024` FLOAT(53),
	`cat__SaleDate_9/30/2024` FLOAT(53),
	`cat__SaleDate_9/5/2024` FLOAT(53),
	`cat__SaleDate_9/6/2024` FLOAT(53),
	`cat__SaleDate_9/8/2024` FLOAT(53),
	`cat__CurrencyType_OMR` FLOAT(53),
	`cat__CurrencyType_USD` FLOAT(53),
	`cat__CurrencyType_Usd` FLOAT(53),
	`cat__CurrencyType_usd` FLOAT(53),
	`cat__CustomerID_0104ec48-84a4-4638-9ed4-dad335d44c43` FLOAT(53),
	`cat__CustomerID_0403d558-166d-4616-9f3e-98d3d7414d35` FLOAT(53),
	`cat__CustomerID_0437bab5-0dae-422e-9d2d-719091ea2dd9` FLOAT(53),
	`cat__CustomerID_045081fa-0df3-4904-820b-067b4176fb85` FLOAT(53),
	`cat__CustomerID_051e499e-f4d0-4a1e-a595-21fc69b2db45` FLOAT(53),
	`cat__CustomerID_0534e616-cbd9-4eba-82bf-f3903ad76eb9` FLOAT(53),
	`cat__CustomerID_05d39b68-833c-45d0-9af3-c0b3bad43a5c` FLOAT(53),
	`cat__CustomerID_05d75424-135a-40ea-9f43-7297d527e0e0` FLOAT(53),
	`cat__CustomerID_07991be5-0500-4bdc-95bc-a3ee50f4d268` FLOAT(53),
	`cat__CustomerID_0822d2d7-9454-4aa3-95bc-b869d6957852` FLOAT(53),
	`cat__CustomerID_089f6dd7-f901-4521-a02c-eb1bf002c6c7` FLOAT(53),
	`cat__CustomerID_0957271b-9145-4838-a842-c40eddb6a2f6` FLOAT(53),
	`cat__CustomerID_0b4a7550-cb81-475b-b8f0-4d4e9668f7e8` FLOAT(53),
	`cat__CustomerID_0bbb7256-0ad2-4b07-a1b0-cba178732f64` FLOAT(53),
	`cat__CustomerID_0bffb839-d519-494d-8b15-9498de261bd6` FLOAT(53),
	`cat__CustomerID_0dadb5f8-e924-45a5-806b-681dd7aebdea` FLOAT(53),
	`cat__CustomerID_0e57e6c8-d5c5-43fa-919e-3640f6ebba01` FLOAT(53),
	`cat__CustomerID_0ead620f-7c7d-4908-bdda-c73282d77d87` FLOAT(53),
	`cat__CustomerID_0ec24f4e-0f17-4c4c-8b16-7b53519d7ce2` FLOAT(53),
	`cat__CustomerID_103bc58d-7df8-47ae-988b-8738b4b2b050` FLOAT(53),
	`cat__CustomerID_104d0c3e-ccfc-43a7-b3e7-e1c56e986cdd` FLOAT(53),
	`cat__CustomerID_10c8ed7e-bba0-4f05-99b7-c72d90c66aaf` FLOAT(53),
	`cat__CustomerID_10f25bba-5c31-4c70-b065-e050a9b6803a` FLOAT(53),
	`cat__CustomerID_11444ef2-a6c9-42e9-8015-6446784d11a7` FLOAT(53),
	`cat__CustomerID_124ea517-d2c8-4ce0-8b00-fcdcfecff89e` FLOAT(53),
	`cat__CustomerID_134fd311-9094-4aef-9068-78b44f308566` FLOAT(53),
	`cat__CustomerID_13c53f9f-0f5f-492c-8660-001021d8745e` FLOAT(53),
	`cat__CustomerID_14cd77f7-8505-47df-a916-b64aae66ebd2` FLOAT(53),
	`cat__CustomerID_15c37dcb-1c11-4482-b1fc-da11997f0d63` FLOAT(53),
	`cat__CustomerID_15fda73e-7b88-4ad7-85c9-d23d8187e574` FLOAT(53),
	`cat__CustomerID_174cb239-fa9b-49fc-88b8-052996b04e57` FLOAT(53),
	`cat__CustomerID_186c1f4d-5f57-49c0-98c6-e20b6fb281bf` FLOAT(53),
	`cat__CustomerID_1889ca5a-60c6-4da8-8289-4cd9af1f7152` FLOAT(53),
	`cat__CustomerID_1a26ed92-27bd-4be2-8386-45682bfc37f5` FLOAT(53),
	`cat__CustomerID_1a52951e-af95-4353-aed3-385ce0718034` FLOAT(53),
	`cat__CustomerID_1b35b6d8-800e-4972-879e-7235f8840cb3` FLOAT(53),
	`cat__CustomerID_1b626cad-36b0-4cd8-ad1a-5bae2dc27b61` FLOAT(53),
	`cat__CustomerID_1b96902d-270f-44ad-8e0c-b401104aaadb` FLOAT(53),
	`cat__CustomerID_1cc1e21a-c2e5-4616-a5cf-a544eb8a944e` FLOAT(53),
	`cat__CustomerID_1e871ef8-cdf7-4f1b-888f-18086f3dc030` FLOAT(53),
	`cat__CustomerID_1f3219ac-02a6-455b-af6a-87711e6653d1` FLOAT(53),
	`cat__CustomerID_1f696c4e-14d1-40b4-a151-52968f14a663` FLOAT(53),
	`cat__CustomerID_22974c53-2595-473f-bbd2-9f309d5e742f` FLOAT(53),
	`cat__CustomerID_232d1545-43b1-477b-ac22-4b1d25b9f81a` FLOAT(53),
	`cat__CustomerID_2398f009-a88e-4af1-b32e-e9eaf1c0409c` FLOAT(53),
	`cat__CustomerID_23eef71c-2019-4005-b8ac-c849cc15b25a` FLOAT(53),
	`cat__CustomerID_2520f9ed-572a-45a1-96af-3d25c78e1b98` FLOAT(53),
	`cat__CustomerID_259051fc-5e0b-49ed-b0a7-09140016fe70` FLOAT(53),
	`cat__CustomerID_25debb26-0ef4-4c61-a5bc-dc5d74696803` FLOAT(53),
	`cat__CustomerID_267f6422-e359-4bb5-98c9-300691a129bf` FLOAT(53),
	`cat__CustomerID_27055332-a7e4-4ed9-a629-240d59715f87` FLOAT(53),
	`cat__CustomerID_2763a02b-2940-4497-931c-db0ad39455be` FLOAT(53),
	`cat__CustomerID_276d23d2-aa88-4056-9480-acc4c7d6a499` FLOAT(53),
	`cat__CustomerID_27f9e498-f3d9-4c22-a051-8b1bd11e4fad` FLOAT(53),
	`cat__CustomerID_28db4b77-bf17-4d5e-8c81-aa62e84a1b6e` FLOAT(53),
	`cat__CustomerID_2a5e6434-a903-4944-ac8c-aedf06d19d05` FLOAT(53),
	`cat__CustomerID_2ac529aa-c34d-4dcd-9f91-ba34671c0e28` FLOAT(53),
	`cat__CustomerID_2b06b9cf-bfd9-4a6b-809c-ae5d5b4202e1` FLOAT(53),

In [45]:
dups = df_final.columns[df_final.columns.duplicated(keep=False)]
print(dups)

Index([], dtype='str')

In [46]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS sales_processed"))
    conn.commit()

In [47]:
engine.dispose()

In [48]:
df_final.to_sql(
    "sales_processed",
    con=engine,
    if_exists="replace",
    index=False
)

OperationalError: (pymysql.err.OperationalError) (1060, "Duplicate column name 'cat__CurrencyType_Usd'")
[SQL:
CREATE TABLE sales_processed (
	`num__Qty` FLOAT(53),
	`num__Unit_Price` FLOAT(53),
	`cat__ProductName_Actually` FLOAT(53),
	`cat__ProductName_Adams_Brush` FLOAT(53),
	`cat__ProductName_Alexander_Spray` FLOAT(53),
	`cat__ProductName_Allen_Brush` FLOAT(53),
	`cat__ProductName_Allen_Notebook` FLOAT(53),
	`cat__ProductName_Anderson_Lamp` FLOAT(53),
	`cat__ProductName_Arnold_Fork` FLOAT(53),
	`cat__ProductName_Arnold_Speaker` FLOAT(53),
	`cat__ProductName_Arnold_Stick` FLOAT(53),
	`cat__ProductName_Bailey_Drill` FLOAT(53),
	`cat__ProductName_Baker_Speaker` FLOAT(53),
	`cat__ProductName_Ball_Notebook` FLOAT(53),
	`cat__ProductName_Banks_Gloves` FLOAT(53),
	`cat__ProductName_Barker_Book` FLOAT(53),
	`cat__ProductName_Barker_Deodorant` FLOAT(53),
	`cat__ProductName_Barnes_Belt` FLOAT(53),
	`cat__ProductName_Barrett_Basket` FLOAT(53),
	`cat__ProductName_Bell_Glove` FLOAT(53),
	`cat__ProductName_Bennett_Lock` FLOAT(53),
	`cat__ProductName_Black` FLOAT(53),
	`cat__ProductName_Boone_Balm` FLOAT(53),
	`cat__ProductName_Boone_Polish` FLOAT(53),
	`cat__ProductName_Bowen_Tire` FLOAT(53),
	`cat__ProductName_Brooks_Cap` FLOAT(53),
	`cat__ProductName_Bryant_Brush` FLOAT(53),
	`cat__ProductName_Butler_Jacket` FLOAT(53),
	`cat__ProductName_Cameron_Fan` FLOAT(53),
	`cat__ProductName_Carter_Fan` FLOAT(53),
	`cat__ProductName_Case` FLOAT(53),
	`cat__ProductName_Chavez_Printer` FLOAT(53),
	`cat__ProductName_Clark_Glass` FLOAT(53),
	`cat__ProductName_Cole_Disk` FLOAT(53),
	`cat__ProductName_Cole_Polish` FLOAT(53),
	`cat__ProductName_Coleman_Case` FLOAT(53),
	`cat__ProductName_Collins_Rug` FLOAT(53),
	`cat__ProductName_Conner_Gel` FLOAT(53),
	`cat__ProductName_Cook_Ball` FLOAT(53),
	`cat__ProductName_Cook_Tray` FLOAT(53),
	`cat__ProductName_Cooper_Knife` FLOAT(53),
	`cat__ProductName_Cox_Screw` FLOAT(53),
	`cat__ProductName_Cross_Rack` FLOAT(53),
	`cat__ProductName_Daniels_Coat` FLOAT(53),
	`cat__ProductName_Dean_Screw` FLOAT(53),
	`cat__ProductName_Dean_Shelf` FLOAT(53),
	`cat__ProductName_Dennis_Mug` FLOAT(53),
	`cat__ProductName_Diaz_Soap` FLOAT(53),
	`cat__ProductName_Dixon_Marker` FLOAT(53),
	`cat__ProductName_Doyle_Grip` FLOAT(53),
	`cat__ProductName_Doyle_Powder` FLOAT(53),
	`cat__ProductName_Edwards_Mixer` FLOAT(53),
	`cat__ProductName_Evans_Tape` FLOAT(53),
	`cat__ProductName_Fisher_Clip` FLOAT(53),
	`cat__ProductName_Fisher_Cover` FLOAT(53),
	`cat__ProductName_Fleming_Tray` FLOAT(53),
	`cat__ProductName_Flores_Coat` FLOAT(53),
	`cat__ProductName_Flowers_Thread` FLOAT(53),
	`cat__ProductName_Ford_Gel` FLOAT(53),
	`cat__ProductName_Foster_Hat` FLOAT(53),
	`cat__ProductName_Foster_Hook` FLOAT(53),
	`cat__ProductName_Fox_Calendar` FLOAT(53),
	`cat__ProductName_Franklin_Bag` FLOAT(53),
	`cat__ProductName_Gardner_Sheet` FLOAT(53),
	`cat__ProductName_Gibbs_Cream` FLOAT(53),
	`cat__ProductName_Gibson_Clock` FLOAT(53),
	`cat__ProductName_Gilbert_Pad` FLOAT(53),
	`cat__ProductName_Gonzales_Sock` FLOAT(53),
	`cat__ProductName_Graham_Cleaner` FLOAT(53),
	`cat__ProductName_Gray_Tool` FLOAT(53),
	`cat__ProductName_Green_Folder` FLOAT(53),
	`cat__ProductName_Gregory_Helmet` FLOAT(53),
	`cat__ProductName_Griffin_Cream` FLOAT(53),
	`cat__ProductName_Hall_Cup` FLOAT(53),
	`cat__ProductName_Hamilton_Paste` FLOAT(53),
	`cat__ProductName_Hanson_Flashlight` FLOAT(53),
	`cat__ProductName_Harmon_Net` FLOAT(53),
	`cat__ProductName_Harper_Phone` FLOAT(53),
	`cat__ProductName_Harris_Pen` FLOAT(53),
	`cat__ProductName_Hayes_Lotion` FLOAT(53),
	`cat__ProductName_Henderson_Gear` FLOAT(53),
	`cat__ProductName_Hill_Phone` FLOAT(53),
	`cat__ProductName_Holland_Nail` FLOAT(53),
	`cat__ProductName_Holmes_Book` FLOAT(53),
	`cat__ProductName_Holmes_Hook` FLOAT(53),
	`cat__ProductName_Horton_Cable` FLOAT(53),
	`cat__ProductName_Howard_Can` FLOAT(53),
	`cat__ProductName_Hudson_Lamp` FLOAT(53),
	`cat__ProductName_Hughes_Strap` FLOAT(53),
	`cat__ProductName_Ingram_Booklet` FLOAT(53),
	`cat__ProductName_Jackson_Cable` FLOAT(53),
	`cat__ProductName_James_Grip` FLOAT(53),
	`cat__ProductName_Jenkins_Valve` FLOAT(53),
	`cat__ProductName_Johnson_Mirror` FLOAT(53),
	`cat__ProductName_Johnson_Screen` FLOAT(53),
	`cat__ProductName_Jordan_Bleach` FLOAT(53),
	`cat__ProductName_Kelly_String` FLOAT(53),
	`cat__ProductName_Lane_Mug` FLOAT(53),
	`cat__ProductName_Larson_Rack` FLOAT(53),
	`cat__ProductName_Lee_Clock` FLOAT(53),
	`cat__ProductName_Lewis_Ruler` FLOAT(53),
	`cat__ProductName_Line` FLOAT(53),
	`cat__ProductName_Lloyd_Mixer` FLOAT(53),
	`cat__ProductName_Long_Mat` FLOAT(53),
	`cat__ProductName_Marsh_Jar` FLOAT(53),
	`cat__ProductName_Martin_Charger` FLOAT(53),
	`cat__ProductName_Matthews_Plate` FLOAT(53),
	`cat__ProductName_Mitchell_Frame` FLOAT(53),
	`cat__ProductName_Moody_Net` FLOAT(53),
	`cat__ProductName_Moore_Chair` FLOAT(53),
	`cat__ProductName_Morgan_Stick` FLOAT(53),
	`cat__ProductName_Morris_Bottle` FLOAT(53),
	`cat__ProductName_Morris_Tray` FLOAT(53),
	`cat__ProductName_Murphy_Dish` FLOAT(53),
	`cat__ProductName_Myers_Shampoo` FLOAT(53),
	`cat__ProductName_Nelson_Knife` FLOAT(53),
	`cat__ProductName_Newman_Rod` FLOAT(53),
	`cat__ProductName_On` FLOAT(53),
	`cat__ProductName_Owens_Powder` FLOAT(53),
	`cat__ProductName_Owens_Tape` FLOAT(53),
	`cat__ProductName_Page_Pen` FLOAT(53),
	`cat__ProductName_Palmer_Screen` FLOAT(53),
	`cat__ProductName_Parker_Cable` FLOAT(53),
	`cat__ProductName_Patterson_Filter` FLOAT(53),
	`cat__ProductName_Perez_Board` FLOAT(53),
	`cat__ProductName_Perry_Switch` FLOAT(53),
	`cat__ProductName_Peterson_Sheet` FLOAT(53),
	`cat__ProductName_Phillips_Hook` FLOAT(53),
	`cat__ProductName_Pierce_File` FLOAT(53),
	`cat__ProductName_Pierce_Plate` FLOAT(53),
	`cat__ProductName_Potter_Shield` FLOAT(53),
	`cat__ProductName_Powell_Tube` FLOAT(53),
	`cat__ProductName_Price_Clip` FLOAT(53),
	`cat__ProductName_Ramirez_Bar` FLOAT(53),
	`cat__ProductName_Reed_Rack` FLOAT(53),
	`cat__ProductName_Reid_Strap` FLOAT(53),
	`cat__ProductName_Richardson_Nail` FLOAT(53),
	`cat__ProductName_Rivera_Block` FLOAT(53),
	`cat__ProductName_Rivers_Lid` FLOAT(53),
	`cat__ProductName_Roberts_Ingredient` FLOAT(53),
	`cat__ProductName_Roberts_Pen` FLOAT(53),
	`cat__ProductName_Robinson_Shelf` FLOAT(53),
	`cat__ProductName_Rodriguez_Keyboard` FLOAT(53),
	`cat__ProductName_Rogers_Lid` FLOAT(53),
	`cat__ProductName_Ross_Cover` FLOAT(53),
	`cat__ProductName_Russell_Oil` FLOAT(53),
	`cat__ProductName_Sanchez_Book` FLOAT(53),
	`cat__ProductName_Sanders_Pin` FLOAT(53),
	`cat__ProductName_Sanderson_Spray` FLOAT(53),
	`cat__ProductName_Scott_Plate` FLOAT(53),
	`cat__ProductName_Simmons_Shorts` FLOAT(53),
	`cat__ProductName_Sims_Brush` FLOAT(53),
	`cat__ProductName_Skill` FLOAT(53),
	`cat__ProductName_Smith_Bag` FLOAT(53),
	`cat__ProductName_Smith_Paper` FLOAT(53),
	`cat__ProductName_Soon` FLOAT(53),
	`cat__ProductName_Spencer_Frame` FLOAT(53),
	`cat__ProductName_Stevens_Cap` FLOAT(53),
	`cat__ProductName_Stewart_Mouse` FLOAT(53),
	`cat__ProductName_Sullivan_Wax` FLOAT(53),
	`cat__ProductName_Swanson_Bucket` FLOAT(53),
	`cat__ProductName_Taylor_Table` FLOAT(53),
	`cat__ProductName_Torres_Stand` FLOAT(53),
	`cat__ProductName_Torres_Table` FLOAT(53),
	`cat__ProductName_Tucker_Helmet` FLOAT(53),
	`cat__ProductName_Turner_Pad` FLOAT(53),
	`cat__ProductName_Vang_Charger` FLOAT(53),
	`cat__ProductName_Vasquez_Bottle` FLOAT(53),
	`cat__ProductName_Wade_Charger` FLOAT(53),
	`cat__ProductName_Walker_Camera` FLOAT(53),
	`cat__ProductName_Wallace_Polish` FLOAT(53),
	`cat__ProductName_Wallace_Sheet` FLOAT(53),
	`cat__ProductName_Ward_Plug` FLOAT(53),
	`cat__ProductName_Warren_Lamp` FLOAT(53),
	`cat__ProductName_Washington_Skirt` FLOAT(53),
	`cat__ProductName_Watson_Chain` FLOAT(53),
	`cat__ProductName_Welch_Mirror` FLOAT(53),
	`cat__ProductName_Welch_Spray` FLOAT(53),
	`cat__ProductName_West_Shine` FLOAT(53),
	`cat__ProductName_White_Monitor` FLOAT(53),
	`cat__ProductName_Williams_Bottle` FLOAT(53),
	`cat__ProductName_Wood_Tire` FLOAT(53),
	`cat__ProductName_Woods_Detergent` FLOAT(53),
	`cat__ProductName_Young_Printer` FLOAT(53),
	`cat__SaleDate_1/1/2025` FLOAT(53),
	`cat__SaleDate_1/10/2025` FLOAT(53),
	`cat__SaleDate_1/11/2025` FLOAT(53),
	`cat__SaleDate_1/15/2025` FLOAT(53),
	`cat__SaleDate_1/16/2025` FLOAT(53),
	`cat__SaleDate_1/19/2025` FLOAT(53),
	`cat__SaleDate_1/20/2025` FLOAT(53),
	`cat__SaleDate_1/21/2025` FLOAT(53),
	`cat__SaleDate_1/22/2025` FLOAT(53),
	`cat__SaleDate_1/23/2025` FLOAT(53),
	`cat__SaleDate_1/24/2025` FLOAT(53),
	`cat__SaleDate_1/5/2025` FLOAT(53),
	`cat__SaleDate_1/6/2025` FLOAT(53),
	`cat__SaleDate_1/7/2025` FLOAT(53),
	`cat__SaleDate_1/9/2025` FLOAT(53),
	`cat__SaleDate_10/10/2024` FLOAT(53),
	`cat__SaleDate_10/11/2024` FLOAT(53),
	`cat__SaleDate_10/12/2024` FLOAT(53),
	`cat__SaleDate_10/13/2024` FLOAT(53),
	`cat__SaleDate_10/14/2024` FLOAT(53),
	`cat__SaleDate_10/15/2024` FLOAT(53),
	`cat__SaleDate_10/17/2024` FLOAT(53),
	`cat__SaleDate_10/18/2024` FLOAT(53),
	`cat__SaleDate_10/19/2024` FLOAT(53),
	`cat__SaleDate_10/20/2024` FLOAT(53),
	`cat__SaleDate_10/21/2024` FLOAT(53),
	`cat__SaleDate_10/25/2024` FLOAT(53),
	`cat__SaleDate_10/26/2024` FLOAT(53),
	`cat__SaleDate_10/27/2024` FLOAT(53),
	`cat__SaleDate_10/4/2024` FLOAT(53),
	`cat__SaleDate_10/6/2024` FLOAT(53),
	`cat__SaleDate_10/8/2024` FLOAT(53),
	`cat__SaleDate_11/1/2024` FLOAT(53),
	`cat__SaleDate_11/10/2024` FLOAT(53),
	`cat__SaleDate_11/11/2024` FLOAT(53),
	`cat__SaleDate_11/13/2024` FLOAT(53),
	`cat__SaleDate_11/18/2024` FLOAT(53),
	`cat__SaleDate_11/19/2024` FLOAT(53),
	`cat__SaleDate_11/2/2024` FLOAT(53),
	`cat__SaleDate_11/22/2024` FLOAT(53),
	`cat__SaleDate_11/23/2024` FLOAT(53),
	`cat__SaleDate_11/24/2024` FLOAT(53),
	`cat__SaleDate_11/25/2024` FLOAT(53),
	`cat__SaleDate_11/26/2024` FLOAT(53),
	`cat__SaleDate_11/3/2024` FLOAT(53),
	`cat__SaleDate_11/30/2024` FLOAT(53),
	`cat__SaleDate_11/5/2024` FLOAT(53),
	`cat__SaleDate_11/6/2024` FLOAT(53),
	`cat__SaleDate_11/7/2024` FLOAT(53),
	`cat__SaleDate_11/8/2024` FLOAT(53),
	`cat__SaleDate_11/9/2024` FLOAT(53),
	`cat__SaleDate_12/1/2024` FLOAT(53),
	`cat__SaleDate_12/13/2024` FLOAT(53),
	`cat__SaleDate_12/15/2024` FLOAT(53),
	`cat__SaleDate_12/17/2024` FLOAT(53),
	`cat__SaleDate_12/18/2024` FLOAT(53),
	`cat__SaleDate_12/2/2024` FLOAT(53),
	`cat__SaleDate_12/20/2024` FLOAT(53),
	`cat__SaleDate_12/24/2024` FLOAT(53),
	`cat__SaleDate_12/25/2024` FLOAT(53),
	`cat__SaleDate_12/26/2024` FLOAT(53),
	`cat__SaleDate_12/27/2024` FLOAT(53),
	`cat__SaleDate_12/28/2024` FLOAT(53),
	`cat__SaleDate_12/29/2024` FLOAT(53),
	`cat__SaleDate_12/3/2024` FLOAT(53),
	`cat__SaleDate_12/31/2024` FLOAT(53),
	`cat__SaleDate_12/7/2024` FLOAT(53),
	`cat__SaleDate_12/9/2024` FLOAT(53),
	`cat__SaleDate_2/10/2025` FLOAT(53),
	`cat__SaleDate_2/11/2025` FLOAT(53),
	`cat__SaleDate_2/12/2025` FLOAT(53),
	`cat__SaleDate_2/17/2025` FLOAT(53),
	`cat__SaleDate_2/18/2025` FLOAT(53),
	`cat__SaleDate_2/19/2025` FLOAT(53),
	`cat__SaleDate_2/2/2025` FLOAT(53),
	`cat__SaleDate_2/20/2025` FLOAT(53),
	`cat__SaleDate_2/21/2025` FLOAT(53),
	`cat__SaleDate_2/22/2025` FLOAT(53),
	`cat__SaleDate_2/23/2025` FLOAT(53),
	`cat__SaleDate_2/24/2025` FLOAT(53),
	`cat__SaleDate_2/25/2025` FLOAT(53),
	`cat__SaleDate_2/3/2025` FLOAT(53),
	`cat__SaleDate_2/6/2025` FLOAT(53),
	`cat__SaleDate_2/7/2025` FLOAT(53),
	`cat__SaleDate_2/9/2025` FLOAT(53),
	`cat__SaleDate_3/12/2025` FLOAT(53),
	`cat__SaleDate_3/16/2025` FLOAT(53),
	`cat__SaleDate_3/17/2025` FLOAT(53),
	`cat__SaleDate_3/18/2025` FLOAT(53),
	`cat__SaleDate_3/20/2025` FLOAT(53),
	`cat__SaleDate_3/21/2025` FLOAT(53),
	`cat__SaleDate_3/22/2025` FLOAT(53),
	`cat__SaleDate_3/23/2025` FLOAT(53),
	`cat__SaleDate_3/24/2025` FLOAT(53),
	`cat__SaleDate_3/25/2025` FLOAT(53),
	`cat__SaleDate_3/27/2025` FLOAT(53),
	`cat__SaleDate_3/28/2025` FLOAT(53),
	`cat__SaleDate_3/3/2025` FLOAT(53),
	`cat__SaleDate_3/30/2025` FLOAT(53),
	`cat__SaleDate_3/31/2025` FLOAT(53),
	`cat__SaleDate_3/4/2025` FLOAT(53),
	`cat__SaleDate_3/5/2025` FLOAT(53),
	`cat__SaleDate_3/6/2025` FLOAT(53),
	`cat__SaleDate_3/7/2025` FLOAT(53),
	`cat__SaleDate_3/8/2025` FLOAT(53),
	`cat__SaleDate_3/9/2025` FLOAT(53),
	`cat__SaleDate_4/1/2025` FLOAT(53),
	`cat__SaleDate_4/11/2025` FLOAT(53),
	`cat__SaleDate_4/15/2025` FLOAT(53),
	`cat__SaleDate_4/16/2025` FLOAT(53),
	`cat__SaleDate_4/19/2025` FLOAT(53),
	`cat__SaleDate_4/22/2025` FLOAT(53),
	`cat__SaleDate_4/23/2025` FLOAT(53),
	`cat__SaleDate_4/27/2025` FLOAT(53),
	`cat__SaleDate_4/28/2025` FLOAT(53),
	`cat__SaleDate_4/3/2025` FLOAT(53),
	`cat__SaleDate_4/5/2025` FLOAT(53),
	`cat__SaleDate_4/7/2025` FLOAT(53),
	`cat__SaleDate_4/8/2025` FLOAT(53),
	`cat__SaleDate_4/9/2025` FLOAT(53),
	`cat__SaleDate_5/10/2025` FLOAT(53),
	`cat__SaleDate_5/11/2025` FLOAT(53),
	`cat__SaleDate_5/12/2025` FLOAT(53),
	`cat__SaleDate_5/13/2025` FLOAT(53),
	`cat__SaleDate_5/14/2025` FLOAT(53),
	`cat__SaleDate_5/15/2025` FLOAT(53),
	`cat__SaleDate_5/18/2025` FLOAT(53),
	`cat__SaleDate_5/22/2025` FLOAT(53),
	`cat__SaleDate_5/23/2025` FLOAT(53),
	`cat__SaleDate_5/24/2025` FLOAT(53),
	`cat__SaleDate_5/25/2024` FLOAT(53),
	`cat__SaleDate_5/25/2025` FLOAT(53),
	`cat__SaleDate_5/26/2024` FLOAT(53),
	`cat__SaleDate_5/28/2024` FLOAT(53),
	`cat__SaleDate_5/3/2025` FLOAT(53),
	`cat__SaleDate_5/31/2024` FLOAT(53),
	`cat__SaleDate_5/5/2025` FLOAT(53),
	`cat__SaleDate_5/7/2025` FLOAT(53),
	`cat__SaleDate_6/1/2024` FLOAT(53),
	`cat__SaleDate_6/11/2024` FLOAT(53),
	`cat__SaleDate_6/13/2024` FLOAT(53),
	`cat__SaleDate_6/14/2024` FLOAT(53),
	`cat__SaleDate_6/15/2024` FLOAT(53),
	`cat__SaleDate_6/16/2024` FLOAT(53),
	`cat__SaleDate_6/17/2024` FLOAT(53),
	`cat__SaleDate_6/18/2024` FLOAT(53),
	`cat__SaleDate_6/19/2024` FLOAT(53),
	`cat__SaleDate_6/22/2024` FLOAT(53),
	`cat__SaleDate_6/24/2024` FLOAT(53),
	`cat__SaleDate_6/27/2024` FLOAT(53),
	`cat__SaleDate_6/29/2024` FLOAT(53),
	`cat__SaleDate_6/30/2024` FLOAT(53),
	`cat__SaleDate_6/4/2024` FLOAT(53),
	`cat__SaleDate_6/5/2024` FLOAT(53),
	`cat__SaleDate_6/6/2024` FLOAT(53),
	`cat__SaleDate_6/7/2024` FLOAT(53),
	`cat__SaleDate_6/9/2024` FLOAT(53),
	`cat__SaleDate_7/13/2024` FLOAT(53),
	`cat__SaleDate_7/14/2024` FLOAT(53),
	`cat__SaleDate_7/15/2024` FLOAT(53),
	`cat__SaleDate_7/16/2024` FLOAT(53),
	`cat__SaleDate_7/17/2024` FLOAT(53),
	`cat__SaleDate_7/18/2024` FLOAT(53),
	`cat__SaleDate_7/20/2024` FLOAT(53),
	`cat__SaleDate_7/21/2024` FLOAT(53),
	`cat__SaleDate_7/26/2024` FLOAT(53),
	`cat__SaleDate_7/27/2024` FLOAT(53),
	`cat__SaleDate_7/28/2024` FLOAT(53),
	`cat__SaleDate_7/31/2024` FLOAT(53),
	`cat__SaleDate_7/4/2024` FLOAT(53),
	`cat__SaleDate_7/5/2024` FLOAT(53),
	`cat__SaleDate_7/7/2024` FLOAT(53),
	`cat__SaleDate_7/8/2024` FLOAT(53),
	`cat__SaleDate_7/9/2024` FLOAT(53),
	`cat__SaleDate_8/10/2024` FLOAT(53),
	`cat__SaleDate_8/11/2024` FLOAT(53),
	`cat__SaleDate_8/12/2024` FLOAT(53),
	`cat__SaleDate_8/15/2024` FLOAT(53),
	`cat__SaleDate_8/2/2024` FLOAT(53),
	`cat__SaleDate_8/20/2024` FLOAT(53),
	`cat__SaleDate_8/21/2024` FLOAT(53),
	`cat__SaleDate_8/22/2024` FLOAT(53),
	`cat__SaleDate_8/23/2024` FLOAT(53),
	`cat__SaleDate_8/24/2024` FLOAT(53),
	`cat__SaleDate_8/25/2024` FLOAT(53),
	`cat__SaleDate_8/29/2024` FLOAT(53),
	`cat__SaleDate_8/3/2024` FLOAT(53),
	`cat__SaleDate_8/31/2024` FLOAT(53),
	`cat__SaleDate_8/5/2024` FLOAT(53),
	`cat__SaleDate_8/7/2024` FLOAT(53),
	`cat__SaleDate_8/8/2024` FLOAT(53),
	`cat__SaleDate_9/1/2024` FLOAT(53),
	`cat__SaleDate_9/10/2024` FLOAT(53),
	`cat__SaleDate_9/15/2024` FLOAT(53),
	`cat__SaleDate_9/2/2024` FLOAT(53),
	`cat__SaleDate_9/20/2024` FLOAT(53),
	`cat__SaleDate_9/22/2024` FLOAT(53),
	`cat__SaleDate_9/25/2024` FLOAT(53),
	`cat__SaleDate_9/26/2024` FLOAT(53),
	`cat__SaleDate_9/27/2024` FLOAT(53),
	`cat__SaleDate_9/28/2024` FLOAT(53),
	`cat__SaleDate_9/29/2024` FLOAT(53),
	`cat__SaleDate_9/30/2024` FLOAT(53),
	`cat__SaleDate_9/5/2024` FLOAT(53),
	`cat__SaleDate_9/6/2024` FLOAT(53),
	`cat__SaleDate_9/8/2024` FLOAT(53),
	`cat__CurrencyType_OMR` FLOAT(53),
	`cat__CurrencyType_USD` FLOAT(53),
	`cat__CurrencyType_Usd` FLOAT(53),
	`cat__CurrencyType_usd` FLOAT(53),
	`cat__CustomerID_0104ec48-84a4-4638-9ed4-dad335d44c43` FLOAT(53),
	`cat__CustomerID_0403d558-166d-4616-9f3e-98d3d7414d35` FLOAT(53),
	`cat__CustomerID_0437bab5-0dae-422e-9d2d-719091ea2dd9` FLOAT(53),
	`cat__CustomerID_045081fa-0df3-4904-820b-067b4176fb85` FLOAT(53),
	`cat__CustomerID_051e499e-f4d0-4a1e-a595-21fc69b2db45` FLOAT(53),
	`cat__CustomerID_0534e616-cbd9-4eba-82bf-f3903ad76eb9` FLOAT(53),
	`cat__CustomerID_05d39b68-833c-45d0-9af3-c0b3bad43a5c` FLOAT(53),
	`cat__CustomerID_05d75424-135a-40ea-9f43-7297d527e0e0` FLOAT(53),
	`cat__CustomerID_07991be5-0500-4bdc-95bc-a3ee50f4d268` FLOAT(53),
	`cat__CustomerID_0822d2d7-9454-4aa3-95bc-b869d6957852` FLOAT(53),
	`cat__CustomerID_089f6dd7-f901-4521-a02c-eb1bf002c6c7` FLOAT(53),
	`cat__CustomerID_0957271b-9145-4838-a842-c40eddb6a2f6` FLOAT(53),
	`cat__CustomerID_0b4a7550-cb81-475b-b8f0-4d4e9668f7e8` FLOAT(53),
	`cat__CustomerID_0bbb7256-0ad2-4b07-a1b0-cba178732f64` FLOAT(53),
	`cat__CustomerID_0bffb839-d519-494d-8b15-9498de261bd6` FLOAT(53),
	`cat__CustomerID_0dadb5f8-e924-45a5-806b-681dd7aebdea` FLOAT(53),
	`cat__CustomerID_0e57e6c8-d5c5-43fa-919e-3640f6ebba01` FLOAT(53),
	`cat__CustomerID_0ead620f-7c7d-4908-bdda-c73282d77d87` FLOAT(53),
	`cat__CustomerID_0ec24f4e-0f17-4c4c-8b16-7b53519d7ce2` FLOAT(53),
	`cat__CustomerID_103bc58d-7df8-47ae-988b-8738b4b2b050` FLOAT(53),
	`cat__CustomerID_104d0c3e-ccfc-43a7-b3e7-e1c56e986cdd` FLOAT(53),
	`cat__CustomerID_10c8ed7e-bba0-4f05-99b7-c72d90c66aaf` FLOAT(53),
	`cat__CustomerID_10f25bba-5c31-4c70-b065-e050a9b6803a` FLOAT(53),
	`cat__CustomerID_11444ef2-a6c9-42e9-8015-6446784d11a7` FLOAT(53),
	`cat__CustomerID_124ea517-d2c8-4ce0-8b00-fcdcfecff89e` FLOAT(53),
	`cat__CustomerID_134fd311-9094-4aef-9068-78b44f308566` FLOAT(53),
	`cat__CustomerID_13c53f9f-0f5f-492c-8660-001021d8745e` FLOAT(53),
	`cat__CustomerID_14cd77f7-8505-47df-a916-b64aae66ebd2` FLOAT(53),
	`cat__CustomerID_15c37dcb-1c11-4482-b1fc-da11997f0d63` FLOAT(53),
	`cat__CustomerID_15fda73e-7b88-4ad7-85c9-d23d8187e574` FLOAT(53),
	`cat__CustomerID_174cb239-fa9b-49fc-88b8-052996b04e57` FLOAT(53),
	`cat__CustomerID_186c1f4d-5f57-49c0-98c6-e20b6fb281bf` FLOAT(53),
	`cat__CustomerID_1889ca5a-60c6-4da8-8289-4cd9af1f7152` FLOAT(53),
	`cat__CustomerID_1a26ed92-27bd-4be2-8386-45682bfc37f5` FLOAT(53),
	`cat__CustomerID_1a52951e-af95-4353-aed3-385ce0718034` FLOAT(53),
	`cat__CustomerID_1b35b6d8-800e-4972-879e-7235f8840cb3` FLOAT(53),
	`cat__CustomerID_1b626cad-36b0-4cd8-ad1a-5bae2dc27b61` FLOAT(53),
	`cat__CustomerID_1b96902d-270f-44ad-8e0c-b401104aaadb` FLOAT(53),
	`cat__CustomerID_1cc1e21a-c2e5-4616-a5cf-a544eb8a944e` FLOAT(53),
	`cat__CustomerID_1e871ef8-cdf7-4f1b-888f-18086f3dc030` FLOAT(53),
	`cat__CustomerID_1f3219ac-02a6-455b-af6a-87711e6653d1` FLOAT(53),
	`cat__CustomerID_1f696c4e-14d1-40b4-a151-52968f14a663` FLOAT(53),
	`cat__CustomerID_22974c53-2595-473f-bbd2-9f309d5e742f` FLOAT(53),
	`cat__CustomerID_232d1545-43b1-477b-ac22-4b1d25b9f81a` FLOAT(53),
	`cat__CustomerID_2398f009-a88e-4af1-b32e-e9eaf1c0409c` FLOAT(53),
	`cat__CustomerID_23eef71c-2019-4005-b8ac-c849cc15b25a` FLOAT(53),
	`cat__CustomerID_2520f9ed-572a-45a1-96af-3d25c78e1b98` FLOAT(53),
	`cat__CustomerID_259051fc-5e0b-49ed-b0a7-09140016fe70` FLOAT(53),
	`cat__CustomerID_25debb26-0ef4-4c61-a5bc-dc5d74696803` FLOAT(53),
	`cat__CustomerID_267f6422-e359-4bb5-98c9-300691a129bf` FLOAT(53),
	`cat__CustomerID_27055332-a7e4-4ed9-a629-240d59715f87` FLOAT(53),
	`cat__CustomerID_2763a02b-2940-4497-931c-db0ad39455be` FLOAT(53),
	`cat__CustomerID_276d23d2-aa88-4056-9480-acc4c7d6a499` FLOAT(53),
	`cat__CustomerID_27f9e498-f3d9-4c22-a051-8b1bd11e4fad` FLOAT(53),
	`cat__CustomerID_28db4b77-bf17-4d5e-8c81-aa62e84a1b6e` FLOAT(53),
	`cat__CustomerID_2a5e6434-a903-4944-ac8c-aedf06d19d05` FLOAT(53),
	`cat__CustomerID_2ac529aa-c34d-4dcd-9f91-ba34671c0e28` FLOAT(53),
	`cat__CustomerID_2b06b9cf-bfd9-4a6b-809c-ae5d5b4202e1` FLOAT(53),

In [49]:
df_final.to_sql(
    "sales_processed",
    con=engine,
    if_exists="replace",
    index=False,
    method="multi"
)

OperationalError: (pymysql.err.OperationalError) (1060, "Duplicate column name 'cat__CurrencyType_Usd'")
[SQL:
CREATE TABLE sales_processed (
	`num__Qty` FLOAT(53),
	`num__Unit_Price` FLOAT(53),
	`cat__ProductName_Actually` FLOAT(53),
	`cat__ProductName_Adams_Brush` FLOAT(53),
	`cat__ProductName_Alexander_Spray` FLOAT(53),
	`cat__ProductName_Allen_Brush` FLOAT(53),
	`cat__ProductName_Allen_Notebook` FLOAT(53),
	`cat__ProductName_Anderson_Lamp` FLOAT(53),
	`cat__ProductName_Arnold_Fork` FLOAT(53),
	`cat__ProductName_Arnold_Speaker` FLOAT(53),
	`cat__ProductName_Arnold_Stick` FLOAT(53),
	`cat__ProductName_Bailey_Drill` FLOAT(53),
	`cat__ProductName_Baker_Speaker` FLOAT(53),
	`cat__ProductName_Ball_Notebook` FLOAT(53),
	`cat__ProductName_Banks_Gloves` FLOAT(53),
	`cat__ProductName_Barker_Book` FLOAT(53),
	`cat__ProductName_Barker_Deodorant` FLOAT(53),
	`cat__ProductName_Barnes_Belt` FLOAT(53),
	`cat__ProductName_Barrett_Basket` FLOAT(53),
	`cat__ProductName_Bell_Glove` FLOAT(53),
	`cat__ProductName_Bennett_Lock` FLOAT(53),
	`cat__ProductName_Black` FLOAT(53),
	`cat__ProductName_Boone_Balm` FLOAT(53),
	`cat__ProductName_Boone_Polish` FLOAT(53),
	`cat__ProductName_Bowen_Tire` FLOAT(53),
	`cat__ProductName_Brooks_Cap` FLOAT(53),
	`cat__ProductName_Bryant_Brush` FLOAT(53),
	`cat__ProductName_Butler_Jacket` FLOAT(53),
	`cat__ProductName_Cameron_Fan` FLOAT(53),
	`cat__ProductName_Carter_Fan` FLOAT(53),
	`cat__ProductName_Case` FLOAT(53),
	`cat__ProductName_Chavez_Printer` FLOAT(53),
	`cat__ProductName_Clark_Glass` FLOAT(53),
	`cat__ProductName_Cole_Disk` FLOAT(53),
	`cat__ProductName_Cole_Polish` FLOAT(53),
	`cat__ProductName_Coleman_Case` FLOAT(53),
	`cat__ProductName_Collins_Rug` FLOAT(53),
	`cat__ProductName_Conner_Gel` FLOAT(53),
	`cat__ProductName_Cook_Ball` FLOAT(53),
	`cat__ProductName_Cook_Tray` FLOAT(53),
	`cat__ProductName_Cooper_Knife` FLOAT(53),
	`cat__ProductName_Cox_Screw` FLOAT(53),
	`cat__ProductName_Cross_Rack` FLOAT(53),
	`cat__ProductName_Daniels_Coat` FLOAT(53),
	`cat__ProductName_Dean_Screw` FLOAT(53),
	`cat__ProductName_Dean_Shelf` FLOAT(53),
	`cat__ProductName_Dennis_Mug` FLOAT(53),
	`cat__ProductName_Diaz_Soap` FLOAT(53),
	`cat__ProductName_Dixon_Marker` FLOAT(53),
	`cat__ProductName_Doyle_Grip` FLOAT(53),
	`cat__ProductName_Doyle_Powder` FLOAT(53),
	`cat__ProductName_Edwards_Mixer` FLOAT(53),
	`cat__ProductName_Evans_Tape` FLOAT(53),
	`cat__ProductName_Fisher_Clip` FLOAT(53),
	`cat__ProductName_Fisher_Cover` FLOAT(53),
	`cat__ProductName_Fleming_Tray` FLOAT(53),
	`cat__ProductName_Flores_Coat` FLOAT(53),
	`cat__ProductName_Flowers_Thread` FLOAT(53),
	`cat__ProductName_Ford_Gel` FLOAT(53),
	`cat__ProductName_Foster_Hat` FLOAT(53),
	`cat__ProductName_Foster_Hook` FLOAT(53),
	`cat__ProductName_Fox_Calendar` FLOAT(53),
	`cat__ProductName_Franklin_Bag` FLOAT(53),
	`cat__ProductName_Gardner_Sheet` FLOAT(53),
	`cat__ProductName_Gibbs_Cream` FLOAT(53),
	`cat__ProductName_Gibson_Clock` FLOAT(53),
	`cat__ProductName_Gilbert_Pad` FLOAT(53),
	`cat__ProductName_Gonzales_Sock` FLOAT(53),
	`cat__ProductName_Graham_Cleaner` FLOAT(53),
	`cat__ProductName_Gray_Tool` FLOAT(53),
	`cat__ProductName_Green_Folder` FLOAT(53),
	`cat__ProductName_Gregory_Helmet` FLOAT(53),
	`cat__ProductName_Griffin_Cream` FLOAT(53),
	`cat__ProductName_Hall_Cup` FLOAT(53),
	`cat__ProductName_Hamilton_Paste` FLOAT(53),
	`cat__ProductName_Hanson_Flashlight` FLOAT(53),
	`cat__ProductName_Harmon_Net` FLOAT(53),
	`cat__ProductName_Harper_Phone` FLOAT(53),
	`cat__ProductName_Harris_Pen` FLOAT(53),
	`cat__ProductName_Hayes_Lotion` FLOAT(53),
	`cat__ProductName_Henderson_Gear` FLOAT(53),
	`cat__ProductName_Hill_Phone` FLOAT(53),
	`cat__ProductName_Holland_Nail` FLOAT(53),
	`cat__ProductName_Holmes_Book` FLOAT(53),
	`cat__ProductName_Holmes_Hook` FLOAT(53),
	`cat__ProductName_Horton_Cable` FLOAT(53),
	`cat__ProductName_Howard_Can` FLOAT(53),
	`cat__ProductName_Hudson_Lamp` FLOAT(53),
	`cat__ProductName_Hughes_Strap` FLOAT(53),
	`cat__ProductName_Ingram_Booklet` FLOAT(53),
	`cat__ProductName_Jackson_Cable` FLOAT(53),
	`cat__ProductName_James_Grip` FLOAT(53),
	`cat__ProductName_Jenkins_Valve` FLOAT(53),
	`cat__ProductName_Johnson_Mirror` FLOAT(53),
	`cat__ProductName_Johnson_Screen` FLOAT(53),
	`cat__ProductName_Jordan_Bleach` FLOAT(53),
	`cat__ProductName_Kelly_String` FLOAT(53),
	`cat__ProductName_Lane_Mug` FLOAT(53),
	`cat__ProductName_Larson_Rack` FLOAT(53),
	`cat__ProductName_Lee_Clock` FLOAT(53),
	`cat__ProductName_Lewis_Ruler` FLOAT(53),
	`cat__ProductName_Line` FLOAT(53),
	`cat__ProductName_Lloyd_Mixer` FLOAT(53),
	`cat__ProductName_Long_Mat` FLOAT(53),
	`cat__ProductName_Marsh_Jar` FLOAT(53),
	`cat__ProductName_Martin_Charger` FLOAT(53),
	`cat__ProductName_Matthews_Plate` FLOAT(53),
	`cat__ProductName_Mitchell_Frame` FLOAT(53),
	`cat__ProductName_Moody_Net` FLOAT(53),
	`cat__ProductName_Moore_Chair` FLOAT(53),
	`cat__ProductName_Morgan_Stick` FLOAT(53),
	`cat__ProductName_Morris_Bottle` FLOAT(53),
	`cat__ProductName_Morris_Tray` FLOAT(53),
	`cat__ProductName_Murphy_Dish` FLOAT(53),
	`cat__ProductName_Myers_Shampoo` FLOAT(53),
	`cat__ProductName_Nelson_Knife` FLOAT(53),
	`cat__ProductName_Newman_Rod` FLOAT(53),
	`cat__ProductName_On` FLOAT(53),
	`cat__ProductName_Owens_Powder` FLOAT(53),
	`cat__ProductName_Owens_Tape` FLOAT(53),
	`cat__ProductName_Page_Pen` FLOAT(53),
	`cat__ProductName_Palmer_Screen` FLOAT(53),
	`cat__ProductName_Parker_Cable` FLOAT(53),
	`cat__ProductName_Patterson_Filter` FLOAT(53),
	`cat__ProductName_Perez_Board` FLOAT(53),
	`cat__ProductName_Perry_Switch` FLOAT(53),
	`cat__ProductName_Peterson_Sheet` FLOAT(53),
	`cat__ProductName_Phillips_Hook` FLOAT(53),
	`cat__ProductName_Pierce_File` FLOAT(53),
	`cat__ProductName_Pierce_Plate` FLOAT(53),
	`cat__ProductName_Potter_Shield` FLOAT(53),
	`cat__ProductName_Powell_Tube` FLOAT(53),
	`cat__ProductName_Price_Clip` FLOAT(53),
	`cat__ProductName_Ramirez_Bar` FLOAT(53),
	`cat__ProductName_Reed_Rack` FLOAT(53),
	`cat__ProductName_Reid_Strap` FLOAT(53),
	`cat__ProductName_Richardson_Nail` FLOAT(53),
	`cat__ProductName_Rivera_Block` FLOAT(53),
	`cat__ProductName_Rivers_Lid` FLOAT(53),
	`cat__ProductName_Roberts_Ingredient` FLOAT(53),
	`cat__ProductName_Roberts_Pen` FLOAT(53),
	`cat__ProductName_Robinson_Shelf` FLOAT(53),
	`cat__ProductName_Rodriguez_Keyboard` FLOAT(53),
	`cat__ProductName_Rogers_Lid` FLOAT(53),
	`cat__ProductName_Ross_Cover` FLOAT(53),
	`cat__ProductName_Russell_Oil` FLOAT(53),
	`cat__ProductName_Sanchez_Book` FLOAT(53),
	`cat__ProductName_Sanders_Pin` FLOAT(53),
	`cat__ProductName_Sanderson_Spray` FLOAT(53),
	`cat__ProductName_Scott_Plate` FLOAT(53),
	`cat__ProductName_Simmons_Shorts` FLOAT(53),
	`cat__ProductName_Sims_Brush` FLOAT(53),
	`cat__ProductName_Skill` FLOAT(53),
	`cat__ProductName_Smith_Bag` FLOAT(53),
	`cat__ProductName_Smith_Paper` FLOAT(53),
	`cat__ProductName_Soon` FLOAT(53),
	`cat__ProductName_Spencer_Frame` FLOAT(53),
	`cat__ProductName_Stevens_Cap` FLOAT(53),
	`cat__ProductName_Stewart_Mouse` FLOAT(53),
	`cat__ProductName_Sullivan_Wax` FLOAT(53),
	`cat__ProductName_Swanson_Bucket` FLOAT(53),
	`cat__ProductName_Taylor_Table` FLOAT(53),
	`cat__ProductName_Torres_Stand` FLOAT(53),
	`cat__ProductName_Torres_Table` FLOAT(53),
	`cat__ProductName_Tucker_Helmet` FLOAT(53),
	`cat__ProductName_Turner_Pad` FLOAT(53),
	`cat__ProductName_Vang_Charger` FLOAT(53),
	`cat__ProductName_Vasquez_Bottle` FLOAT(53),
	`cat__ProductName_Wade_Charger` FLOAT(53),
	`cat__ProductName_Walker_Camera` FLOAT(53),
	`cat__ProductName_Wallace_Polish` FLOAT(53),
	`cat__ProductName_Wallace_Sheet` FLOAT(53),
	`cat__ProductName_Ward_Plug` FLOAT(53),
	`cat__ProductName_Warren_Lamp` FLOAT(53),
	`cat__ProductName_Washington_Skirt` FLOAT(53),
	`cat__ProductName_Watson_Chain` FLOAT(53),
	`cat__ProductName_Welch_Mirror` FLOAT(53),
	`cat__ProductName_Welch_Spray` FLOAT(53),
	`cat__ProductName_West_Shine` FLOAT(53),
	`cat__ProductName_White_Monitor` FLOAT(53),
	`cat__ProductName_Williams_Bottle` FLOAT(53),
	`cat__ProductName_Wood_Tire` FLOAT(53),
	`cat__ProductName_Woods_Detergent` FLOAT(53),
	`cat__ProductName_Young_Printer` FLOAT(53),
	`cat__SaleDate_1/1/2025` FLOAT(53),
	`cat__SaleDate_1/10/2025` FLOAT(53),
	`cat__SaleDate_1/11/2025` FLOAT(53),
	`cat__SaleDate_1/15/2025` FLOAT(53),
	`cat__SaleDate_1/16/2025` FLOAT(53),
	`cat__SaleDate_1/19/2025` FLOAT(53),
	`cat__SaleDate_1/20/2025` FLOAT(53),
	`cat__SaleDate_1/21/2025` FLOAT(53),
	`cat__SaleDate_1/22/2025` FLOAT(53),
	`cat__SaleDate_1/23/2025` FLOAT(53),
	`cat__SaleDate_1/24/2025` FLOAT(53),
	`cat__SaleDate_1/5/2025` FLOAT(53),
	`cat__SaleDate_1/6/2025` FLOAT(53),
	`cat__SaleDate_1/7/2025` FLOAT(53),
	`cat__SaleDate_1/9/2025` FLOAT(53),
	`cat__SaleDate_10/10/2024` FLOAT(53),
	`cat__SaleDate_10/11/2024` FLOAT(53),
	`cat__SaleDate_10/12/2024` FLOAT(53),
	`cat__SaleDate_10/13/2024` FLOAT(53),
	`cat__SaleDate_10/14/2024` FLOAT(53),
	`cat__SaleDate_10/15/2024` FLOAT(53),
	`cat__SaleDate_10/17/2024` FLOAT(53),
	`cat__SaleDate_10/18/2024` FLOAT(53),
	`cat__SaleDate_10/19/2024` FLOAT(53),
	`cat__SaleDate_10/20/2024` FLOAT(53),
	`cat__SaleDate_10/21/2024` FLOAT(53),
	`cat__SaleDate_10/25/2024` FLOAT(53),
	`cat__SaleDate_10/26/2024` FLOAT(53),
	`cat__SaleDate_10/27/2024` FLOAT(53),
	`cat__SaleDate_10/4/2024` FLOAT(53),
	`cat__SaleDate_10/6/2024` FLOAT(53),
	`cat__SaleDate_10/8/2024` FLOAT(53),
	`cat__SaleDate_11/1/2024` FLOAT(53),
	`cat__SaleDate_11/10/2024` FLOAT(53),
	`cat__SaleDate_11/11/2024` FLOAT(53),
	`cat__SaleDate_11/13/2024` FLOAT(53),
	`cat__SaleDate_11/18/2024` FLOAT(53),
	`cat__SaleDate_11/19/2024` FLOAT(53),
	`cat__SaleDate_11/2/2024` FLOAT(53),
	`cat__SaleDate_11/22/2024` FLOAT(53),
	`cat__SaleDate_11/23/2024` FLOAT(53),
	`cat__SaleDate_11/24/2024` FLOAT(53),
	`cat__SaleDate_11/25/2024` FLOAT(53),
	`cat__SaleDate_11/26/2024` FLOAT(53),
	`cat__SaleDate_11/3/2024` FLOAT(53),
	`cat__SaleDate_11/30/2024` FLOAT(53),
	`cat__SaleDate_11/5/2024` FLOAT(53),
	`cat__SaleDate_11/6/2024` FLOAT(53),
	`cat__SaleDate_11/7/2024` FLOAT(53),
	`cat__SaleDate_11/8/2024` FLOAT(53),
	`cat__SaleDate_11/9/2024` FLOAT(53),
	`cat__SaleDate_12/1/2024` FLOAT(53),
	`cat__SaleDate_12/13/2024` FLOAT(53),
	`cat__SaleDate_12/15/2024` FLOAT(53),
	`cat__SaleDate_12/17/2024` FLOAT(53),
	`cat__SaleDate_12/18/2024` FLOAT(53),
	`cat__SaleDate_12/2/2024` FLOAT(53),
	`cat__SaleDate_12/20/2024` FLOAT(53),
	`cat__SaleDate_12/24/2024` FLOAT(53),
	`cat__SaleDate_12/25/2024` FLOAT(53),
	`cat__SaleDate_12/26/2024` FLOAT(53),
	`cat__SaleDate_12/27/2024` FLOAT(53),
	`cat__SaleDate_12/28/2024` FLOAT(53),
	`cat__SaleDate_12/29/2024` FLOAT(53),
	`cat__SaleDate_12/3/2024` FLOAT(53),
	`cat__SaleDate_12/31/2024` FLOAT(53),
	`cat__SaleDate_12/7/2024` FLOAT(53),
	`cat__SaleDate_12/9/2024` FLOAT(53),
	`cat__SaleDate_2/10/2025` FLOAT(53),
	`cat__SaleDate_2/11/2025` FLOAT(53),
	`cat__SaleDate_2/12/2025` FLOAT(53),
	`cat__SaleDate_2/17/2025` FLOAT(53),
	`cat__SaleDate_2/18/2025` FLOAT(53),
	`cat__SaleDate_2/19/2025` FLOAT(53),
	`cat__SaleDate_2/2/2025` FLOAT(53),
	`cat__SaleDate_2/20/2025` FLOAT(53),
	`cat__SaleDate_2/21/2025` FLOAT(53),
	`cat__SaleDate_2/22/2025` FLOAT(53),
	`cat__SaleDate_2/23/2025` FLOAT(53),
	`cat__SaleDate_2/24/2025` FLOAT(53),
	`cat__SaleDate_2/25/2025` FLOAT(53),
	`cat__SaleDate_2/3/2025` FLOAT(53),
	`cat__SaleDate_2/6/2025` FLOAT(53),
	`cat__SaleDate_2/7/2025` FLOAT(53),
	`cat__SaleDate_2/9/2025` FLOAT(53),
	`cat__SaleDate_3/12/2025` FLOAT(53),
	`cat__SaleDate_3/16/2025` FLOAT(53),
	`cat__SaleDate_3/17/2025` FLOAT(53),
	`cat__SaleDate_3/18/2025` FLOAT(53),
	`cat__SaleDate_3/20/2025` FLOAT(53),
	`cat__SaleDate_3/21/2025` FLOAT(53),
	`cat__SaleDate_3/22/2025` FLOAT(53),
	`cat__SaleDate_3/23/2025` FLOAT(53),
	`cat__SaleDate_3/24/2025` FLOAT(53),
	`cat__SaleDate_3/25/2025` FLOAT(53),
	`cat__SaleDate_3/27/2025` FLOAT(53),
	`cat__SaleDate_3/28/2025` FLOAT(53),
	`cat__SaleDate_3/3/2025` FLOAT(53),
	`cat__SaleDate_3/30/2025` FLOAT(53),
	`cat__SaleDate_3/31/2025` FLOAT(53),
	`cat__SaleDate_3/4/2025` FLOAT(53),
	`cat__SaleDate_3/5/2025` FLOAT(53),
	`cat__SaleDate_3/6/2025` FLOAT(53),
	`cat__SaleDate_3/7/2025` FLOAT(53),
	`cat__SaleDate_3/8/2025` FLOAT(53),
	`cat__SaleDate_3/9/2025` FLOAT(53),
	`cat__SaleDate_4/1/2025` FLOAT(53),
	`cat__SaleDate_4/11/2025` FLOAT(53),
	`cat__SaleDate_4/15/2025` FLOAT(53),
	`cat__SaleDate_4/16/2025` FLOAT(53),
	`cat__SaleDate_4/19/2025` FLOAT(53),
	`cat__SaleDate_4/22/2025` FLOAT(53),
	`cat__SaleDate_4/23/2025` FLOAT(53),
	`cat__SaleDate_4/27/2025` FLOAT(53),
	`cat__SaleDate_4/28/2025` FLOAT(53),
	`cat__SaleDate_4/3/2025` FLOAT(53),
	`cat__SaleDate_4/5/2025` FLOAT(53),
	`cat__SaleDate_4/7/2025` FLOAT(53),
	`cat__SaleDate_4/8/2025` FLOAT(53),
	`cat__SaleDate_4/9/2025` FLOAT(53),
	`cat__SaleDate_5/10/2025` FLOAT(53),
	`cat__SaleDate_5/11/2025` FLOAT(53),
	`cat__SaleDate_5/12/2025` FLOAT(53),
	`cat__SaleDate_5/13/2025` FLOAT(53),
	`cat__SaleDate_5/14/2025` FLOAT(53),
	`cat__SaleDate_5/15/2025` FLOAT(53),
	`cat__SaleDate_5/18/2025` FLOAT(53),
	`cat__SaleDate_5/22/2025` FLOAT(53),
	`cat__SaleDate_5/23/2025` FLOAT(53),
	`cat__SaleDate_5/24/2025` FLOAT(53),
	`cat__SaleDate_5/25/2024` FLOAT(53),
	`cat__SaleDate_5/25/2025` FLOAT(53),
	`cat__SaleDate_5/26/2024` FLOAT(53),
	`cat__SaleDate_5/28/2024` FLOAT(53),
	`cat__SaleDate_5/3/2025` FLOAT(53),
	`cat__SaleDate_5/31/2024` FLOAT(53),
	`cat__SaleDate_5/5/2025` FLOAT(53),
	`cat__SaleDate_5/7/2025` FLOAT(53),
	`cat__SaleDate_6/1/2024` FLOAT(53),
	`cat__SaleDate_6/11/2024` FLOAT(53),
	`cat__SaleDate_6/13/2024` FLOAT(53),
	`cat__SaleDate_6/14/2024` FLOAT(53),
	`cat__SaleDate_6/15/2024` FLOAT(53),
	`cat__SaleDate_6/16/2024` FLOAT(53),
	`cat__SaleDate_6/17/2024` FLOAT(53),
	`cat__SaleDate_6/18/2024` FLOAT(53),
	`cat__SaleDate_6/19/2024` FLOAT(53),
	`cat__SaleDate_6/22/2024` FLOAT(53),
	`cat__SaleDate_6/24/2024` FLOAT(53),
	`cat__SaleDate_6/27/2024` FLOAT(53),
	`cat__SaleDate_6/29/2024` FLOAT(53),
	`cat__SaleDate_6/30/2024` FLOAT(53),
	`cat__SaleDate_6/4/2024` FLOAT(53),
	`cat__SaleDate_6/5/2024` FLOAT(53),
	`cat__SaleDate_6/6/2024` FLOAT(53),
	`cat__SaleDate_6/7/2024` FLOAT(53),
	`cat__SaleDate_6/9/2024` FLOAT(53),
	`cat__SaleDate_7/13/2024` FLOAT(53),
	`cat__SaleDate_7/14/2024` FLOAT(53),
	`cat__SaleDate_7/15/2024` FLOAT(53),
	`cat__SaleDate_7/16/2024` FLOAT(53),
	`cat__SaleDate_7/17/2024` FLOAT(53),
	`cat__SaleDate_7/18/2024` FLOAT(53),
	`cat__SaleDate_7/20/2024` FLOAT(53),
	`cat__SaleDate_7/21/2024` FLOAT(53),
	`cat__SaleDate_7/26/2024` FLOAT(53),
	`cat__SaleDate_7/27/2024` FLOAT(53),
	`cat__SaleDate_7/28/2024` FLOAT(53),
	`cat__SaleDate_7/31/2024` FLOAT(53),
	`cat__SaleDate_7/4/2024` FLOAT(53),
	`cat__SaleDate_7/5/2024` FLOAT(53),
	`cat__SaleDate_7/7/2024` FLOAT(53),
	`cat__SaleDate_7/8/2024` FLOAT(53),
	`cat__SaleDate_7/9/2024` FLOAT(53),
	`cat__SaleDate_8/10/2024` FLOAT(53),
	`cat__SaleDate_8/11/2024` FLOAT(53),
	`cat__SaleDate_8/12/2024` FLOAT(53),
	`cat__SaleDate_8/15/2024` FLOAT(53),
	`cat__SaleDate_8/2/2024` FLOAT(53),
	`cat__SaleDate_8/20/2024` FLOAT(53),
	`cat__SaleDate_8/21/2024` FLOAT(53),
	`cat__SaleDate_8/22/2024` FLOAT(53),
	`cat__SaleDate_8/23/2024` FLOAT(53),
	`cat__SaleDate_8/24/2024` FLOAT(53),
	`cat__SaleDate_8/25/2024` FLOAT(53),
	`cat__SaleDate_8/29/2024` FLOAT(53),
	`cat__SaleDate_8/3/2024` FLOAT(53),
	`cat__SaleDate_8/31/2024` FLOAT(53),
	`cat__SaleDate_8/5/2024` FLOAT(53),
	`cat__SaleDate_8/7/2024` FLOAT(53),
	`cat__SaleDate_8/8/2024` FLOAT(53),
	`cat__SaleDate_9/1/2024` FLOAT(53),
	`cat__SaleDate_9/10/2024` FLOAT(53),
	`cat__SaleDate_9/15/2024` FLOAT(53),
	`cat__SaleDate_9/2/2024` FLOAT(53),
	`cat__SaleDate_9/20/2024` FLOAT(53),
	`cat__SaleDate_9/22/2024` FLOAT(53),
	`cat__SaleDate_9/25/2024` FLOAT(53),
	`cat__SaleDate_9/26/2024` FLOAT(53),
	`cat__SaleDate_9/27/2024` FLOAT(53),
	`cat__SaleDate_9/28/2024` FLOAT(53),
	`cat__SaleDate_9/29/2024` FLOAT(53),
	`cat__SaleDate_9/30/2024` FLOAT(53),
	`cat__SaleDate_9/5/2024` FLOAT(53),
	`cat__SaleDate_9/6/2024` FLOAT(53),
	`cat__SaleDate_9/8/2024` FLOAT(53),
	`cat__CurrencyType_OMR` FLOAT(53),
	`cat__CurrencyType_USD` FLOAT(53),
	`cat__CurrencyType_Usd` FLOAT(53),
	`cat__CurrencyType_usd` FLOAT(53),
	`cat__CustomerID_0104ec48-84a4-4638-9ed4-dad335d44c43` FLOAT(53),
	`cat__CustomerID_0403d558-166d-4616-9f3e-98d3d7414d35` FLOAT(53),
	`cat__CustomerID_0437bab5-0dae-422e-9d2d-719091ea2dd9` FLOAT(53),
	`cat__CustomerID_045081fa-0df3-4904-820b-067b4176fb85` FLOAT(53),
	`cat__CustomerID_051e499e-f4d0-4a1e-a595-21fc69b2db45` FLOAT(53),
	`cat__CustomerID_0534e616-cbd9-4eba-82bf-f3903ad76eb9` FLOAT(53),
	`cat__CustomerID_05d39b68-833c-45d0-9af3-c0b3bad43a5c` FLOAT(53),
	`cat__CustomerID_05d75424-135a-40ea-9f43-7297d527e0e0` FLOAT(53),
	`cat__CustomerID_07991be5-0500-4bdc-95bc-a3ee50f4d268` FLOAT(53),
	`cat__CustomerID_0822d2d7-9454-4aa3-95bc-b869d6957852` FLOAT(53),
	`cat__CustomerID_089f6dd7-f901-4521-a02c-eb1bf002c6c7` FLOAT(53),
	`cat__CustomerID_0957271b-9145-4838-a842-c40eddb6a2f6` FLOAT(53),
	`cat__CustomerID_0b4a7550-cb81-475b-b8f0-4d4e9668f7e8` FLOAT(53),
	`cat__CustomerID_0bbb7256-0ad2-4b07-a1b0-cba178732f64` FLOAT(53),
	`cat__CustomerID_0bffb839-d519-494d-8b15-9498de261bd6` FLOAT(53),
	`cat__CustomerID_0dadb5f8-e924-45a5-806b-681dd7aebdea` FLOAT(53),
	`cat__CustomerID_0e57e6c8-d5c5-43fa-919e-3640f6ebba01` FLOAT(53),
	`cat__CustomerID_0ead620f-7c7d-4908-bdda-c73282d77d87` FLOAT(53),
	`cat__CustomerID_0ec24f4e-0f17-4c4c-8b16-7b53519d7ce2` FLOAT(53),
	`cat__CustomerID_103bc58d-7df8-47ae-988b-8738b4b2b050` FLOAT(53),
	`cat__CustomerID_104d0c3e-ccfc-43a7-b3e7-e1c56e986cdd` FLOAT(53),
	`cat__CustomerID_10c8ed7e-bba0-4f05-99b7-c72d90c66aaf` FLOAT(53),
	`cat__CustomerID_10f25bba-5c31-4c70-b065-e050a9b6803a` FLOAT(53),
	`cat__CustomerID_11444ef2-a6c9-42e9-8015-6446784d11a7` FLOAT(53),
	`cat__CustomerID_124ea517-d2c8-4ce0-8b00-fcdcfecff89e` FLOAT(53),
	`cat__CustomerID_134fd311-9094-4aef-9068-78b44f308566` FLOAT(53),
	`cat__CustomerID_13c53f9f-0f5f-492c-8660-001021d8745e` FLOAT(53),
	`cat__CustomerID_14cd77f7-8505-47df-a916-b64aae66ebd2` FLOAT(53),
	`cat__CustomerID_15c37dcb-1c11-4482-b1fc-da11997f0d63` FLOAT(53),
	`cat__CustomerID_15fda73e-7b88-4ad7-85c9-d23d8187e574` FLOAT(53),
	`cat__CustomerID_174cb239-fa9b-49fc-88b8-052996b04e57` FLOAT(53),
	`cat__CustomerID_186c1f4d-5f57-49c0-98c6-e20b6fb281bf` FLOAT(53),
	`cat__CustomerID_1889ca5a-60c6-4da8-8289-4cd9af1f7152` FLOAT(53),
	`cat__CustomerID_1a26ed92-27bd-4be2-8386-45682bfc37f5` FLOAT(53),
	`cat__CustomerID_1a52951e-af95-4353-aed3-385ce0718034` FLOAT(53),
	`cat__CustomerID_1b35b6d8-800e-4972-879e-7235f8840cb3` FLOAT(53),
	`cat__CustomerID_1b626cad-36b0-4cd8-ad1a-5bae2dc27b61` FLOAT(53),
	`cat__CustomerID_1b96902d-270f-44ad-8e0c-b401104aaadb` FLOAT(53),
	`cat__CustomerID_1cc1e21a-c2e5-4616-a5cf-a544eb8a944e` FLOAT(53),
	`cat__CustomerID_1e871ef8-cdf7-4f1b-888f-18086f3dc030` FLOAT(53),
	`cat__CustomerID_1f3219ac-02a6-455b-af6a-87711e6653d1` FLOAT(53),
	`cat__CustomerID_1f696c4e-14d1-40b4-a151-52968f14a663` FLOAT(53),
	`cat__CustomerID_22974c53-2595-473f-bbd2-9f309d5e742f` FLOAT(53),
	`cat__CustomerID_232d1545-43b1-477b-ac22-4b1d25b9f81a` FLOAT(53),
	`cat__CustomerID_2398f009-a88e-4af1-b32e-e9eaf1c0409c` FLOAT(53),
	`cat__CustomerID_23eef71c-2019-4005-b8ac-c849cc15b25a` FLOAT(53),
	`cat__CustomerID_2520f9ed-572a-45a1-96af-3d25c78e1b98` FLOAT(53),
	`cat__CustomerID_259051fc-5e0b-49ed-b0a7-09140016fe70` FLOAT(53),
	`cat__CustomerID_25debb26-0ef4-4c61-a5bc-dc5d74696803` FLOAT(53),
	`cat__CustomerID_267f6422-e359-4bb5-98c9-300691a129bf` FLOAT(53),
	`cat__CustomerID_27055332-a7e4-4ed9-a629-240d59715f87` FLOAT(53),
	`cat__CustomerID_2763a02b-2940-4497-931c-db0ad39455be` FLOAT(53),
	`cat__CustomerID_276d23d2-aa88-4056-9480-acc4c7d6a499` FLOAT(53),
	`cat__CustomerID_27f9e498-f3d9-4c22-a051-8b1bd11e4fad` FLOAT(53),
	`cat__CustomerID_28db4b77-bf17-4d5e-8c81-aa62e84a1b6e` FLOAT(53),
	`cat__CustomerID_2a5e6434-a903-4944-ac8c-aedf06d19d05` FLOAT(53),
	`cat__CustomerID_2ac529aa-c34d-4dcd-9f91-ba34671c0e28` FLOAT(53),
	`cat__CustomerID_2b06b9cf-bfd9-4a6b-809c-ae5d5b4202e1` FLOAT(53),

In [50]:
print(df_final.columns.tolist())

['num__Qty', 'num__Unit_Price', 'cat__ProductName_Actually', 'cat__ProductName_Adams_Brush', 'cat__ProductName_Alexander_Spray', 'cat__ProductName_Allen_Brush', 'cat__ProductName_Allen_Notebook', 'cat__ProductName_Anderson_Lamp', 'cat__ProductName_Arnold_Fork', 'cat__ProductName_Arnold_Speaker', 'cat__ProductName_Arnold_Stick', 'cat__ProductName_Bailey_Drill', 'cat__ProductName_Baker_Speaker', 'cat__ProductName_Ball_Notebook', 'cat__ProductName_Banks_Gloves', 'cat__ProductName_Barker_Book', 'cat__ProductName_Barker_Deodorant', 'cat__ProductName_Barnes_Belt', 'cat__ProductName_Barrett_Basket', 'cat__ProductName_Bell_Glove', 'cat__ProductName_Bennett_Lock', 'cat__ProductName_Black', 'cat__ProductName_Boone_Balm', 'cat__ProductName_Boone_Polish', 'cat__ProductName_Bowen_Tire', 'cat__ProductName_Brooks_Cap', 'cat__ProductName_Bryant_Brush', 'cat__ProductName_Butler_Jacket', 'cat__ProductName_Cameron_Fan', 'cat__ProductName_Carter_Fan', 'cat__ProductName_Case', 'cat__ProductName_Chavez_Printer', 'cat__ProductName_Clark_Glass', 'cat__ProductName_Cole_Disk', 'cat__ProductName_Cole_Polish', 'cat__ProductName_Coleman_Case', 'cat__ProductName_Collins_Rug', 'cat__ProductName_Conner_Gel', 'cat__ProductName_Cook_Ball', 'cat__ProductName_Cook_Tray', 'cat__ProductName_Cooper_Knife', 'cat__ProductName_Cox_Screw', 'cat__ProductName_Cross_Rack', 'cat__ProductName_Daniels_Coat', 'cat__ProductName_Dean_Screw', 'cat__ProductName_Dean_Shelf', 'cat__ProductName_Dennis_Mug', 'cat__ProductName_Diaz_Soap', 'cat__ProductName_Dixon_Marker', 'cat__ProductName_Doyle_Grip', 'cat__ProductName_Doyle_Powder', 'cat__ProductName_Edwards_Mixer', 'cat__ProductName_Evans_Tape', 'cat__ProductName_Fisher_Clip', 'cat__ProductName_Fisher_Cover', 'cat__ProductName_Fleming_Tray', 'cat__ProductName_Flores_Coat', 'cat__ProductName_Flowers_Thread', 'cat__ProductName_Ford_Gel', 'cat__ProductName_Foster_Hat', 'cat__ProductName_Foster_Hook', 'cat__ProductName_Fox_Calendar', 'cat__ProductName_Franklin_Bag', 'cat__ProductName_Gardner_Sheet', 'cat__ProductName_Gibbs_Cream', 'cat__ProductName_Gibson_Clock', 'cat__ProductName_Gilbert_Pad', 'cat__ProductName_Gonzales_Sock', 'cat__ProductName_Graham_Cleaner', 'cat__ProductName_Gray_Tool', 'cat__ProductName_Green_Folder', 'cat__ProductName_Gregory_Helmet', 'cat__ProductName_Griffin_Cream', 'cat__ProductName_Hall_Cup', 'cat__ProductName_Hamilton_Paste', 'cat__ProductName_Hanson_Flashlight', 'cat__ProductName_Harmon_Net', 'cat__ProductName_Harper_Phone', 'cat__ProductName_Harris_Pen', 'cat__ProductName_Hayes_Lotion', 'cat__ProductName_Henderson_Gear', 'cat__ProductName_Hill_Phone', 'cat__ProductName_Holland_Nail', 'cat__ProductName_Holmes_Book', 'cat__ProductName_Holmes_Hook', 'cat__ProductName_Horton_Cable', 'cat__ProductName_Howard_Can', 'cat__ProductName_Hudson_Lamp', 'cat__ProductName_Hughes_Strap', 'cat__ProductName_Ingram_Booklet', 'cat__ProductName_Jackson_Cable', 'cat__ProductName_James_Grip', 'cat__ProductName_Jenkins_Valve', 'cat__ProductName_Johnson_Mirror', 'cat__ProductName_Johnson_Screen', 'cat__ProductName_Jordan_Bleach', 'cat__ProductName_Kelly_String', 'cat__ProductName_Lane_Mug', 'cat__ProductName_Larson_Rack', 'cat__ProductName_Lee_Clock', 'cat__ProductName_Lewis_Ruler', 'cat__ProductName_Line', 'cat__ProductName_Lloyd_Mixer', 'cat__ProductName_Long_Mat', 'cat__ProductName_Marsh_Jar', 'cat__ProductName_Martin_Charger', 'cat__ProductName_Matthews_Plate', 'cat__ProductName_Mitchell_Frame', 'cat__ProductName_Moody_Net', 'cat__ProductName_Moore_Chair', 'cat__ProductName_Morgan_Stick', 'cat__ProductName_Morris_Bottle', 'cat__ProductName_Morris_Tray', 'cat__ProductName_Murphy_Dish', 'cat__ProductName_Myers_Shampoo', 'cat__ProductName_Nelson_Knife', 'cat__ProductName_Newman_Rod', 'cat__ProductName_On', 'cat__ProductName_Owens_Powder', 'cat__ProductName_Owens_Tape', 'cat__ProductName_Page_Pen', 'cat__ProductName_Palmer_Screen', 'cat__ProductName_Parker_Cable', 'cat__ProductName_Patterson_Filter', 'cat__ProductName_Perez_Board', 'cat__ProductName_Perry_Switch', 'cat__ProductName_Peterson_Sheet', 'cat__ProductName_Phillips_Hook', 'cat__ProductName_Pierce_File', 'cat__ProductName_Pierce_Plate', 'cat__ProductName_Potter_Shield', 'cat__ProductName_Powell_Tube', 'cat__ProductName_Price_Clip', 'cat__ProductName_Ramirez_Bar', 'cat__ProductName_Reed_Rack', 'cat__ProductName_Reid_Strap', 'cat__ProductName_Richardson_Nail', 'cat__ProductName_Rivera_Block', 'cat__ProductName_Rivers_Lid', 'cat__ProductName_Roberts_Ingredient', 'cat__ProductName_Roberts_Pen', 'cat__ProductName_Robinson_Shelf', 'cat__ProductName_Rodriguez_Keyboard', 'cat__ProductName_Rogers_Lid', 'cat__ProductName_Ross_Cover', 'cat__ProductName_Russell_Oil', 'cat__ProductName_Sanchez_Book', 'cat__ProductName_Sanders_Pin', 'cat__ProductName_Sanderson_Spray', 'cat__ProductName_Scott_Plate', 'cat__ProductName_Simmons_Shorts', 'cat__ProductName_Sims_Brush', 'cat__ProductName_Skill', 'cat__ProductName_Smith_Bag', 'cat__ProductName_Smith_Paper', 'cat__ProductName_Soon', 'cat__ProductName_Spencer_Frame', 'cat__ProductName_Stevens_Cap', 'cat__ProductName_Stewart_Mouse', 'cat__ProductName_Sullivan_Wax', 'cat__ProductName_Swanson_Bucket', 'cat__ProductName_Taylor_Table', 'cat__ProductName_Torres_Stand', 'cat__ProductName_Torres_Table', 'cat__ProductName_Tucker_Helmet', 'cat__ProductName_Turner_Pad', 'cat__ProductName_Vang_Charger', 'cat__ProductName_Vasquez_Bottle', 'cat__ProductName_Wade_Charger', 'cat__ProductName_Walker_Camera', 'cat__ProductName_Wallace_Polish', 'cat__ProductName_Wallace_Sheet', 'cat__ProductName_Ward_Plug', 'cat__ProductName_Warren_Lamp', 'cat__ProductName_Washington_Skirt', 'cat__ProductName_Watson_Chain', 'cat__ProductName_Welch_Mirror', 'cat__ProductName_Welch_Spray', 'cat__ProductName_West_Shine', 'cat__ProductName_White_Monitor', 'cat__ProductName_Williams_Bottle', 'cat__ProductName_Wood_Tire', 'cat__ProductName_Woods_Detergent', 'cat__ProductName_Young_Printer', 'cat__SaleDate_1/1/2025', 'cat__SaleDate_1/10/2025', 'cat__SaleDate_1/11/2025', 'cat__SaleDate_1/15/2025', 'cat__SaleDate_1/16/2025', 'cat__SaleDate_1/19/2025', 'cat__SaleDate_1/20/2025', 'cat__SaleDate_1/21/2025', 'cat__SaleDate_1/22/2025', 'cat__SaleDate_1/23/2025', 'cat__SaleDate_1/24/2025', 'cat__SaleDate_1/5/2025', 'cat__SaleDate_1/6/2025', 'cat__SaleDate_1/7/2025', 'cat__SaleDate_1/9/2025', 'cat__SaleDate_10/10/2024', 'cat__SaleDate_10/11/2024', 'cat__SaleDate_10/12/2024', 'cat__SaleDate_10/13/2024', 'cat__SaleDate_10/14/2024', 'cat__SaleDate_10/15/2024', 'cat__SaleDate_10/17/2024', 'cat__SaleDate_10/18/2024', 'cat__SaleDate_10/19/2024', 'cat__SaleDate_10/20/2024', 'cat__SaleDate_10/21/2024', 'cat__SaleDate_10/25/2024', 'cat__SaleDate_10/26/2024', 'cat__SaleDate_10/27/2024', 'cat__SaleDate_10/4/2024', 'cat__SaleDate_10/6/2024', 'cat__SaleDate_10/8/2024', 'cat__SaleDate_11/1/2024', 'cat__SaleDate_11/10/2024', 'cat__SaleDate_11/11/2024', 'cat__SaleDate_11/13/2024', 'cat__SaleDate_11/18/2024', 'cat__SaleDate_11/19/2024', 'cat__SaleDate_11/2/2024', 'cat__SaleDate_11/22/2024', 'cat__SaleDate_11/23/2024', 'cat__SaleDate_11/24/2024', 'cat__SaleDate_11/25/2024', 'cat__SaleDate_11/26/2024', 'cat__SaleDate_11/3/2024', 'cat__SaleDate_11/30/2024', 'cat__SaleDate_11/5/2024', 'cat__SaleDate_11/6/2024', 'cat__SaleDate_11/7/2024', 'cat__SaleDate_11/8/2024', 'cat__SaleDate_11/9/2024', 'cat__SaleDate_12/1/2024', 'cat__SaleDate_12/13/2024', 'cat__SaleDate_12/15/2024', 'cat__SaleDate_12/17/2024', 'cat__SaleDate_12/18/2024', 'cat__SaleDate_12/2/2024', 'cat__SaleDate_12/20/2024', 'cat__SaleDate_12/24/2024', 'cat__SaleDate_12/25/2024', 'cat__SaleDate_12/26/2024', 'cat__SaleDate_12/27/2024', 'cat__SaleDate_12/28/2024', 'cat__SaleDate_12/29/2024', 'cat__SaleDate_12/3/2024', 'cat__SaleDate_12/31/2024', 'cat__SaleDate_12/7/2024', 'cat__SaleDate_12/9/2024', 'cat__SaleDate_2/10/2025', 'cat__SaleDate_2/11/2025', 'cat__SaleDate_2/12/2025', 'cat__SaleDate_2/17/2025', 'cat__SaleDate_2/18/2025', 'cat__SaleDate_2/19/2025', 'cat__SaleDate_2/2/2025', 'cat__SaleDate_2/20/2025', 'cat__SaleDate_2/21/2025', 'cat__SaleDate_2/22/2025', 'cat__SaleDate_2/23/2025', 'cat__SaleDate_2/24/2025', 'cat__SaleDate_2/25/2025', 'cat__SaleDate_2/3/2025', 'cat__SaleDate_2/6/2025', 'cat__SaleDate_2/7/2025', 'cat__SaleDate_2/9/2025', 'cat__SaleDate_3/12/2025', 'cat__SaleDate_3/16/2025', 'cat__SaleDate_3/17/2025', 'cat__SaleDate_3/18/2025', 'cat__SaleDate_3/20/2025', 'cat__SaleDate_3/21/2025', 'cat__SaleDate_3/22/2025', 'cat__SaleDate_3/23/2025', 'cat__SaleDate_3/24/2025', 'cat__SaleDate_3/25/2025', 'cat__SaleDate_3/27/2025', 'cat__SaleDate_3/28/2025', 'cat__SaleDate_3/3/2025', 'cat__SaleDate_3/30/2025', 'cat__SaleDate_3/31/2025', 'cat__SaleDate_3/4/2025', 'cat__SaleDate_3/5/2025', 'cat__SaleDate_3/6/2025', 'cat__SaleDate_3/7/2025', 'cat__SaleDate_3/8/2025', 'cat__SaleDate_3/9/2025', 'cat__SaleDate_4/1/2025', 'cat__SaleDate_4/11/2025', 'cat__SaleDate_4/15/2025', 'cat__SaleDate_4/16/2025', 'cat__SaleDate_4/19/2025', 'cat__SaleDate_4/22/2025', 'cat__SaleDate_4/23/2025', 'cat__SaleDate_4/27/2025', 'cat__SaleDate_4/28/2025', 'cat__SaleDate_4/3/2025', 'cat__SaleDate_4/5/2025', 'cat__SaleDate_4/7/2025', 'cat__SaleDate_4/8/2025', 'cat__SaleDate_4/9/2025', 'cat__SaleDate_5/10/2025', 'cat__SaleDate_5/11/2025', 'cat__SaleDate_5/12/2025', 'cat__SaleDate_5/13/2025', 'cat__SaleDate_5/14/2025', 'cat__SaleDate_5/15/2025', 'cat__SaleDate_5/18/2025', 'cat__SaleDate_5/22/2025', 'cat__SaleDate_5/23/2025', 'cat__SaleDate_5/24/2025', 'cat__SaleDate_5/25/2024', 'cat__SaleDate_5/25/2025', 'cat__SaleDate_5/26/2024', 'cat__SaleDate_5/28/2024', 'cat__SaleDate_5/3/2025', 'cat__SaleDate_5/31/2024', 'cat__SaleDate_5/5/2025', 'cat__SaleDate_5/7/2025', 'cat__SaleDate_6/1/2024', 'cat__SaleDate_6/11/2024', 'cat__SaleDate_6/13/2024', 'cat__SaleDate_6/14/2024', 'cat__SaleDate_6/15/2024', 'cat__SaleDate_6/16/2024', 'cat__SaleDate_6/17/2024', 'cat__SaleDate_6/18/2024', 'cat__SaleDate_6/19/2024', 'cat__SaleDate_6/22/2024', 'cat__SaleDate_6/24/2024', 'cat__SaleDate_6/27/2024', 'cat__SaleDate_6/29/2024', 'cat__SaleDate_6/30/2024', 'cat__SaleDate_6/4/2024', 'cat__SaleDate_6/5/2024', 'cat__SaleDate_6/6/2024', 'cat__SaleDate_6/7/2024', 'cat__SaleDate_6/9/2024', 'cat__SaleDate_7/13/2024', 'cat__SaleDate_7/14/2024', 'cat__SaleDate_7/15/2024', 'cat__SaleDate_7/16/2024', 'cat__SaleDate_7/17/2024', 'cat__SaleDate_7/18/2024', 'cat__SaleDate_7/20/2024', 'cat__SaleDate_7/21/2024', 'cat__SaleDate_7/26/2024', 'cat__SaleDate_7/27/2024', 'cat__SaleDate_7/28/2024', 'cat__SaleDate_7/31/2024', 'cat__SaleDate_7/4/2024', 'cat__SaleDate_7/5/2024', 'cat__SaleDate_7/7/2024', 'cat__SaleDate_7/8/2024', 'cat__SaleDate_7/9/2024', 'cat__SaleDate_8/10/2024', 'cat__SaleDate_8/11/2024', 'cat__SaleDate_8/12/2024', 'cat__SaleDate_8/15/2024', 'cat__SaleDate_8/2/2024', 'cat__SaleDate_8/20/2024', 'cat__SaleDate_8/21/2024', 'cat__SaleDate_8/22/2024', 'cat__SaleDate_8/23/2024', 'cat__SaleDate_8/24/2024', 'cat__SaleDate_8/25/2024', 'cat__SaleDate_8/29/2024', 'cat__SaleDate_8/3/2024', 'cat__SaleDate_8/31/2024', 'cat__SaleDate_8/5/2024', 'cat__SaleDate_8/7/2024', 'cat__SaleDate_8/8/2024', 'cat__SaleDate_9/1/2024', 'cat__SaleDate_9/10/2024', 'cat__SaleDate_9/15/2024', 'cat__SaleDate_9/2/2024', 'cat__SaleDate_9/20/2024', 'cat__SaleDate_9/22/2024', 'cat__SaleDate_9/25/2024', 'cat__SaleDate_9/26/2024', 'cat__SaleDate_9/27/2024', 'cat__SaleDate_9/28/2024', 'cat__SaleDate_9/29/2024', 'cat__SaleDate_9/30/2024', 'cat__SaleDate_9/5/2024', 'cat__SaleDate_9/6/2024', 'cat__SaleDate_9/8/2024', 'cat__CurrencyType_OMR', 'cat__CurrencyType_USD', 'cat__CurrencyType_Usd', 'cat__CurrencyType_usd', 'cat__CustomerID_0104ec48-84a4-4638-9ed4-dad335d44c43', 'cat__CustomerID_0403d558-166d-4616-9f3e-98d3d7414d35', 'cat__CustomerID_0437bab5-0dae-422e-9d2d-719091ea2dd9', 'cat__CustomerID_045081fa-0df3-4904-820b-067b4176fb85', 'cat__CustomerID_051e499e-f4d0-4a1e-a595-21fc69b2db45', 'cat__CustomerID_0534e616-cbd9-4eba-82bf-f3903ad76eb9', 'cat__CustomerID_05d39b68-833c-45d0-9af3-c0b3bad43a5c', 'cat__CustomerID_05d75424-135a-40ea-9f43-7297d527e0e0', 'cat__CustomerID_07991be5-0500-4bdc-95bc-a3ee50f4d268', 'cat__CustomerID_0822d2d7-9454-4aa3-95bc-b869d6957852', 'cat__CustomerID_089f6dd7-f901-4521-a02c-eb1bf002c6c7', 'cat__CustomerID_0957271b-9145-4838-a842-c40eddb6a2f6', 'cat__CustomerID_0b4a7550-cb81-475b-b8f0-4d4e9668f7e8', 'cat__CustomerID_0bbb7256-0ad2-4b07-a1b0-cba178732f64', 'cat__CustomerID_0bffb839-d519-494d-8b15-9498de261bd6', 'cat__CustomerID_0dadb5f8-e924-45a5-806b-681dd7aebdea', 'cat__CustomerID_0e57e6c8-d5c5-43fa-919e-3640f6ebba01', 'cat__CustomerID_0ead620f-7c7d-4908-bdda-c73282d77d87', 'cat__CustomerID_0ec24f4e-0f17-4c4c-8b16-7b53519d7ce2', 'cat__CustomerID_103bc58d-7df8-47ae-988b-8738b4b2b050', 'cat__CustomerID_104d0c3e-ccfc-43a7-b3e7-e1c56e986cdd', 'cat__CustomerID_10c8ed7e-bba0-4f05-99b7-c72d90c66aaf', 'cat__CustomerID_10f25bba-5c31-4c70-b065-e050a9b6803a', 'cat__CustomerID_11444ef2-a6c9-42e9-8015-6446784d11a7', 'cat__CustomerID_124ea517-d2c8-4ce0-8b00-fcdcfecff89e', 'cat__CustomerID_134fd311-9094-4aef-9068-78b44f308566', 'cat__CustomerID_13c53f9f-0f5f-492c-8660-001021d8745e', 'cat__CustomerID_14cd77f7-8505-47df-a916-b64aae66ebd2', 'cat__CustomerID_15c37dcb-1c11-4482-b1fc-da11997f0d63', 'cat__CustomerID_15fda73e-7b88-4ad7-85c9-d23d8187e574', 'cat__CustomerID_174cb239-fa9b-49fc-88b8-052996b04e57', 'cat__CustomerID_186c1f4d-5f57-49c0-98c6-e20b6fb281bf', 'cat__CustomerID_1889ca5a-60c6-4da8-8289-4cd9af1f7152', 'cat__CustomerID_1a26ed92-27bd-4be2-8386-45682bfc37f5', 'cat__CustomerID_1a52951e-af95-4353-aed3-385ce0718034', 'cat__CustomerID_1b35b6d8-800e-4972-879e-7235f8840cb3', 'cat__CustomerID_1b626cad-36b0-4cd8-ad1a-5bae2dc27b61', 'cat__CustomerID_1b96902d-270f-44ad-8e0c-b401104aaadb', 'cat__CustomerID_1cc1e21a-c2e5-4616-a5cf-a544eb8a944e', 'cat__CustomerID_1e871ef8-cdf7-4f1b-888f-18086f3dc030', 'cat__CustomerID_1f3219ac-02a6-455b-af6a-87711e6653d1', 'cat__CustomerID_1f696c4e-14d1-40b4-a151-52968f14a663', 'cat__CustomerID_22974c53-2595-473f-bbd2-9f309d5e742f', 'cat__CustomerID_232d1545-43b1-477b-ac22-4b1d25b9f81a', 'cat__CustomerID_2398f009-a88e-4af1-b32e-e9eaf1c0409c', 'cat__CustomerID_23eef71c-2019-4005-b8ac-c849cc15b25a', 'cat__CustomerID_2520f9ed-572a-45a1-96af-3d25c78e1b98', 'cat__CustomerID_259051fc-5e0b-49ed-b0a7-09140016fe70', 'cat__CustomerID_25debb26-0ef4-4c61-a5bc-dc5d74696803', 'cat__CustomerID_267f6422-e359-4bb5-98c9-300691a129bf', 'cat__CustomerID_27055332-a7e4-4ed9-a629-240d59715f87', 'cat__CustomerID_2763a02b-2940-4497-931c-db0ad39455be', 'cat__CustomerID_276d23d2-aa88-4056-9480-acc4c7d6a499', 'cat__CustomerID_27f9e498-f3d9-4c22-a051-8b1bd11e4fad', 'cat__CustomerID_28db4b77-bf17-4d5e-8c81-aa62e84a1b6e', 'cat__CustomerID_2a5e6434-a903-4944-ac8c-aedf06d19d05', 'cat__CustomerID_2ac529aa-c34d-4dcd-9f91-ba34671c0e28', 'cat__CustomerID_2b06b9cf-bfd9-4a6b-809c-ae5d5b4202e1', 'cat__CustomerID_2d98daef-5cd8-44e7-aabc-154098880873', 'cat__CustomerID_32b91cd3-6311-4bf8-913f-1cb56ae199cb', 'cat__CustomerID_335688a6-b5d5-43c2-9966-38f716e828af', 'cat__CustomerID_34367237-9710-472d-9c25-5de7d3338499', 'cat__CustomerID_360fe30b-679e-47b9-bad8-f6f83ea74d84', 'cat__CustomerID_36d9aaf8-ef33-4a3e-8d4e-e6d1634b3b13', 'cat__CustomerID_3739bab7-1700-4841-a849-12a9f64564e4', 'cat__CustomerID_3b847e21-2766-4906-be24-552deb14b1c0', 'cat__CustomerID_3ca4e50e-0b3c-4093-97aa-0203a3cb6c84', 'cat__CustomerID_3cbf55c8-e008-4a02-9af3-9030443f7d2a', 'cat__CustomerID_3e6ad095-88f3-4d04-8b4f-dcfbb945dd51', 'cat__CustomerID_3ec28f56-6bb9-4553-bdcc-07b13c1b305f', 'cat__CustomerID_40ff5ca1-8aac-4425-9ac4-167210e0516d', 'cat__CustomerID_422bd69c-04a6-44d4-a4c1-15742a394bb3', 'cat__CustomerID_428eb1da-66ef-49e5-afc0-217079c16ab6', 'cat__CustomerID_435ecb46-4545-4af7-b72c-119f64d193a5', 'cat__CustomerID_43c38201-7183-4b79-88eb-2e3a33ffa4bc', 'cat__CustomerID_45e80c31-76d0-4fd0-b052-15be1e44ffaf', 'cat__CustomerID_471f88e1-e40d-4308-a591-7e3cb6eacf1c', 'cat__CustomerID_481e094b-2c28-48f0-81af-e1c1b319dd95', 'cat__CustomerID_484cb4e5-c44b-4967-93bc-89aef0677f4c', 'cat__CustomerID_4891ece4-fa78-4615-a06a-099bc89e573b', 'cat__CustomerID_48a52f0d-8edb-4a09-a079-573347382fd6', 'cat__CustomerID_48f8ca73-3c11-4d49-aeeb-02c9aa3ec7f8', 'cat__CustomerID_4aad0387-5b47-43f0-9b19-12bd39f86c31', 'cat__CustomerID_4afc9a88-1a93-4ec1-91dd-18bb63497ea2', 'cat__CustomerID_4ec70c3a-b353-4ea7-b437-bbdc3ee4cc6e', 'cat__CustomerID_4f3cb6cf-b60e-49aa-b61c-a1bbed8c8f2c', 'cat__CustomerID_546ef9ad-fc0e-4f4e-af6e-d78188f6373e', 'cat__CustomerID_5550173a-dc5f-4ffc-9ae3-225fbfa52142', 'cat__CustomerID_55eb5681-5dca-4690-991c-378a0119f76b', 'cat__CustomerID_56db1f35-4912-4506-bdcb-454b361283d7', 'cat__CustomerID_57199f1f-09f2-42da-8cef-b6ce6a412e1f', 'cat__CustomerID_5967e79d-9931-4ea9-8129-8c9aeae4c90d', 'cat__CustomerID_5a63a128-3213-47c8-b945-18709cc3df2b', 'cat__CustomerID_5aa3340c-3207-4be3-83af-28d8daffd8c0', 'cat__CustomerID_5ae26050-8ef0-4a6a-b066-c0ab0f8f000e', 'cat__CustomerID_5bbc6d30-0977-478f-b951-9f2cd98564af', 'cat__CustomerID_5ce3e057-5846-41b1-9d5a-7f56f8aa778b', 'cat__CustomerID_620d689c-ecfc-470d-95d3-4a770c0e2724', 'cat__CustomerID_657ae642-e290-46fb-a314-8ac34d345ec6', 'cat__CustomerID_66784559-57f6-4506-a4af-07d797937c8b', 'cat__CustomerID_67ac2bb7-f822-49ef-b717-7957f7b40b8b', 'cat__CustomerID_691df20b-7bb8-4a7b-8a4b-07a997a311fa', 'cat__CustomerID_699da3f7-d7cf-448c-a483-3506c42d685e', 'cat__CustomerID_69ded101-847c-488c-99e4-438c05361804', 'cat__CustomerID_6cec3841-9a48-4baa-84a0-08b1184ebd71', 'cat__CustomerID_6d1e722b-f021-40d1-b632-79c8bac35bd8', 'cat__CustomerID_6d6bf428-c920-4e22-84a5-3b5574889784', 'cat__CustomerID_6da0ca26-e56e-41e1-89b0-004aa6d74b3e', 'cat__CustomerID_6ed6e2b1-3a9c-42c4-a493-1e177948a9fc', 'cat__CustomerID_70a05a3b-f927-4429-8d10-f6242ca3c905', 'cat__CustomerID_7104bf3b-ffeb-4fca-b012-0e623e9fc141', 'cat__CustomerID_722ce28c-e0ef-47f2-a3cc-91d1372bebaf', 'cat__CustomerID_72a815bf-d3e6-444a-8467-61f4157b6bc2', 'cat__CustomerID_7483887b-54a5-4722-af8f-8ff753116c08', 'cat__CustomerID_74b4076b-51e3-4ee8-a997-424a9550c915', 'cat__CustomerID_74cff845-5f2b-400a-bf18-0f3cb5e0fab8', 'cat__CustomerID_75ba74dd-7ada-4f1d-9bf1-b95d2aaabd98', 'cat__CustomerID_75d8418d-cfed-4264-8371-5240b329ae85', 'cat__CustomerID_77048ffd-c5a7-47f9-8e77-c1a9c5745c2d', 'cat__CustomerID_77a1b5da-d82a-4fc6-9e8c-d39d3cd1a19c', 'cat__CustomerID_7841d94f-ae84-4401-9d60-d489b97d8151', 'cat__CustomerID_78c4328d-f82b-4402-b617-aa92f2cca99d', 'cat__CustomerID_7a2e9e34-b07f-4ef0-bded-ac378df3efd6', 'cat__CustomerID_7b1e02c1-ecf9-404f-9394-ee8e66efa50c', 'cat__CustomerID_7c680274-3c15-495c-b873-51d0caf70312', 'cat__CustomerID_7ca80b40-9f31-4c1f-a093-65ce89565f36', 'cat__CustomerID_7f18df12-a14a-45a4-8ede-68137fa2ff57', 'cat__CustomerID_81d45348-605d-48cf-9f4f-56b238b6a54f', 'cat__CustomerID_82436cac-c3df-4c41-8c22-e5f3cb83361b', 'cat__CustomerID_8263d1e9-1cd2-4843-bcac-3c56d400fb28', 'cat__CustomerID_829aa7f3-773d-4131-9290-9790588fda4f', 'cat__CustomerID_82c0bacf-b86f-47ee-a10f-e7119321466a', 'cat__CustomerID_838c2400-adf0-47bb-91b1-5055ed708224', 'cat__CustomerID_83de3a26-0f09-4821-97cd-111a28e1be39', 'cat__CustomerID_85746df4-64ad-49ac-88a4-a582cc382075', 'cat__CustomerID_862c2ac0-e5d1-4079-aa33-7e46d62793bf', 'cat__CustomerID_86c2d109-c411-48d9-8d1c-0e4c9cf09711', 'cat__CustomerID_86f1d0e1-f0ec-4632-82f3-1f232c8221e7', 'cat__CustomerID_87ad2648-ee78-498b-9cc6-4d5fd4353b94', 'cat__CustomerID_88391e29-dd77-41ac-aeb3-2000ac46b31f', 'cat__CustomerID_88e499a8-56da-4a23-816a-ab63e11b4fe1', 'cat__CustomerID_89a7e081-4883-437a-9cbb-0692e6d6d7eb', 'cat__CustomerID_89e1228a-da9a-4b60-96ca-32e0476a9b3b', 'cat__CustomerID_8a92685f-22de-4bde-8abb-48b670e75e56', 'cat__CustomerID_8c48b22a-26b3-4dba-a69f-05ebc37f1ea2', 'cat__CustomerID_8e0e97d9-775f-46f9-854c-7ea868042afa', 'cat__CustomerID_8fd37b5c-55cd-4d3f-9be6-74bc3c06bbaf', 'cat__CustomerID_90bef402-ff6a-4cf7-87b3-b5dd0fddec0a', 'cat__CustomerID_90e743f7-167e-4b98-ac06-a352d9bdfaa1', 'cat__CustomerID_90fbe81f-ec15-4681-9a0c-9b311cca8220', 'ca

In [51]:
cols = df_final.columns.str.lower()
dups = cols[cols.duplicated(keep=False)]
print(df_final.columns[cols.duplicated(keep=False)])

Index(['cat__CurrencyType_USD', 'cat__CurrencyType_Usd',
       'cat__CurrencyType_usd', 'cat__StoreID_STORE_A',
       'cat__StoreID_Store_A'],
      dtype='str')

In [52]:
df_final.columns = df_final.columns.str.lower().str.replace("-", "_")

In [53]:
def clean_text(x):
    return (
        str(x)
        .strip()
        .lower()
        .replace(" ", "_")
        .replace("-", "_")
    )

In [54]:
cat_cols = ["StoreID", "ProductName", "CurrencyType"]

for col in cat_cols:
    df[col] = df[col].apply(clean_text)

In [55]:
from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

def clean_df(X):
    X = X.copy()
    for col in X.columns:
        X[col] = X[col].astype(str).str.strip().str.lower().str.replace("-", "_").str.replace(" ", "_")
    return X

In [56]:
preprocess = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
], remainder="passthrough")

pipeline = Pipeline([
    ("cleaning", FunctionTransformer(clean_df)),
    ("preprocess", preprocess)
])

In [57]:
df[cat_cols].nunique()
df[cat_cols].head()

   StoreID     ProductName CurrencyType
0  store_a  johnson_mirror          usd
1  store_a     roberts_pen          usd
2  store_a   white_monitor          usd
3  store_a     moore_chair          nan
4  store_a   jackson_cable          usd

NameError: name 'X_train' is not defined

In [59]:
df_final.to_sql(
    "sales_processed",
    con=engine,
    if_exists="replace",
    index=False,
    method="multi"
)

DuplicateColumnError: A column with name 'cat__currencytype_usd' is already present in table 'sales_processed'.

In [60]:
df_final.columns[df_final.columns.duplicated()]

Index(['cat__currencytype_usd', 'cat__currencytype_usd',
       'cat__storeid_store_a', 'cat__storeid_store_a'],
      dtype='str')

In [61]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

In [62]:
preprocess = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
        ("num", StandardScaler(), num_cols)
    ],
    remainder="drop"   # مهم جدًا
)

NameError: name 'num_cols' is not defined

In [63]:
# 1. تحديد الأعمدة
cat_cols = ["StoreID", "ProductName", "CurrencyType"]
num_cols = ["Qty", "Unit_Price"]

# 2. preprocessing
preprocess = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
    ("num", StandardScaler(), num_cols)
])

# 3. pipeline
from sklearn.pipeline import Pipeline

model = Pipeline([
    ("preprocess", preprocess)
])

In [64]:
X_transformed = preprocess.fit_transform(df)

In [65]:
import pandas as pd

X_transformed = X_transformed.toarray()

In [66]:
df_final = pd.DataFrame(X_transformed)

In [67]:
ohe = preprocess.named_transformers_["cat"]

cat_names = ohe.get_feature_names_out(cat_cols)
num_names = num_cols

all_names = list(cat_names) + list(num_names)

df_final.columns = all_names

In [68]:
df_final = df_final.loc[:, ~df_final.columns.duplicated()]

In [69]:
df_final.to_sql(
    "sales_processed",
    con=engine,
    if_exists="replace",
    index=False
)

100

In [71]:
import pandas as pd

def reverse_one_hot(df, prefix):
    cols = [c for c in df.columns if c.startswith(prefix)]
    
    df[prefix] = df[cols].idxmax(axis=1).str.replace(prefix + "_", "")
    
    df = df.drop(columns=cols)
    return df

In [72]:
df = reverse_one_hot(df, "CurrencyType")

In [73]:
df = reverse_one_hot(df, "ProductName")